### ISSUE TITLE
[Button] `variantColor` does not work with `COLOR_NAME.600`

### ISSUE THREAD

**Issue by xxczaki** [chakra-ui/chakra-ui#253] opened 2019-11-17 18:41 UTC
I want to set Button's `variantColor` to `blue.600` (from the [default theme](https://chakra-ui.com/theme#blue)):

```jsx
<Button m={2} variantColor="blue.600" variant="solid">
	LinkedIn
</Button>
```

Unfortunately, it doesn't fully render the button (no text, color, shape; only on hover text underline is visible). When I use `variantColor="blue"` it works correctly:

![](https://imgur.com/T82i35Q.png)

It also doesn't work with other colors, ex. `red.300`.

**Comment by lee-reinhardt** [comment] 2019-11-18 18:35
Dupe of #203

**Comment by xxczaki** [comment] 2019-11-18 20:14
@lee-reinhardt I don’t think so. #203 is about using a custom color, whereas mine is about a color from the default theme.

**Comment by lee-reinhardt** [comment] 2019-11-18 23:01
@xxczaki If you read Segun's answer, he explains why you can't pass a plain color, or even theme-config color like `blue.600` to the `variantColor` prop. The button component has behavior that relies on using more than one value from the theme variant color specified [source](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Button/styles.js#L95).

> The reason is that Button has interactive styles (hover, action, disabled) and we pick color values from the object to make it work out of the box.

You can work around this by making your own entry in the theme colors that satisfies all the numbers, or override styles via `_active`, `_hover`, etc. props.

**Comment by segunadebayo** [comment] 2019-12-02 17:43
Thanks for the response @lee-reinhardt.

@xxczaki, the reason is `variantColor` expects the **color key**, not the specific color, we that internally to manage the hover, active, disabled styling of the button.

Check this: https://chakra-ui.com/theme#blue, and pass color keys like `blue`, `green`, `orange`, `red`, etc. for it to work.

In the future, this will be declarative but you either try my suggestion above or create your own button from `PseudoBox` component. Hope this helps.

**Closed by segunadebayo** 2019-12-02 17:43 UTC

**Comment by sethburtonhall** [comment] 2021-01-05 16:07
I thought it would be helpful to share [this code sandbox](https://codesandbox.io/s/divine-surf-p19px?file=/src/App.tsx:0-86) for anyone with the same issue.

Thanks @dodas !!
