### ISSUE TITLE
Slider not working

### ISSUE THREAD

**Issue by danchitnis** [chakra-ui/chakra-ui#3849] opened 2021-04-18 05:19 UTC
# 🐛 Bug report

Slider is not working properly. Once dragged, it will not move again

## 💥 Steps to reproduce

create a slider as described here:
https://chakra-ui.com/docs/form/slider

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-ui-slider-bxhub?file=/src/index.js

## 🧭 Possible Solution

slider works fine on version 1.5.0

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.5.1       |
| Browser          |      Chrome 90      |
| Operating System |       Windows 10     |

**Comment by with-heart** [comment] 2021-04-18 14:27
Closing as duplicate of #3818

**Closed by with-heart** 2021-04-18 14:27 UTC
