### ISSUE TITLE
remove `chakra-*` class names from prod builds

### ISSUE THREAD

**Issue by MariuzM** [chakra-ui/chakra-ui#2685] opened 2020-12-01 21:12 UTC
I've noticed that in Prod builds `chakra-` classes are being added, but they are not being used. So why would we need them especially in Prod builds? 

I think having an option to remove them make sense, i feel now that cluttering html classes with this, especially considering they are not being used and just there.

![Screen Shot 2020-12-01 at 20 56 51](https://user-images.githubusercontent.com/36937039/100797380-ed00a000-3419-11eb-971c-24cd3968991b.png)

**Comment by with-heart** [comment] 2020-12-01 22:58
We added these so users can target individual elements of Chakra components for extensibility purposes, like integrating with other style systems or legacy styles.

**Comment by MariuzM** [comment] 2020-12-01 23:01
Hm but does this help to target them when in this example i already see two elements with same class name? I guess this is to target as a global stack, button and so on element. But i know from my projects i never done it like so, so i feel in my case i believe there will be more, people will complain that this is polluting the DOM. 

Having an option to remove them would be best solution i think

**Comment by with-heart** [comment] 2020-12-01 23:07
> does this help to target them when in this example i already see two elements with same class name

Yes, this is fairly traditional css behavior. Like most other things, we can't predict what users will or won't need to target or how they do the targeting, but this at least gives them the option to do so.

Gonna close this as a duplicate of #2229. You should be able to achieve this in your own build process using [`babel-plugin-react-remove-classname`](https://www.npmjs.com/package/babel-plugin-react-remove-classname) or something similar.

**Closed by with-heart** 2020-12-01 23:07 UTC

**Comment by MariuzM** [comment] 2020-12-01 23:09
I have already tried using this plugin and it did not work. 

So looks like you just guys going to force something on us before asking community do they really need this and if some one does need it give an option but not force a feature that some people will not want.

**Comment by ljosberinn** [comment] 2020-12-01 23:45
Besides as target for global selectors which actually _have_ been requested, this feature also allows easier descendant selectors:

![image](https://user-images.githubusercontent.com/29307652/100809209-e8e27b80-3435-11eb-8a37-bc6dc436d122.png)

**Comment by MariuzM** [comment] 2020-12-01 23:48
I do understand that some people love this feature but i still can't help but think that this is polluting the DOM. I'm fine trying to use 3rd party tools such as `babel-plugin-react-remove-classname` but i have tried it it does not delete the `chakra-*` classes, other classes that i have randomly added it does, so either there more that Chakra is  doing in the background or i have no idea :( 

I just wish you guys gives an option instead of enforcing this, because i know I'm not the only one who will complain about this.

**Comment by ljosberinn** [comment] 2020-12-01 23:49
Said babel plugin doesnt seem to go through node_module imports too which is unfortunate; only through class names you yourself added. Chakra is not doing anything special here, those classnames are just plain strings.

**Comment by MariuzM** [comment] 2020-12-01 23:50
Any other workaround on this, thoughts / suggestions?

**Comment by bbcntolga** [comment] 2022-02-13 15:03
I'm also interested in any solution for this. There should be an option to disable the naming in a production build. Im wondering if chakra does not have anything yet...

**Comment by mdunbavan** [comment] 2022-08-18 08:50
This is really disappointing that it has not been resolved or this issue has not been raised since Feb! This is an issue for a lot of people I think and something that needs to be resolved.

**Comment by bbcntolga** [comment] 2022-08-18 09:56
@with-heart Maybe this should be a issue to think about. There should be an easy integrated way in chakra to replace the "chakra" prefix with some other string.
