### ISSUE TITLE
<Stack> with <StackDivider> When set direction and spacing responsibly, it will be broken.

### ISSUE THREAD

**Issue by Qrymy** [chakra-ui/chakra-ui#2523] opened 2020-11-16 04:38 UTC
# Bug report

## Describe the bug

In `<Stack>` component with `<StackDivider>`, if I set `direction` and `spacing` props responsibly, it will ignore `spacing` in minimum width(= mobile viewport).

## To reproduce

```jsx
<Stack
  spacing={[10, 20]}
  divider={<StackDivider borderColor="black" />}
  direction={["column", "row"]}
>
  <Box bgColor="red.500">First</Box>
  <Box bgColor="blue.500">Second</Box>
  <Box bgColor="yellow.500">Third</Box>
</Stack>
```

## Minimal reproduction

<https://codesandbox.io/s/late-haze-lm54t?file=/src/app.tsx:151-422&resolutionWidth=461&resolutionHeight=675>

## Expected behavior

- Depends on `spacing` prop, it should be space correctly.

## System information

- OS: macOS 10.15.7 (19H2)
- Browser (if applies): Chrome 86.0.4240.198
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: v12.18.3

## Additional context

None.

**Comment by segunadebayo** [comment] 2020-11-19 08:45
I just pushed a fix for this. Thanks for catching it.

**Closed by segunadebayo** 2020-11-19 08:45 UTC

**Comment by violabg** [comment] 2022-09-02 14:05
I think the problem is back with 2.3.1
