### ISSUE TITLE
AspectRatio component is not visible when used inside a flex container

### ISSUE THREAD

**Issue by CarterMcAlister** [chakra-ui/chakra-ui#2582] opened 2020-11-20 21:11 UTC
# Bug report

## Describe the bug
The AspectRatio component is not visible if it is used inside of a component with `display:flex` on it.

## To reproduce
* Place a `AspectRatio` component is used inside of a flex container.
* `AspectRatio` component will not be visible in the DOM and have a height/width of 0 when inspected.

## Minimal reproduction
https://codesandbox.io/s/flexbox-aspect-ratio-chakra-4w1jm?file=/src/App.tsx

## Expected behavior
The AspectRatio component should be visible and work the same as it does when not in a flex container.

## System information
- OS: macOS
- Browser (if applies): Chrome/Firefox
- @chakra-ui/react v1.0.0

**Comment by TimKolberger** [comment] 2020-11-25 12:21
The children of a flex container need a defined width. 
You can apply `minWidth`, `width` or `flex="1 1 auto"` to define a width for a flex container child - otherwise it will be indefinite and not visible.

Closing this issue, because it is not a bug in chakra UI. 
Feel free to join our discord and ask for help if you need further assistance! :)

**Closed by TimKolberger** 2020-11-25 12:21 UTC

**Comment by epshtielsl** [comment] 2022-08-15 19:49
> The children of a flex container need a defined width. You can apply `minWidth`, `width` or `flex="1 1 auto"` to define a width for a flex container child - otherwise it will be indefinite and not visible.
> 
> Closing this issue, because it is not a bug in chakra UI. Feel free to join our discord and ask for help if you need further assistance! :)

Setting the minWidth or width defeats the purpose of the AspectRatio component does it not?

**Comment by TimKolberger** [comment] 2022-08-15 20:14
The element height will scale according to the given aspect ratio. 

When the width is zero, the height will be zero as well: not visible.

When the width is dynamic, the height will be computed with the given aspect ratio according to the current width: visible.
