### ISSUE TITLE
Typescript: No more typings from v2.3.5 onward

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#6972] opened 2022-11-11 20:31 UTC
## Info
Chakra: update from v`2.3.4` to v`2.3.5`
NextJS:  `12.3.3`
VSCode: `1.73.1` (latest version Windows)

## Problem
Just after updating Chakra, pretty much all my files went red in VSCode. VSCode couldn't load the types from `.d.ts` files anymore.

> Could not find a declaration file for module '@chakra-ui/react'. 'd:/_dev/thethirdrace.com/node_modules/@chakra-ui/react/dist/index.cjs.js' implicitly has an 'any' type.
>
> Try `npm i --save-dev @types/chakra-ui__react` if it exists or add a new declaration (.d.ts) file containing `declare module '@chakra-ui/react';`ts(7016)

## Attempts at a solution
I looked in the `node_modules` folder, but all the typings are in the package, it's just that VSCode can't figure out how to load them or something.

I cleaned my repo, even cloned it entirely from scratch, same problem. No more typings available from v`2.3.5` onward.

I did try with Chakra `2.3.7` and still has the same problem.

I tried switching NextJS to ESM, still the same problem, but referencing the ESM modules 😒.

As soon as I revert to Chakra `2.3.4`, everything goes back to normal.

## The "solution"

While trying to setup the codesandbox for this issue, I accidently changed the `moduleResolution` value in my `tsconfig.json` and it fixed the issue.

With Chakra `2.3.4` and many versions prior, I used the value `nodenext` as it's supposed to be the latest and most up-to-date value to use going forward with Node `16.x`.

Turns out, with Chakra `2.3.5` onward, this doesn't work anymore. I had to switch back to the old `node` value for it to work.

It seems the new way to export packages in Chakra `2.3.5` is conflicting with the latest node module resolution mode.

Why? Absolutely no idea... but I think Chakra should look into it because this was definitely working just fine in `2.3.4` and it should work in the future too since that's where Node is trying to move everybody towards this new method...

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-next-js-typescript-kxvyr

### Chakra UI Version

2.3.5

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2022-11-14 10:41
This is already fixed in the codebase. It was caused by not having `types` field in the exports we used previously.

We'll release a new version shortly.

**Closed by segunadebayo** 2022-11-14 10:41 UTC
