### ISSUE TITLE
[v1 Button and maybe more components] Default size lost on page refresh

### ISSUE THREAD

**Issue by tomhicks** [chakra-ui/chakra-ui#1227] opened 2020-07-15 08:21 UTC
In the current docs if you go to this page: https://next.chakra-ui.com/docs/form/button directly (a full page load) then the button has no default size and loses all its padding, font size, etc..

If you navigate from another doc page to that one in the sidebar, the default size is there, and the button looks right.

**Comment by navin-moorthy** [comment] 2020-07-16 04:46
I noticed this too. This is an issue only happening in Gatsby I guess.
I am using Next JS to test, there seems to be no issues.

**Comment by segunadebayo** [comment] 2020-07-17 12:40
@navin-moorthy, do you have a Next.js version of the docs?

My hunch tells me it's an issue with Gatsby and I'm thinking of the reverting to Next.js for the docs.

**Comment by navin-moorthy** [comment] 2020-07-17 15:08
> @navin-moorthy, do you have a Next.js version of the docs?
> 
> My hunch tells me it's an issue with Gatsby and I'm thinking of the reverting to Next.js for the docs.

@segunadebayo I don't have the docs in Next.js but I my Next.js site(WIP) with button added to it.
You can check it for clarifications.

We can move our Docs from `Gatsby` to `Next.js` but we should find the cause of the bug(may be sometimes later) so that this don't appear later.

**Comment by segunadebayo** [comment] 2020-08-06 13:01
This has been fixed in the docs. We'll update the docs shortly.

Thanks for catching this @tomhicks

**Closed by segunadebayo** 2020-08-06 13:01 UTC
Labels: Type: Bug 🐛
