### ISSUE TITLE
Focus ring lasts when clicking on checkboxes

### ISSUE THREAD

**Issue by emmanuel-bearstudio** [chakra-ui/chakra-ui#5503] opened 2022-02-01 10:32 UTC
### Description

When the checkbox component is selected with the cursor the focus ring (visible part of the focus) will last just as an input component would do. 

### Problem Statement/Justification

The problem here is that this behaviour doesn't match the needs of most of users (Using click with trackpad/mouses and not tabs).  
Being able to tab through checkboxes is a thing (accessibility, etc.) but it should not be on the cost of the experience of most of users. 
It means that on this specific use case, having the focus ring lasting on checkboxes just create an odd feeling of "undone" action and makes the user thinks "Have i checked that properly ?"
I am not complaining about the focus itself. You should still able to tab through checkboxes. However if you use your click to activate/deactivate them, you shouldn't have this visual ring around those checkboxes.

### Proposed Solution or API

When clicking on checkboxes (whether it's a check or an uncheck) you should not have the focus ring that lasts on it. 

- Material UI have this behaviour right (not telling their code solution is the best but it's much more enjoyable for the user). 
Here i can tab through the checkboxes but when i click, the visual part of focus doesn't last.

https://user-images.githubusercontent.com/62236130/151952581-f4ce49de-a4b0-4e49-9322-baab04cd5546.mov

- Here is the behaviour with Html vanilla (same thing here the focus ring doesn't last)

https://user-images.githubusercontent.com/62236130/151952683-8d2d74f7-f488-4280-a061-e059859d8f33.mov

### Alternatives

--

### Additional Information

Here is a vidéo of the issue. You can see the focus lasting after i clicked on the checkbox (Using chakra checkboxes of course).

https://user-images.githubusercontent.com/62236130/151952852-f15a586b-ae17-4184-8223-56d1bb229d28.mov

**Comment by TimKolberger** [comment] 2022-02-05 14:53
Kindly use the package `focus-lock` to remove the focus ring.
Docs: https://chakra-ui.com/docs/migration#css-reset

Closing this because it is not a bug.

**Closed by TimKolberger** 2022-02-05 14:53 UTC
Labels: needs triage
