### ISSUE TITLE
Nextjs with SSR flashes themeless UI

### ISSUE THREAD

**Issue by VickyKoblinski** [chakra-ui/chakra-ui#6192] opened 2022-06-15 01:53 UTC
### Description

When I have cookieStorageManagerSSR on (and do not have ColorModeScript), the first paint flashes a (mostly) unthemed skeleton.

### Link to Reproduction

https://codesandbox.io/s/confident-wing-ztomgs?file=/Chakra.js:378-401

### Steps to reproduce

1. Open Codesandbox link
2. Notice how ColorModeScript in _document is commented out[1]
3. Notice how colorModeManager is set in Chakra.js
4. Open Codesandbox preview to a new window
5. Refresh the page and notice the first render is jarring. Toggle to dark mode, refresh the page and notice it's even more jarring. Turn off Javascript (I use Quick Javascript Switcher chrome extension but you can probably do this from the dev tools) and notice how some elements have received the theme like the button text, but most of the page has not. In dark mode this is especially noticeable as you flash from black to white and then the DOM is updated with the CSS classes.

Bonus:
7. Comment back in ColorModeScript. Refresh and notice that it's so much better!
8. But then toggle the theme and refresh your page. The cookie value was updated but the localStorage was not (confirmed by looking in Application Storage in the devtools). The server now expects one mode and the client expects another which causes a flash (black to white or white to black). 

### Chakra UI Version

2.2.1

### Browser

Chrome 105

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

[1] **ColorModeScript in _document is commented out** -- From the [docs](https://chakra-ui.com/docs/styled-system/features/color-mode#forcing-a-specific-mode): "Also, if you use colorModeManager, you can avoid adding the <ColorModeScript /> to _document.js." and also in this recent PR https://github.com/chakra-ui/chakra-ui/pull/6035/files#diff-2195e3eb593f2d293a26fbbb447b9efae1bf3b08202902799424c8f62872dff6R11-R12

Overall I would think that the cookie would take precedence over the value in localStorage especially since I'm explicitly passing `cookieStorageManagerSSR` to the `colorModeManager`. This can be extra tricky to debug because the localStorage value isn't cleared out in an obvious way and Chakra still acknowledges it even after ColorModeScript is removed.  

There's really two problems at play here, both relating to Next.js and SSR:
1. The SSR is lacking. Is it a bug? It's very unpleasant especially in dark mode. [I found this site](https://devresourc.es/) that's using Chakra and SSR, but there's no flashing and when you turn off JS on the frontend, you can see the server responds with a DOM tree populated with classnames, so I think what's happening now is a bug. 
2. Cookies vs local storage. LocalStorage takes priority and if you're using both colorModeManager and ColorModeScript you're going to have a bad time. You'll have a worse time if you don't use ColorModeScript at all though.

And a bonus^2!
3. When I manually changed ColorModeScript to dark mode, it never would change for me. I bet it was because `light` was in my localStorage. So anyone else out there reading this, go to your `dev tools > Application > Storage > Local Storage` and if you see the key/value there you can right click and delete it :)

**Comment by VickyKoblinski** [comment] 2022-06-19 07:16
I believe I've identified the problem.

https://github.com/chakra-ui/chakra-ui/blob/main/packages/color-mode/src/color-mode-provider.tsx#L103-L125

The color mode is set inside a useSafeLayoutEffect, which means that the theme can't get set server side at all since these hooks only run client side.

As for the part where I talked about it was "preferring local storage", that was sort of true. The thing that was missing and wasn't in the docs is that `<ColorModeScript initialColorMode={theme.config.initialColorMode} />` needs to have `type="cookie"` on it when you're doing cookies. Maybe it's somewhere, but it's not here https://chakra-ui.com/docs/styled-system/features/color-mode :)

**Comment by VickyKoblinski** [comment] 2022-06-20 05:10
I made substantial progress on this: https://codesandbox.io/s/priceless-night-6f0292?file=/pages/_document.js

__document.tsx
```tsx
import { ColorMode } from "@chakra-ui/color-mode";
import { ColorModeScript } from "@chakra-ui/react";
import Document, { Html, Head, Main, NextScript, DocumentContext } from "next/document";

import theme from "theme";

type MaybeColorMode = ColorMode | undefined;

function parseCookie(cookie: string, key: string): MaybeColorMode {
  const match = cookie.match(new RegExp(`(^| )${key}=([^;]+)`));
  return match?.[2] as MaybeColorMode;
}

export default class MyDocument extends Document<{ colorMode: string }> {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx);

    let colorMode: MaybeColorMode = theme.config.initialColorMode;

    if (ctx.req && ctx.req.headers.cookie) {
      colorMode =
        parseCookie(ctx.req.headers.cookie, "chakra-ui-color-mode") || theme.config.initialColorMode;
    }

    return { ...initialProps, colorMode };
  }

  render() {
    const { colorMode } = this.props;

    return (
      <Html data-theme={colorMode} lang="en" style={{ colorScheme: colorMode }}>
        <Head />
        <body className={`chakra-ui-${colorMode}`}>
          {/* <ColorModeScript initialColorMode={theme.config.initialColorMode} type="cookie" /> */}
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

So notably here: I added `data-theme` and `style={{ colorScheme }}` to Html and `className="chakra-ui-{colorMode}"` to body.

This actually works! (I don't really care about colorMode system so I don't know if that one works.)

This is really fantastic and it actually works great!! 

**However** I have a weird side effect. The codesandbox here isn't reproducing it but locally when I refresh the page with javascript on, the text isn't on the page and takes a moment to appear. If I turn JS off, the text is on the page and it looks great. I don't know what's causing the text to disappear.

**Comment by rbozan** [comment] 2022-08-11 07:17
not stale, needs documentation

**Comment by jca41** [comment] 2022-08-13 09:14
Having the same issue with remix SSR

**Comment by GuilhermeAmado** [comment] 2022-09-04 23:35
Same issue here

**Comment by artoruotsala** [comment] 2022-09-12 12:48
I had the same issue. The problem was that I was developing two Next.JS sites - then other one was using Chakra's color mode and stored the value to the cookie. Then running the first page at the same dev address & port loaded the cookie of the second page and messed up the colors.

**Comment by tombohub** [comment] 2022-09-23 09:14
> Having the same issue with remix SSR
 really? I didn't notice any issue. See if you notice aything: https://checklist-remix.vercel.app/

**Comment by xixixao** [comment] 2022-12-30 04:14
I took @VickyKoblinski's example code (https://github.com/chakra-ui/chakra-ui/issues/6192#issuecomment-1159979257) and boiled it down to the minimum to get a theme correctly pre-rendered with NextJS:

```tsx
// pages/_document.tsx
import Document, { Html, Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  render() {
    return (
      <Html data-theme="light" lang="en">
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```

**Comment by woodjs** [comment] 2023-01-28 07:45
> I took @VickyKoblinski's example code ([#6192 (comment)](https://github.com/chakra-ui/chakra-ui/issues/6192#issuecomment-1159979257)) and boiled it down to the minimum to get a theme correctly pre-rendered with NextJS:
> 
> ```tsx
> // pages/_document.tsx
> import Document, { Html, Head, Main, NextScript } from 'next/document'
> 
> export default class MyDocument extends Document {
>   render() {
>     return (
>       <Html data-theme="light" lang="en">
>         <Head />
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </Html>
>     )
>   }
> }
> ```
the question was that if in the settings you have a default color scheme of light, then when you change to dark and when you reload the page, you should initially see a light theme, then a flicker, which will change to dark.

**Comment by woodjs** [comment] 2023-01-28 09:25
How did I manage to solve this problem:
1. Setting the theme color in your config
`const customTheme = {
...
  config: {
    initialColorMode: 'dark',
  },
...
}
`
2. _app.js
`
import { ChakraProvider, cookieStorageManagerSSR } from '@chakra-ui/react';
import theme from '../styles/theme';

function MyApp({ Component, pageProps, cookies }) {
 const colorModeManager = cookieStorageManagerSSR(cookies);

return (
...
     <ChakraProvider colorModeManager={colorModeManager} theme={theme}>
      {children}
    </ChakraProvider>
...
);
}

MyApp.getInitialProps = (data) => {
  const { ctx } = data;
  return {
    cookies: ctx?.req?.headers?.cookie || '',
  };
};

`

As a result, your theme should be rendered on the server side (SSR)

**Comment by Yuripetusko** [comment] 2023-04-26 00:17
While the solution provided by @woodjs works, it opts out the whole nextjs app from `Automatic Static Optimization` due to introduction of `getInitialProps`. I really wish there was a better solution, but so far I cannot find one

**Comment by cgalpin** [comment] 2023-11-08 19:44
Same issue with Next.js 13 App Router as well

**Comment by manakuro** [comment] 2023-11-23 05:43
In Next.js 14 App Router and static rendering, the workaround could be using the `_dark` for each property.

```.ts
const theme = extendTheme({
  styles: {
    global: (props: StyleFunctionProps) => ({
      body: {
        color: "black",
        bg: "white",
        _dark: {
          color: "white",
          bg: "black",
        },
        lineHeight: "base",
      },
    }),
  },
  config: {
    initialColorMode: "dark",
    useSystemColorMode: false,
  },
});
```

**Comment by mpash** [comment] 2023-12-13 21:24
> In Next.js 14 App Router and static rendering, the workaround could be using the `_dark` for each property.
> 
> ```ts
> const theme = extendTheme({
>   styles: {
>     global: (props: StyleFunctionProps) => ({
>       body: {
>         color: "black",
>         bg: "white",
>         _dark: {
>           color: "white",
>           bg: "black",
>         },
>         lineHeight: "base",
>       },
>     }),
>   },
>   config: {
>     initialColorMode: "dark",
>     useSystemColorMode: false,
>   },
> });
> ```

@manakuro I tried your above suggestion to no success. I'm thinking its something to do with how `ColorModeScript` is implemented. Next13/14 complains in the same fashion when you use a script instead of a Script tag for instance.

**Comment by iamv1n** [comment] 2024-06-29 12:02
Can we please have this in documentation?

**Comment by IzumiSy** [comment] 2024-10-02 09:56
Still needs it to be documentated officially.

I have confirmed that just using `type="localStorage"` also works for me.
```tsx
const RootLayout = ({ children }: Readonly<React.PropsWithChildren>) => {
  return (
    <html lang="en">
      <body>
        <ColorModeScript type="localStorage" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
};
```

**Comment by Yuripetusko** [comment] 2024-10-02 10:03
I don't think there's a point for Chakra team and contributors to spend time on this now, since chakra v3 will address this, so it's more productive for them to focus on v3 and for consumers to just wait

**Comment by segunadebayo** [comment] 2024-10-08 14:07
Closing based on https://github.com/chakra-ui/chakra-ui/issues/6192#issuecomment-1367715085 and https://github.com/chakra-ui/chakra-ui/issues/6192#issuecomment-2388176764

Feel free to open a PR to the v2 branch to update the docs.

**Closed by segunadebayo** 2024-10-08 14:07 UTC
