### ISSUE TITLE
createStandaloneToast - when used all texts gets resized

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#4112] opened 2021-05-29 04:09 UTC
```
function CustomToastExample() {
  const toast = createStandaloneToast()
  return (
    <Button
      onClick={() =>
        toast({
          position: "top",
          title: "An error occurred.",
          description: "Unable to create user account.",
          status: "error",
          duration: 3000,
        })
      }
    >
      Show Toast
    </Button>
  )
}
```

When we use createStandaloneToast for displaying toasts - all the text fields in the screen gets resized one and causes a very bad visual effect. Attached a video of same happening in chakra site. Requesting to check this and fix , as its happening throughout my application. Thank you! Using chakra v1.6.2

https://user-images.githubusercontent.com/39894982/120057548-83c4b700-c061-11eb-8a5c-aa3ec255bca0.mov

**Comment by anubra266** [comment] 2021-05-29 11:32
Confirmed opening the toast removes the Custom font and uses default browser system fonts

**Comment by anubra266** [comment] 2021-05-29 11:38
@with-heart, I found the problem. The `createStandalone` toast is not getting a theme object. 
Doing this does not break the fonts
```js
const { theme } = useChakra()
  const toast = createStandaloneToast({
    theme, 
  })
  ```

**Comment by anubra266** [comment] 2021-05-29 11:43
I'll open a PR for this

**Comment by anubra266** [comment] 2021-05-29 12:57
@segunadebayo There's no storybook example for standalone toasts. Mind me opening a PR?

**Comment by with-heart** [comment] 2021-05-29 13:07
> @with-heart,I wouldn't call this a bug. It's a standalone Toast, so the user must provide a theme object.

It defaults to the default theme though if they don't provide one:

https://github.com/chakra-ui/chakra-ui/blob/327f00644d3336fe1e2d3152f9cc3474a18824ef/packages/toast/src/use-toast.tsx#L123-L139

> @segunadebayo There's no storybook example for standalone toasts. Mind me opening a PR?

Don't ask for permission, just open PRs for whatever seems right to you!

**Comment by anubra266** [comment] 2021-05-29 13:08
> Don't ask for permission, just open PRs for whatever seems right to you!
Ok sure...thanks

**Comment by anubra266** [comment] 2021-05-29 13:10
> It defaults to the default theme though if they don't provide one:

But would the default theme contain the theme tokens in our custom theme?  because I passed the Docs' theme to the standaloneToast instead of the defaultTheme, and everything worked just fine.

**Comment by with-heart** [comment] 2021-05-29 13:25
Ahhhhh okay, I see what you're saying. That makes sense. It's a problem specific to anyone using a custom theme that changes font sizes. 

Might be something we just need to document because there's not a way for us to get that custom theme value without it being passed.

**Comment by anubra266** [comment] 2021-05-29 14:53
Yeah...exactly.

**Comment by ganeshkrishnasharma** [comment] 2021-05-29 15:30
Thank you all , Much appreciated 🙏

**Comment by anubra266** [comment] 2021-06-01 09:56
@with-heart we may close this now...I think

**Closed** 2021-06-06 17:41 UTC
Labels: Topic: Documentation 📚
