### ISSUE TITLE
Fractions values not being converted to percentages

### ISSUE THREAD

**Issue by matteo95g** [chakra-ui/chakra-ui#3777] opened 2021-04-09 19:04 UTC
# 🐛 Bug report

Using fractions (1/2, 1/3, 1/4 etc) for setting properties as width, height, etc are being interpreted as actual px values instead of being treated as % as indicated in the documentation: https://chakra-ui.com/docs/features/responsive-styles#under-the-hood

## 💥 Steps to reproduce

The following component ```<Box w={1/2} />``` is rendering with a css width set to 0.5px

## 💻 Link to reproduction

It can be reproduced using the example given here, changing the width to any fraction, like `1/2`: https://chakra-ui.com/docs/layout/flex#usage

![Screen Shot 2021-04-09 at 15 59 06](https://user-images.githubusercontent.com/18466456/114228341-a8978a80-994c-11eb-8073-a2460b36f511.png)

## 🧐 Expected behavior

Per the styled-system docs (https://styled-system.com/#layout), width values between 0 and 1 should be treated as percent widths and not be converted to px values

So in the example above, `1/2` should be translated to `50%`:

![Screen Shot 2021-04-09 at 16 01 46](https://user-images.githubusercontent.com/18466456/114228592-0a57f480-994d-11eb-88d5-f2bc2eedf766.png)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |1.4.2            |
| Browser          |Chrome            |
| Operating System |macOS            |

**Comment by segunadebayo** [comment] 2021-04-13 08:54
Duplicate of #304

**Closed by segunadebayo** 2021-04-13 08:54 UTC

**Comment by matteo95g** [comment] 2021-04-13 12:29
Ok, thanks for the clarification @segunadebayo . Any clue as to whether it will be corrected in the future?
