### ISSUE TITLE
Adding custom sizes for heading tags?

### ISSUE THREAD

**Issue by VarunRustomji** [chakra-ui/chakra-ui#1274] opened 2020-07-17 06:55 UTC
I am building a blog site and using [rich-markdown-editor](https://github.com/outline/rich-markdown-editor) to build the text editor.

The issues I'm having is when I try to assign H1, H2, H3 to my text, the editor dynamically adds h1, h2, h3 but in Chakra the font-size of h1, h2, h3 and p is the same so the text does not get correctly formatted. 

Is there any way to fix this issue?

**Comment by segunadebayo** [comment] 2020-07-17 16:48
This is a duplicate of #1270. I'd recommend you take a look at the suggested solution.

Chakra works pretty well with MDX when you use it with `@mdx/react`

**Closed by segunadebayo** 2020-07-17 16:48 UTC
