### ISSUE TITLE
CLI: Vite mts/mjs config files not recognized

### ISSUE THREAD

**Issue by abrenoch** [chakra-ui/chakra-ui#9021] opened 2024-10-28 15:04 UTC
### Description

It looks like the `mts` and `mjs` versions of `vite.config` are not being checked on this line:

https://github.com/chakra-ui/chakra-ui/blob/b22de5633070d00e2ebc6220bb1a227ec9d0703b/packages/cli/src/utils/context.ts#L26

Which is preventing `npx @chakra-ui/cli snippet add` from working in a project using that naming convention for the vite config.

```
node:internal/fs/utils:699
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

### Link to Reproduction

NA

### Steps to reproduce

Run the `npx @chakra-ui/cli snippet add` command in a project that uses `vite.config.mjs` or `vite.config.mts`

### Chakra UI Version

3

### Browser

NA

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Encountered this while looking into updating the `react-querybuilder` library to work with v3

**Comment by segunadebayo** [comment] 2024-10-28 15:20
Duplicate of #8999

Will get to it shortly

**Closed by segunadebayo** 2024-10-28 15:20 UTC

**Comment by abrenoch** [comment] 2024-10-28 15:22
whoops overlooked that- thanks!
