### ISSUE TITLE
Margins not working due to *:not(style)~*:not(style)

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2578] opened 2020-11-20 11:30 UTC
An unknown style is being applied to elements, so far I can only narrow this down to when using vStack, but I imagine its there in others too. `*:not(style)~*:not(style)`

Will not get the margins applied from this
```
    <VStack>
      <Link href="jamie" m="10rem">
        jamie
      </Link>
      <Text variant="caps3" m="10rem">
        Hello World //no margin left
      </Text>
    </VStack>
```

https://codesandbox.io/s/no-margin-chakra-b56vs

![image](https://user-images.githubusercontent.com/1344898/99795120-2a645400-2b23-11eb-9cbe-56ce5aee8897.png)

**Comment by hutber** [comment] 2020-11-24 09:25
So I guess the fix/solution to this is to never use Margin and only use Paddings?

**Comment by hutber** [comment] 2020-11-27 10:38
This is my fixes currently:
```
        mt={[0, "-3rem !important"]}
        mt={[0, `${space["-1"]} !important`]}
```

**Comment by with-heart** [comment] 2020-11-29 21:17
Yes, this is currently set by `Stack` as part of its styles: https://github.com/chakra-ui/chakra-ui/blob/7eafb24dbe57bd9928e95e1e804a7abb87a44dfb/packages/layout/src/stack.utils.tsx#L22-L27

It's not entirely clear to me why we're setting certain values to `0` when they're not relevant to the direction of the `Stack`. I'm going to mark this as a bug so we can investigate if this is actually necessary, because it shouldn't need to conflict with your other margin styles in this manner.

An easier solution for the time being is to use `<VStack shouldWrapChildren>` which will automatically wrap each the inner element in a `Box`, meaning the margins are applied to the `Box` rather than the children so they can still set their own margins.

**Comment by segunadebayo** [comment] 2020-12-11 10:22
From a usage standpoint, we don't recommend adding custom margins to the children of `HStack`, `VStack` or `Stack`.

If you ever need to, then maybe you don't need to use them and reach for `Flex` or use the `shouldWrapChildren` prop.

@with-heart, setting certain values to `0` is needed to get the responsive spacing to work.

Closing this because it isn't a bug.

**Closed by segunadebayo** 2020-12-11 10:22 UTC
Labels: Type: Bug 🐛

**Comment by hutber** [comment] 2020-12-11 16:25
This is now causing drawing issues:
If you turn off JS, then the page will render without padding:
![image](https://user-images.githubusercontent.com/1344898/101928285-4d879e00-3bcd-11eb-96c9-2ea0402721c3.png)
![image](https://user-images.githubusercontent.com/1344898/101928394-6ee88a00-3bcd-11eb-8d87-99cce66ed9e1.png)

Sadly this means that I always always have to do `pt="5px !important"` every single time

![ezgif-6-e506a93ab179](https://user-images.githubusercontent.com/1344898/101928107-1ca76900-3bcd-11eb-996b-c6baba8dcc44.gif)

**Comment by MariuzM** [comment] 2021-01-02 00:25
Yeah noticed same thing here, so what I've done just created a Moded Stack component adding !important and just using that component in my project.

**Comment by MariuzM** [comment] 2021-01-02 00:44
@hutber this is what i use 
```js
      {...(m && {
        m: m === typeof String ? `${m} !important` : m,
      })}
```

**Comment by hutber** [comment] 2021-01-02 00:46
Thanks Pal, I will play with this. Its driving me absolutely crazy!!!

**Comment by with-heart** [comment] 2021-01-02 11:23
I'm still not understanding what the problem is. Why are you using `Stack` to begin with?

**Comment by MariuzM** [comment] 2021-01-02 11:54
@with-heart because thats something we are use to, and i do the same. Just give us an option when passing `m` to `Stack` then it just need to override that style you guys have instead of us using `!important` 

![Screen Shot 2021-01-02 at 11 53 14](https://user-images.githubusercontent.com/36937039/103456770-354cff80-4cf1-11eb-8b06-986d4ea7caa5.png)

![Screen Shot 2021-01-02 at 11 52 18](https://user-images.githubusercontent.com/36937039/103456769-31b97880-4cf1-11eb-9f60-6cc681cbfc27.png)

**Comment by with-heart** [comment] 2021-01-02 12:00
Could one of you please create a codesandbox example? Screenshots aren't very helpful, I can't tell what's going on or what I'm supposed be looking at, ya know?

**Comment by MariuzM** [comment] 2021-01-02 12:13
https://codesandbox.io/s/currying-platform-qhhfz?file=/src/app.js but noticed I'm getting different behavior with this, so will do the one i have in my project.

**Comment by MariuzM** [comment] 2021-01-02 12:26
@with-heart 
Repo: https://github.com/MariuzM/chakra_issue
Live: https://chakra-issue.vercel.app/

**Comment by TimKolberger** [comment] 2021-01-02 12:31
Your request is technically valid - the margins are getting overridden. But from a design system perspective the current behaviour is correct. The `Stack` component is an approach to solve the issue "which component owns the whitespace". It helps distributing space around nested components. 

**The space around nested components is not their responsibility - they should not interfere with it. This increases the reusability of the component in different contexts.**

We have two tools at hand to apply whitespace: `margin` and `padding`. We have to choose wisely when to use which tool. My mindset when deciding to use margin or padding is:

- `margin` is applied hierarchically from top to bottom (or outside -> inside)
- `padding` is applied hierarchically from bottom to top (or inside -> outside)

E.g. when building a grid, the grid itself distributes space between its nested components with margin. Each nested component can manage its space with padding , but it should never interfere with the spacing from the hierarchy level above.

> In your specific use cases, play it through which component owns which space. When the ownership is clear, the `Space` component will be a blessing to work with and there are no "spacing hickups" in your applications.

IMO the implementation of the Stack component needs no change, because there is no bug if you follow the mentioned design principles to ease your development workflow.

Further references:

- [A blog entry by Max Stoiber about Margins](https://mxstbr.com/thoughts/margin/)
- [A great talk from Mark Dalgleish about how to approach reusable styled components](https://www.youtube.com/watch?v=jnV1u67_yVg)

**Comment by MariuzM** [comment] 2021-01-02 12:36
@timkindberg i only wish that something like this could be included in Stack by default, then this just leaves up to users to work it out, until better solution is implemented. I personally don't want to use another component that i know `Stack` is perfectly capable for what i need, less components to think about better development. 

For me `Stack` is this super div element that can accept css props, hence i use this for most part and adjust my props when needed. 

```js
      {...(m && {
        m: typeof m === 'string' ? `${m} !important` : m,
      })}
```

**Comment by TimKolberger** [comment] 2021-01-02 12:52
We need to follow some design principles to create high quality components. This cannot be solved by any library - some things are left to the developer, because only she/he knows what their goal is.

You don't need to use another component. You just need to use the right tool for the job: 
_Nested components in a `Stack` manage their whitespace with `padding`._ 

CSS uses the model of outer space (`margin`) and inner space (`padding`). The developer has to choose when to use what. And those rules are derived from a design system - chakra UI is based on `styled system`.

We as developers do not only need to known how to code, but how to compose components.
The Stack component is a great example - you stumble over some odd behaviour, learn to distribute space ownership and carry on.

**Comment by MariuzM** [comment] 2021-01-02 12:58
Sorry but i don't really understand how this can be solved without using !important on each Stack component? 

What other component / tool from Chakra UI can we use that does not have this issue and we can set our margins?

**Comment by TimKolberger** [comment] 2021-01-02 13:21
The goal is not to be able to manage every space with `margin`. There are reasons that there are two different tools (margin and padding) to manage whitespace.
The goal is to use the right tool for the right job.

I implemented two different solutions in [your codesandbox](https://codesandbox.io/s/nostalgic-brown-j3q9e?file=/pages/index.js).

1. use a `Box` component to apply padding on the Stack Item
2. use `Wrap` and `WrapItem` because the behaviour you want to implement looks like the `Wrap` component

**Comment by with-heart** [comment] 2021-01-02 13:54
A couple more good resources for this concept:

- https://www.youtube.com/watch?v=0SZfnNh268s

A talk on atomic design systems in React, but the part at 16:33 talks about the distinction between "layout" components and "content" components. `Stack` (or `Wrap` and `WrapItem`) would be one of the "layout" components, while its `children` would be the "content" components.

- https://every-layout.dev/layouts/stack/

A great article from the book "Every Layout" discussing how to build a `Stack` in pure css and its use cases.

**Comment by hutber** [comment] 2021-01-02 14:26
Thank you all for taking the time to lay these things out.

The sandbox was actually linked in the original post, if you wanted to look. But I think the problem is clear to you all now and you can see.

I wonder if it is worth updating the docs to reflect this edge case so others can avoid the pain our team has had. I will certainly push our team away from vstack and hstack in the future. Thank you again!!

@MariuzM I have been using `m="5px !important"` or if you want to use a variable `m={${someVar}px !important}`

**Comment by JakeCoxon** [comment] 2021-04-07 18:25
I came across this issue and it made me realise I was trying to use VStack wrong. 

If you have spacing in between VStack but you want to change the margin in-between two elements. Instead of trying to assign margin to one element like this:
```
    <VStack>
      <A />
      <B />
      <C marginTop="4" />
      <D />
    </VStack>
```
Just do this
```
    <VStack>
      <A />
      <VStack spacing="4">
        <B />
        <C />
      </VStack>
      <D />
    </VStack>
```

This keeps the responsibility of spacing out of the components as the above links suggest

**Comment by JavaJamie** [comment] 2021-08-13 23:19
I'm seeing this weird margin-top issue as well: `.css-n21gh5>*:not(style)~*:not(style)`

I can't seem to remove it, despite putting !important. Is there a fix?

**Comment by JavaJamie** [comment] 2021-08-13 23:20
Also saw this issue. I put spacing to 0 on the stack and it removed it which was good.

**Comment by marwanmakm** [comment] 2021-09-28 03:03
Hello everyone. Well, in my personal case, I had a mix with HStack, Stack and Flex. I resolved it deleting this kind of mixes and trying to write a more unified structure. For example:

Instead of use this:
```
<Stack someprops... >
    <Flex someprops... >
         // MAGIC CODE
    </Flex>
</Stack>
```

I used this:
```
<Flex someprops... >     // flexDirection="column" or any prop to match with my requirements
    <Flex someprops... >
         // MAGIC CODE
    </Flex>
</Flex>
```

Hope this help!

**Comment by vialus** [comment] 2021-11-21 14:03
I am using Flex component and I want to use `margin=auto` to align some elements to one side.  This simple thing for html `flex` element does not work due to this bug,  as this margin=0  in `*:not(style)~*:not(style)` overwrites `<Flex direction='column' mb='auto' >`
Can someone finally fix this bug? Or is this the problem of any design system that offers you a complex elements but prevents doing the simplest thing?

**Comment by mateo2181** [comment] 2021-11-28 17:28
Perhaps not the best solution but using style `style={{margin: 0}}` works.
```
<Stack flexDirection="row" gridGap={4}>
   <Button colorScheme="blue" isLoading={isSubmitting} type="submit" w="full">Save Pet</Button>
   <Button type="button" style={{margin: 0}} w="full">Back to Profile</Button>
</Stack>
```

**Comment by ChristopherWirtOfficial** [comment] 2022-09-18 21:21
To just add some continued vocalization to this issue, the reasons for the style may be good and valid and righteous, but they still lead to a problem that's completely unintuitive. Whether someone is trying to use margin because they don't "know better" (an opinion expressed by Chakra devs in this thread that I also personally agree with) or just because they're wrapping around a library that uses these bad practices, the result is the same.

Developers, especially less experienced ones, run into a problem that is hidden from them and caused by black(box) magic: a hidden default style that affects the children inside in an inconsistent way that they may have trouble explaining. Even after finding the problem in a style explorer, it's not immediately obvious what a good solution for this is. This leads to hacks, bad answers, (some) good answers, and some that are outright wrong and cause further unknown problems.

I'm not saying that the approach isn't right, but I do think some more thought can be put into mitigating the real issue here, which is that the current setup leads to a consistently confusing experience for users of the library.

**Comment by AllanKevinScain** [comment] 2022-11-03 13:21
I created my boiler plate with chakra and I'm anticipating some measurements and styles for my development team.

I want to find a way to intervene in the amount of margin that is added, I'm sure if I could put a different number from the chakra ui theme pattern, this would be the best alternative.

I see that in chakra ui there are some patterns, but these don't work on Stack, only on buttons, inputs....

Does anyone have a tip?

This is my current code:</br>

![image](https://user-images.githubusercontent.com/82052266/199730247-7907ac2c-adab-4ea2-ad89-5d712bc8b3e3.png)</br>
![image](https://user-images.githubusercontent.com/82052266/199730403-f269a3be-ed3f-4fe5-9237-1cd4180c88cb.png)</br>
![image](https://user-images.githubusercontent.com/82052266/199730675-a0b5251e-c0d7-4672-b2aa-129898f8096d.png)</br>
![image](https://user-images.githubusercontent.com/82052266/199730506-306cfb66-b610-4b1c-adeb-97c6516aa9b4.png)</br>

What works for me is putting this in the chakra tag:</br>
![image](https://user-images.githubusercontent.com/82052266/199731534-12644e0c-f7f0-4c42-bf18-4cfc167cf3bc.png)</br>
![image](https://user-images.githubusercontent.com/82052266/199731690-40e79cb8-44bf-4fbc-a89f-fe92fb9b0615.png)</br>

**Comment by superuserpro** [comment] 2024-09-07 18:35
Same https://preprocessor.space/questions/the-troubles-of-top-margins-in-css
