### ISSUE TITLE
Skeleton colorStart and colorEnd should accept theme colors

### ISSUE THREAD

**Issue by arielger** [chakra-ui/chakra-ui#732] opened 2020-05-17 23:47 UTC
**Is your feature request related to a problem? Please describe.**
The Skeleton component (https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Skeleton/index.js) is not mapping the theme colors strings (e.g. "gray.500") in `colorStart` and `colorEnd` properties to theme colors.

**Describe the solution you'd like**
I would like to be able to pass theme colors to those props as we can do with components like Box:

`<Skeleton colorStart="gray.100" colorEnd="gray.200" />

**Comment by with-heart** [comment] 2020-06-28 06:08
Duplicate of #997

**Closed by with-heart** 2020-06-28 06:08 UTC
