### ISSUE TITLE
[Tooltip] does not work properly with a disabled button

### ISSUE THREAD

**Issue by deebov** [chakra-ui/chakra-ui#610] opened 2020-04-16 09:44 UTC
**Describe the bug**
Tooltip does not work properly with a disabled button. Tooltip won't hide after moving out the cursor.

**Expected Behavior**
Tooltip hides after moving out the cursor. 

**To Reproduce**
1. go to https://codesandbox.io/s/white-https-23k7y?file=/src/App.js
2. hover on the button

**Comment by segunadebayo** [comment] 2020-04-16 12:25
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #500. Please subscribe to that issue for future updates.

**Closed by segunadebayo** 2020-04-16 12:25 UTC
