### ISSUE TITLE
used extendTheme not change

### ISSUE THREAD

**Issue by chenzhidongweb** [chakra-ui/chakra-ui#5808] opened 2022-04-02 11:19 UTC
### Description

used extendTheme not change

### Link to Reproduction

none

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This is `theme/index.js` file

```
import Button from './components/button'
import Input from './components/input'
import Drawer from './components/drawer'
import Modal from './components/modal'
import Menu from './components/menu'
import Select from './components/select'
import Tabs from './components/tabs'
import Progress from './components/progress'
import Table from './components/table'
import Toast from './components/toast'
import Switch from './components/switch'
```

```
const overrides = {
  colors,
  styles,
  components: {
    Button,
    Input,
    Drawer,
    Modal,
    Menu,
    Select,
    Tabs,
    Progress,
    Table,
    Toast,
    Switch
  },
}

export default extendTheme(
  overrides,
  withDefaultColorScheme({
    colorScheme: 'purple'
  }),
  withDefaultVariant({
    variant: 'purple'
  })
)
```

This is components file

```
export default {
  variants: {
    bgvariant:{
      bg:'#6F4EF2',
      color: 'red'
    }
  }
}
```

This is use file

```
toast({
    title: "Party started. You successfully invested",
    status: 'success',
    duration: 9000,
    position: "top-right",
    variant:'bgvariant'
  });
```

**Comment by chenzhidongweb** [comment] 2022-04-02 11:20
Style not changed

**Comment by TimKolberger** [comment] 2022-04-02 12:46
Toast uses the Alert component styles from the theme. Try define the variant there.

Kindly add a codesandbox for a reproduction, it is hard for us to help without running Code if you need further assistance 😊

**Comment by chenzhidongweb** [comment] 2022-04-02 13:08
the variant prop can't use Toast component?

**Comment by TimKolberger** [comment] 2022-04-02 13:21
Not quite - useToast renders the Alert component. Code reference: https://github.com/chakra-ui/chakra-ui/blob/main/packages/toast/src/use-toast.tsx

If you want to specify a variant in the ToastOptions, kindly define the variant on the Alert component in the theme.

**Comment by chenzhidongweb** [comment] 2022-04-02 13:34
Ok, But Switch components has Same problem

**Comment by TimKolberger** [comment] 2022-04-02 13:37
Kindly add a reproduction, because the Switch component should work as expected.

**Comment by chenzhidongweb** [comment] 2022-04-02 13:39
```
<Switch variant='blue' _focus={{ outline: "none" }} name='isOpenPart' isChecked={values.isOpenPart} value={values.isOpenPart} onChange={(e) => {
    if (values.isOpenPart) {
      setFormOneData({
        ...initFormOneData,
        tokenRatio: '',
        tokenHolders: '',
        partyName: values.partyName,
        tokenName: values.tokenName
      })
    }
    handleChange(e)
  }} />
```

This is `theme/component/switch.js` file

```
export default {
  size: 'lg',
  variants: {
    blue: {
      color: 'red'
    },
  }
}

```

**Comment by chenzhidongweb** [comment] 2022-04-02 13:42
This is alert component 

```
export default {
  variants: {
    bgvariant:{
      bg:'#6F4EF2',
      color: 'red'
    }
  }
}
```

use file
```
const toast = useToast({
    variant: 'bgvariant'
  });
toast({
    title: "You successfully invested the party amount",
    status: 'success',
    duration: 9000,
    position: "top-right",
    isClosable: true,
  })
```

I tryed, But not has bg

**Comment by chenzhidongweb** [comment] 2022-04-02 13:54
Alert component has four variants props `'solid', 'subtle', 'left-accent', 'top-accent'`
Can't customize toast style, right?

**Comment by TimKolberger** [comment] 2022-04-02 17:23
See this codesandbox for reference: https://codesandbox.io/s/r1ojr

I'll close this issue, because it is not a bug in chakra. Kindly add a reproduction for any further issues.

**Closed by TimKolberger** 2022-04-02 17:23 UTC
Labels: Status: Needs Reproduction ♺
