### ISSUE TITLE
[Toast] Toast styles not being applied with latest beta

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#1229] opened 2020-07-15 12:59 UTC
Using the latest betas

https://codesandbox.io/s/serverless-water-c8szr?file=/src/App.tsx

**Comment by segunadebayo** [comment] 2020-07-15 16:33
This is due to lerna publishing a weird version of some packages. We'll look into this.

**Comment by dmitru** [comment] 2020-07-15 19:24
I can confirm the bug; happens to Alert and Toast components.

**Comment by glenmcrae** [comment] 2020-07-25 07:41
I can confirm this one too for both Alerts and Toast components.

**Comment by maxjustus** [comment] 2020-07-25 22:55
Same is happening to me

**Comment by JClackett** [comment] 2020-07-26 09:37
@segunadebayo will this be fixed soon in one of the beta patch releases?

**Comment by segunadebayo** [comment] 2020-07-27 11:56
This has been fixed in `v1.0.0-rc.0`. Please check again.

Otherwise, I'll re-open this issue.

Cheers

**Closed by segunadebayo** 2020-07-27 11:56 UTC
Labels: Type: Bug 🐛

**Comment by JClackett** [comment] 2020-07-27 12:38
Its working except for when position is "bottom-right" there's now not any padding on the right side?

demo: https://codesandbox.io/s/elated-forest-ul53e?file=/src/App.tsx

**Comment by with-heart** [comment] 2020-07-27 12:42
@JClackett Probably the same issue as #1183

**Comment by JClackett** [comment] 2020-07-27 12:46
@with-heart yep that looks like it
