### ISSUE TITLE
Lazy Popover makes popper log console errors

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#3236] opened 2021-02-01 13:46 UTC
# 🐛 Bug report
When using `isLazy` on a popover (and on development) popper will log (**log**, not throw) the following error when the popover is closed.
```
"Popper: "arrow" modifier's `element` must be a child of the popper element. "
```

## 💥 Steps to reproduce

1. Use `isLazy`
2. Open an close a popover

## 💻 Link to reproduction

https://codesandbox.io/s/happy-visvesvaraya-66sij?file=/src/App.tsx

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.3.2     |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment] 2021-02-09 11:55
Thanks for reporting this issue.

However, this issue is a duplicate of an existing issue #2521. Please subscribe to that issue for future updates.

**Closed by segunadebayo** 2021-02-09 11:55 UTC
