### ISSUE TITLE
@chakra-ui/react >= 1.5 button elements are not compatible with framer-motion

### ISSUE THREAD

**Issue by joel1st** [chakra-ui/chakra-ui#4561] opened 2021-08-13 05:50 UTC
### Description

When I click a button I expect the animations assigned to that button to occur.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-framer-motion-example-forked-v5iir?file=/src/App.js

### Steps to reproduce

After onClick causes a rerender, the `whileHover` and `whileTap` on a Chakra/Frame Motion button no longer work. This issue only presents itself after v1.4.2

Working Animated button (@chakra-ui/react:1.4.2)
https://codesandbox.io/s/chakra-ui-framer-motion-example-forked-70j93?file=/src/App.js:178-184

Failing Animated button (@chakra-ui/react:1.6.6)
https://codesandbox.io/s/chakra-ui-framer-motion-example-forked-v5iir?file=/src/App.js

### Chakra UI Version

1.6.6

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by primos63** [comment] 2021-08-16 17:48
This bug was introduced in @chakra-ui/react v1.5.2 with @chakra-ui/button v1.3.0. I know the reason for this happening and have a fix. The issue I'm having is in writing the test that catches the issue in the current release.

As far as I can tell, there are no tests which include `framer-motion` with chakra components. I've created one for button which simulates the user actions, but both the current module and my fixed module pass all tests. That's not the case when using the browser. The current module fails as described in the issue and my fixed module does not fail.

As a result, I've not submitted a PR. If one of the core team members would let me know how to proceed that would be awesome. The change to the code base was 1 line modified. The test has many more lines of code!

**Comment by segunadebayo** [comment] 2021-09-09 10:30
Possibly a duplicate of #4623. I just pushed a fix for it.

**How I fixed it:**
The problem was related to how `motion` works under the hood. It seems to require a very stable `ref` to get it working correctly so I swapped out: `mergeRefs` function with a memoized `useMergeRefs` hook.

**Closed by segunadebayo** 2021-09-09 10:30 UTC
Labels: Type: Bug 🐛, needs triage
