### ISSUE TITLE
The colorMode property is undefined for custom themes

### ISSUE THREAD

**Issue by maxcnunes** [chakra-ui/chakra-ui#2646] opened 2020-11-27 19:16 UTC
# Bug report

## Describe the bug

When using a custom theme, `colorMode` isn't provided as part of the theme properties.

## To reproduce

1. Create a fresh new react project `yarn create react-app my-app --template @chakra-ui/typescript`
2. Change `src/App.tsx` to use a custom theme like this:

```jsx
...
import { extendTheme } from '@chakra-ui/react';

const customTheme = extendTheme({
  styles: {
    global: (props) => ({
      body: {
        bg: (props: any) => {
          console.log('***theme colorMode', props.colorMode);
          return props.colorMode === 'dark' ? 'red.300' : 'yellow.300';
        },
      },
    }),
  },
});

export const App = () => (
  <ChakraProvider theme={customTheme}>
...
```
3. Start the app `yarn start`
4. Look at the Developer tools > console, the `colorMode` is undefined

## Minimal reproduction

https://github.com/maxcnunes/chakra-app-colorMode-undefined

## Expected behavior

The same way the default theme, changes the background based on the color mode ([here](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/styles.ts#L8)), I would expect to have the same behavior for custom themes too.

## System information

- OS: macOS Big Sur 11.0.1 (20B29)
- Browser: Chrome
- Version of @chakra-ui/react: 1.0.1
- Version of Node.js: v14.11.0

**Comment by TimKolberger** [comment] 2020-11-27 19:30
In your provided code snippet and repository is the `props` argument shadowed. 
Please see this updated example and [an updated codesandbox](https://codesandbox.io/s/infallible-feynman-bcdrh?file=/src/App.tsx)

```jsx
const customTheme = extendTheme({
  styles: {
    global: (props) => {
      // props look like { theme, colorMode }
      console.log({ props });
      console.log("props.colorMode", props.colorMode);

      return {
        body: {
          bg: (theme) => {

            // this is the chakra theme - not the computed props

            console.log({ theme });
            return props.colorMode === "dark"
              ? "red.300"
              : "yellow.300";
          }
        }
      };
    }
  }
});
```

I am closing this, because it is not a bug.

**Closed by TimKolberger** 2020-11-27 19:30 UTC

**Comment by maxcnunes** [comment] 2020-11-27 19:31
Right, I was just going to mention I got it working without nested props, thanks for the quick response anyway!
