### ISSUE TITLE
Support for React Server Component (RSC) in Next.js 14

### ISSUE THREAD

**Issue by slava-lu** [chakra-ui/chakra-ui#8216] opened 2024-01-15 15:39 UTC
### Description

At this page of Next.js documentation there is the statement that Chakra does not support React Server Components
https://chakra-ui.com/getting-started/nextjs-app-guide
`To use Chakra UI in server components, you need to convert them into client-side component`

But this kills the whole idea behind Next.js and the App router. 

### Problem Statement/Justification

React Server Components are the near future of React. Not having the support for RSC makes Chakra pretty much useless in React world. 

### Proposed Solution or API

Add support for RSC

**Comment by segunadebayo** [comment] 2024-01-16 00:21
This is a duplicate of #8094 

Again. Chakra works in Next 14 and can be rendered in server components

 We’ll update the docs shortly

**Closed by segunadebayo** 2024-01-16 00:21 UTC
Labels: needs triage

**Comment by tomdoeslinux** [comment] 2024-01-31 07:09
> This is a duplicate of #8094
> 
> Again. Chakra works in Next 14 and can be rendered in server components
> 
> We’ll update the docs shortly

Thanks for replying. The docs also seemed to confuse me as I got Chakra to work well in my NextJS app.

**Comment by DavidCodesDev** [comment] 2024-03-04 00:47
> This is a duplicate of #8094
> 
> Again. Chakra works in Next 14 and can be rendered in server components
> 
> We’ll update the docs shortly

I'm sorry bro but it absolutely does not work, I have spent the last 8 hours trying to fix the bugs of ChakraUI in Nextjs14 app router, it's all fixed if I use 'use client', but that defeats the entire purpose, useBreakPointValue is not recognized as a function anymore when it's serverside, then I got this error: Error: Could not find the module "/Users/X/Projects/Y/node_modules/@chakra-ui/system/dist/chunk-ZHQNHOQS.mjs#chakra#header" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
Another nonsense error:

`Failed to compile.

./node_modules/@chakra-ui/icons/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.
    at Object.transformSource (/Users/X/Projects/Y/node_modules/next/dist/build/webpack/loaders/next-flight-loader/index.js:52:31)

Import trace for requested module:
./node_modules/@chakra-ui/icons/dist/index.mjs
./src/app/page.tsx
`

But I didn't export *, it was a <StarIcon> direct named import
Not sure if this is chakraui specific, maybe a nextjs setting but I couldnt find any fix for it


I got many more errors but its on my other pc, currently sitting here frustrated trying to find an alternative to chakra-ui, I spent the last 4 years learning chakra-ui and I absolutely love it, but there are so many small annoying bugs when trying to make a bit more sophisticated projects

**Comment by casta42** [comment] 2024-04-03 22:39
any updates on this?

**Comment by DavidCodesDev** [comment] 2024-04-03 23:03
> any updates on this?
> 

It's coming this month with the Chakra-Ui v3 update

**Comment by GregerGu** [comment] 2024-04-08 11:51
> > any updates on this?
> 
> It's coming this month with the Chakra-Ui v3 update

Hi, do you have a link to this, I can't seem to find it.

**Comment by Mounajidev** [comment] 2024-05-12 23:55
i am starting a new project on nextjs 14, and just facing all this, what davindcodes just expressed what i was feel too. 
there is any update on this, i saw chakraui v3 ... but not in their page yet...

**Comment by bohdan-mykhailenko** [comment] 2024-05-14 20:01
Could anyone explain how Chakra works in Server Component? Before I used to think that it doesnt work at all, but suddenly I added Chakra components to my RSC and everything is working. Component is still server rendered, ui works well(even Menus, Popovers, etc). Is it expected behavior or it was updated recently?

 Everyone in forums say that u need to use Chakra/MUi etc for client compoennts(with user interaction) and talwind/panda/daisyui for server components. But what is the deal with that? How to check how css-in-js work or doesnt work in your RSC?

**Comment by casta42** [comment] 2024-05-17 23:23
> i am starting a new project on nextjs 14, and just facing all this, what davindcodes just expressed what i was feel too. there is any update on this, i saw chakraui v3 ... but not in their page yet...

I think V3 is going to drop around June-July? not sure, Segun made this post on March https://x.com/thesegunadebayo/status/1773403593086844939

According to this blog by Segun https://www.adebayosegun.com/blog/chakra-panda-ark-whats-the-plan 
"After this fix, all Chakra UI components will be compatible with React Server Components and SSR'd correctly "

Hope this helps, cant wait for v3 to drop!
