### ISSUE TITLE
Add Avatar responsive size

### ISSUE THREAD

**Issue by omribenari** [chakra-ui/chakra-ui#2105] opened 2020-09-27 21:34 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
Avatar component don't support responsive size.
size prop is a string.

## Describe the solution you'd like

something like this:
```
<Avatar name={name} src={photoUrl} size={["sm", "md", "lg", "xl"]} /> 
```
## Describe alternatives you've considered
i also tried 
```
<Avatar name={name} src={photoUrl} size={{ base: "sm", md: "md" }} /> 
```

**Comment by andrei-scripcaru** [comment] 2020-09-29 09:02
I second that.

**Comment by segunadebayo** [comment] 2020-10-29 10:04
Thanks for chiming in @andrei-scripcaru. 

This is also a duplicate of #1028.

**Closed by segunadebayo** 2020-10-29 10:04 UTC
Labels: workaround available ✌️

**Comment by JavaJamie** [comment] 2021-08-10 09:08
Thanks @andrei-scripcaru!

**Comment by marloscarmo** [comment] 2021-09-01 10:34
You can use this simple way!

```
import { useBreakpointValue } from '@chakra-ui/media-query'

<Avatar
  size={useBreakpointValue({
    base: 'sm',
    md: 'md',
  })}
  src="/images/avatar.png"
></Avatar>
```

**Comment by edwinvelez** [comment] 2022-01-13 02:01
If you are using [Next.js](https://nextjs.org/) I came up a solution. Hopefully, it will for you too. See [nextjs-avatar-component-with-chakra-ui](https://github.com/edwinvelez/nextjs-avatar-component-with-chakra-ui) for a working example.
