### ISSUE TITLE
applying baseStyle to Th does not work

### ISSUE THREAD

**Issue by AJFunk** [chakra-ui/chakra-ui#4024] opened 2021-05-17 17:02 UTC
# 🐛 Bug report

applying `baseStyle` to `th` in theme does not work

## 💥 Steps to reproduce

When extending the theme, apply a `baseStyle` to `th` and observe that it does not work:
```
const theme = extendTheme({
  components: {
    Table: {
      baseStyle: {
        th: {
          // does not work
          color: "red.500"
        },
        td: {
          // this works
          color: "red.500"
        }
      }
    }
  }
});
```

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/twilight-feather-nn6nz?file=/src/index.js:175-426

## 🧐 Expected behavior

Base styles should be applied

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.16.1       |
| Browser          |      Chrome 90.0.4430.93      |
| Operating System |      Mac 10.15.3       |

## 📝 Additional information

In my local copy of Chakra, I threw a `console.log` at the style object that is returned from the `useStyles` hook in the `th` component here https://github.com/chakra-ui/chakra-ui/blob/326813ea261ddb6c9f0106e7e63f49f51e111fa2/packages/table/src/table.tsx#L120
and found that `styles.th` only contains the default styles. Any styles that I add via `extendTheme` do not make it here

I've tested using various style attrs and nothing seems to work for `th`. Everything seems to work fine for other table components, so for some reason this seems to only affect `th`

**Comment by TimKolberger** [comment] 2021-05-17 18:05
The color for `th` is [set by the variant](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/table.ts#L42).

The styles for components are applied from baseStyle <-- variant <-- style props.

Closing this, because it is not a bug :)

**Closed by TimKolberger** 2021-05-17 18:05 UTC

**Comment by cl510804194** [comment] 2021-07-27 09:35
emmm., After reading it, I want to know how to modify the global th style...

**Comment by TimKolberger** [comment] 2021-07-27 09:44
Using global styles is documented here: https://chakra-ui.com/docs/features/global-styles
