### ISSUE TITLE
MenuItemProps include invalid props `"disabled" | "aria-disabled" | "type"`

### ISSUE THREAD

**Issue by Andarist** [chakra-ui/chakra-ui#4935] opened 2021-10-27 07:59 UTC
### Description

When I use many Chakra components with TS I can easily end up with my props being silently swallowed

### Link to Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgWQKYDsCuBJGqQAKUEYAznAL5wBmxIcA5AAIDGAFgIYDWUHAtJmAB6EBkwMAUKEixEcABIAVZABkAwpx4ciJclVoR6zdt14DhpAJ6k8ISRKFC4TGKT6oAHmFQsY7qMRQEjCW3nAAymwQmAA2ACYAogHQcAC8KGK4+DpkANoARHHApBwARjGocfkAusGhqHCKbMXYpGrQUD7w6WhYWYTEefnFACLFZRVVtQ5OLm6e3r7+gXAAFCAQNnAxwFyoMZYAlHVh4dFQLKgA8tRNqDrl+GkKyuqavDmkADz5pZgwMAg6HyAD4CkUSo8pkA

### Steps to reproduce

The given link is enough to showcase the problem.

### Chakra UI Version

latest

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by TimKolberger** [comment] 2021-11-08 14:45
The MenuItem component forwards all props to the DOM element `button`. This behaviour is the same for almost every chakra ui component. The type `HTMLChakraProps` exists exactly for this use case - "allow the combination of all DOM props and all chakra style props for this component".

All non-chakra-style-props (except additional component props) should end up in the DOM and should not be swallowed.

`MenuItemProps["disabled"]` and `HTMLChakraProps<"button">["disabled"]` are valid because they map to the [DOM attribute "disabled"](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled).

Let me know if I misunderstood the question. 
If this answers you question feel free to close this issue.

**Comment by Andarist** [comment] 2021-11-08 15:33
This is not the case though.

For such components:
```jsx
<MenuItem disabled>Download</MenuItem>
<MenuItem isDisabled>Create a Copy</MenuItem>
```
we get such HTML rendered:
```html
<button
  type="button"
  id="menu-list-4-menuitem-6"
  role="menuitem"
  tabindex="-1"
  class="chakra-menu__menuitem css-1rufx9q"
  data-index="0"
>
  Download</button
><button
  type="button"
  id="menu-list-4-menuitem-8"
  role="menuitem"
  tabindex="-1"
  class="chakra-menu__menuitem css-1rufx9q"
  data-index="1"
  disabled=""
>
  Create a Copy
</button>
```

We may notice here that the first menu item doesn't have `disabled` forwarded to it. The live demo can be found here: https://codesandbox.io/s/stoic-dan-biz7r?file=/src/App.js

However, even if this would be forwarded, I think this would be a foot gun for the user. Supporting both `isDisabled` and `disabled` is confusing and the user can get lost as to which one they should use. According to my understanding, the `isDisabled` is a "more correct" one to use here because it's Chakra-specific and thus Chakra understands how to implement some more fine-grained behaviors based on it.

**Comment by TimKolberger** [comment] 2021-11-08 17:34
Yes this is correct :+1: Some HTML attributes are overridden by the components. In case of `MenuItem` the `disabled` prop is managed by `useClickable`. That is the intended behaviour for the components, as you mentioned!

If I understand you correctly, we are talking about specific typings which are currently too wide?
E.g. the prop `disabled` is currently allowed by the `MenuItem` component, but will be swallowed because `useClickable` overrides this prop.

This behaviour may occur with many more components where the HTML attributes are managed by the component.

I don't see any issue with the type `HTMLChakraProps` itself.
So we need to identify which attributes are overridden by each component, and adjust the typings for them manually. Correct?

**Comment by TimKolberger** [comment] 2021-11-08 17:42
E.g. the MenuItemProps are currently defined like this:

https://github.com/chakra-ui/chakra-ui/blob/4453b2a03bda52f8059825da5f5701bc748cc8e9/packages/menu/src/menu.tsx#L255-L257

But correct would be 

```ts
type PropsOverridenByUseClickable = "disabled" | "aria-disabled" | "type"

export interface MenuItemProps
  extends Omit<HTMLChakraProps<"button">, PropsOverridenByUseClickable>,
    MenuItemOptions {}
```

**Comment by anubra266** [comment] 2021-11-09 12:45
@TimKolberger could you confirm an Issue here, or I can go ahead and close it.

**Comment by Andarist** [comment] 2021-11-09 16:31
> I don't see any issue with the type HTMLChakraProps itself.
So we need to identify which attributes are overridden by each component, and adjust the typings for them manually. Correct?

Yes, I've only pointed towards `HTMLChakraProps` as a suggestion for where this problem might originate. I don't know its exact purpose etc - if you believe there is no conceptual problem with it then yes, this should be fixed at a component level (like you have suggested in the latter post)

> @TimKolberger could you confirm an Issue here, or I can go ahead and close it.

I believe that Tim has already confirmed the problem, only in a slightly different place than I've originally suggested

**Closed** 2021-12-29 09:01 UTC
Labels: Type: Bug 🐛, Topic: TypeScript 🤠

**Comment by JClackett** [comment] 2022-01-26 18:55
Not sure if this is relevant to this issue, but I want to add a type of "submit" to the MenuItem component, but it keeps overriding it to be "button", I've added an as prop as button too but it doesn't change it.

Example:

```tsx
 <c.MenuItem as="button" type="submit">
```

**Comment by JClackett** [comment] 2022-01-26 18:59
I've tracked it down to the fact that the MenuItem, uses "useMenuItem" which uses "useClickable" and that sets type="button" which useMenuItem spreads and overrides any of the user added props. Basically impossible to get type="submit" on the MenuItem. Is this like this for reason?

**Comment by TimKolberger** [comment] 2022-01-26 19:05
@JClackett kindly create a new issue
