### ISSUE TITLE
v1.0.0-rc.7 - Toast doesn't close anymore

### ISSUE THREAD

**Issue by bulby97** [chakra-ui/chakra-ui#2331] opened 2020-10-26 12:13 UTC
# Bug report

## Describe the bug

When using toast with the `useToast` hook on rc.7, the toast cannot be closed.

Official Chakra CodeSandbox templates:
- [CodeSandbox](https://codesandbox.io/s/inspiring-euclid-wqwu7?file=/src/App.tsx)
-->

## System information
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.7]

**Comment by ljosberinn** [comment] 2020-10-26 12:16
duplicate of #2328, fixed in the next release

**Closed by ljosberinn** 2020-10-26 12:16 UTC
