### ISSUE TITLE
createStandaloneToast causes fonts to shift

### ISSUE THREAD

**Issue by prescottbreeden** [chakra-ui/chakra-ui#4076] opened 2021-05-23 20:04 UTC
# 🐛 Bug report
When calling toast with createStandaloneToast from inside redux middleware, fonts set in the the extendTheme option shift until the toast dissapears.

## 💥 Steps to reproduce

- change fonts with extendTheme
- call createStandaloneToast from inside some redux middleware
- font will shift away from the font set by theme until toast is closed

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/sad-joliot-khqpe?file=/src/index.tsx

## 🧐 Expected behavior
Styling doesn't change when calling toast from standalone

## 🧭 Possible Solution
No solution in mind, workaround for now is to create a reducer for notifications and select them in a notification component and call toast with useToast as redux state changes -- however, this is not ideal and it would be lovely if I could just use the standalone.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.6.2        |
| Browser          |    Firefox        |
| Operating System |      Linux      |

## 📝 Additional information
Love the library, y'all are crushing it, by far favorite boon to productivity banging out UIs for clients.

**Comment by nowshad-sust** [comment] 2021-05-27 13:31
I was facing the same problem, a lot of my styles were messed up once the toast pops up.
But the solution was an easier one, just passing the theme resolves the issue. 

`const toast = createStandaloneToast({ theme: defaultTheme });`

**Comment by la55u** [comment] 2021-05-27 13:38
@nowshad-sust and how do you obtain the theme outside a component? (in plain js)

**Comment by nowshad-sust** [comment] 2021-05-27 14:08
> @nowshad-sust and how do you obtain the theme outside a component? (in plain js)

For my use case, I could get the direct js custom theme object and import it directly. I think chakra's default theme can also be imported directly as it's exported as a js object - https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/index.ts

**Comment by with-heart** [comment] 2021-05-29 14:54
I know this was created first, but I'm going to close this as a duplicate of #4112 as we have more details in that issue.

**Closed by with-heart** 2021-05-29 14:54 UTC
