### ISSUE TITLE
Better integration of React Hook Form on NumberInput

### ISSUE THREAD

**Issue by jcognard-actinvision** [chakra-ui/chakra-ui#3194] opened 2021-01-28 13:12 UTC
# 🚀 Feature request

Being able to use React Hook Form’s `register` on NumberInput.

## 🧱 Problem Statement / Justification

Currently, the only way to integrate React Hook Form with `NumberInput` is to use a controller to pass the ref to `NumberInputField` and the props (value, onChange, onBlur) to `NumberInput`.

See this [Codesandbox example](https://codesandbox.io/s/chakra-ui-react-hook-form-forked-nly2i?file=/src/HookForm.js:312-388)

## ✅ Proposed solution or API

It would be simpler to support `ref={register}` on `NumberInput`.

**Comment by TimKolberger** [comment] 2021-01-31 10:01
The component `NumberInput` controls the state of the `NumberInputField` to be able to change the value with the stepper buttons. 

Kindly follow the [react-hook-form docs on integrating it with component libraries](https://react-hook-form.com/get-started#IntegratingwithUIlibraries)

Closing this as duplicate of #3131

**Closed by TimKolberger** 2021-01-31 10:01 UTC
