### ISSUE TITLE
Box shadows for button components do not appear in Safari

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#2663] opened 2020-11-29 17:04 UTC
# Bug report

## Describe the bug

When using Safari, it appears box shadows for button components do not appear 

## To reproduce

1. Open the provided codesandbox demo below via Safari
2. Click on the button component

## Minimal reproduction

https://codesandbox.io/s/exciting-wood-v8mm8?file=/src/App.tsx

## Expected behavior

- I would expect the button box shadow to appear when viewing via Safari

## System information

- OS: macOS, Big Sur (11.0.1)
- Browser: Safari
- Version of @chakra-ui/react: 1.0.1

**Comment by with-heart** [comment] 2020-11-29 17:57
Hi @brennanfife! This is "working as intended" for Safari. It does not register clicks on buttons, checkboxes, and radios as focusing the element. https://zellwk.com/blog/inconsistent-button-behavior/

We could force it to using workarounds, but I don't think we want to override default browser behavior like that, especially since Safari is _probably_ doing the correct thing here in not showing focus outlines on click as there's a debate around whether focus outline on click is useful/necessary. It still correctly shows the outline when navigating via <kbd>TAB</kbd>.

I'm going to close this as I don't consider it a bug that should be addressed, but I'm open to further discussion if you feel like it's necessary 😄

**Closed by with-heart** 2020-11-29 17:57 UTC

**Comment by brennanfife** [comment] 2020-11-29 22:10
Oh, I actually did not know this about Safari. Definitely agree with you here on keeping the browser specific behavior. Thanks.
