### ISSUE TITLE
Non-unique id when using  RadioGroup or useRadio hook inside a FormControl

### ISSUE THREAD

**Issue by simontaisne** [chakra-ui/chakra-ui#3074] opened 2021-01-16 23:21 UTC
# 🐛 Bug report

When using the `useRadio` hook to create custom radio components  or `RadioGroup`/`Radio` components inside a `FormControl`, the generated `input` `id`s are non-unique.

## 💻 Link to reproduction

https://codesandbox.io/s/affectionate-bogdan-1v1pf?file=/src/App.js

## 🧐 Expected behavior

The generated `id`s should be unique.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.1.4  |
| Browser          | Chrome 87  |
| Operating System | macOS 11.1 |

## 📝 Additional information

<img width="767" alt="Screen Shot 2021-01-16 at 6 20 24 PM" src="https://user-images.githubusercontent.com/233639/104827010-84ce1800-5827-11eb-8fc2-8a81635bfd9c.png">

**Comment by tomdohnal** [comment] 2021-01-20 21:55
This seems to be caused by the fact that ChakraUI generates a unique ID per each `FormControl` and if a single `FormControl` renders several different radio button inputs it passes the same `id` prop onto them.

I looked at the implementation of `CheckboxGroup` and `Checkbox` and they don't seem to be using `useFormControl` hook at all thus *not* resulting in passing non-unique ids onto the checkbox inputs... 

I'd be happy to help with this issue but I first need to understand why you use the `useFormControl` hook in some form elements (such as radio input) and not in other ones (e. g. checkbox input)

**Comment by m4tta** [comment] 2021-02-06 09:39
> first need to understand why you use the useFormControl hook in some form elements (such as radio input) and not in other ones (e. g. checkbox input)

That is the example code for creating custom radio buttons provided in the docs... https://chakra-ui.com/docs/form/radio

Seems the `RadioGroup` component should override any `id` setting that FormControl does or prefix it with another value to make unique.

**Comment by broeker** [comment] 2021-03-05 20:50
I'm also facing this issue when trying to place a dynamic `RadioGroup` inside of a` FormControl`:

```
<RadioGroup key={resetKey} value={value || ""} onChange={handleChange} >
        <Stack
          direction={forceStack ? ["column"] : ["column", "column", "row"]}
          spacing={forceStack ? [".2rem"] : ["0"]}
        >
          {(options || []).map(item => (
            <Radio
              mr={4}
              size="lg"
              colorScheme="brand"
              key={item.value}
              value={item.value}
            >
              {item.label}
            </Radio>
          ))}
        </Stack>
      </RadioGroup>
```

When that code is placed inside of a `FormControl`, it generates a single ID for each of the inputs, resulting in non-unique id warnings in console:

```
<input class="chakra-radio__input" **id="field-815"** required="" aria-required="true" type="radio" name="radio-516"...>
<input class="chakra-radio__input" **id="field-815"** required="" aria-required="true" type="radio" name="radio-516"...>
<input class="chakra-radio__input" **id="field-815"** required="" aria-required="true" type="radio" name="radio-516"...>
```

If I remove the `FormControl`, then no id is generated at all for the inputs, and the warnings go away. Here is the output of same three inputs with no `FormControl`:

```
<input class="chakra-radio__input" type="radio" name="radio-2" value="both"...>
<input class="chakra-radio__input" type="radio" name="radio-2" value="worksheets...">
<input class="chakra-radio__input" type="radio" name="radio-2" value="affadavit"...>
```
For what it's worth per the above question I have my entire app wrapped in a FormControl, not just some fields. 

Also, the problem was not present in pre 1.0 releases -- I only started seeing this post-upgrade (I'm now running the latest 1.3). 

Thanks for any help!

**Comment by andrewcs0901** [comment] 2021-04-05 01:41
Realizar os seguintes ajustes:
- Adicionar campo obrigatório (isRequired) no cadastro manual de usuário;
- No cadastro de usuário manual, não deixar cadastrar se o formulário estiver vazio;
- No dialogo de confirmação de exclusão definir o tamanho máximo e adicionar "..." se for muito grande - Ex.: igual foi usado na tabela de usuários que está truncando o nome.

**Comment by segunadebayo** [comment] 2021-05-17 00:35
Hi @tomdohnal,

I'd say we skipped that detail when designing the checkbox component. Feel free to send in PR if you'd like to tackle that.

@simontaisne I've pushed a fix for this issue with the radio. It'll be published shortly.

**Closed by segunadebayo** 2021-05-17 00:35 UTC
Labels: Type: Bug 🐛
