### ISSUE TITLE
Side navigation using the Drawer component

### ISSUE THREAD

**Issue by sorxrob** [chakra-ui/chakra-ui#2021] opened 2020-09-12 12:35 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I recently discovered Chakra UI and I love it functionality-wise. I want to use the `Drawer` component as a sidebar nav to make it easier to compose dashboard layouts with Chakra.

## Describe the solution you'd like

Maybe adding a `fixed` prop will make the `Drawer` fixed? 

## Additional context

Here's a sample of what I'm trying to achieve https://vuetifyjs.com/en/examples/layouts/complex/.

**Comment by with-heart** [comment] 2020-09-13 14:52
Hi @sorxrob! Closing this as a duplicate of #608!

**Closed by with-heart** 2020-09-13 14:52 UTC
Labels: Type: Duplicate 😒
