### ISSUE TITLE
Tooltip openDelay not autoclosing upon first render

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#3951] opened 2021-05-03 21:55 UTC
# 🐛 Bug report

The `Tooltip` `openDelay` prop is breaking the tooltip. **Upon the first render** (this is extremelly important, since this bug only happens on the first hover upon the first render of the component), if you hover the target component quickly (hover and immediatly, without waiting for the Tooltip to appear, leaves that component) the Tooltip opens and remains open forever.

Some things that I've noted:

1 - **IMPORTANT:** Don't discart this bug quickly. It is really intermitent (since it only happens upon the first hover after the component render). If you were not able to replicate this issue, please let me know
2 - I've noticed that it started happened after I upgrade to v1.6.0 (I was on 1.3.3)
3 - It only happens right when your component was rendered. If you hover anything else besides that componen, for some reason, it won't happen

## 💥 Steps to reproduce

The steps below is the best way that I was able to achive a minimum viable reproducion of the bug:

1. Open the [More Examples section in the Chakra's Tooltip page](https://chakra-ui.com/docs/overlay/tooltip#more-examples)
2. **Without hovering any button** edit the code of the "Delay Open - 500ms" tooltip to `openDelay={2000}` (the longer, the easier to reproduce)
3. Now, hover that button in the preview section (right above) and immediatly removes your mouse from the button **and don't hover anything else**
4. After 2 seconds, the Tooltip will open and remain that way
5. Now, hover the button again, and remove your mouse from the button. The Tooltip will disapear
6. Now, hover and remove the mouse again (to try the bug). You will see that it doesn't happen anymore

It is extremelly annoying. In my app I have a dozen Tooltips in a given page, if the user pass all the targets without waiting it opens **all the 12 tooltips**.

## 💻 Link to reproduction

https://chakra-ui.com/docs/overlay/tooltip#more-examples

## 🧐 Expected behavior

Even upon first render, The Tooltips should appear and hide.

## 📝 Additional information

Please, fix this issue. It is almost mandatory for our app and I invested at least 3 hours exploring this bug to find a way to reproduce it :)

Thanks :D

**Comment by segunadebayo** [comment] 2021-05-03 22:14
This is a duplicate of #3659.

We'll look into this as soon as we can.

**Closed by segunadebayo** 2021-05-03 22:14 UTC

**Comment by delucca** [comment] 2021-05-03 22:17
Thanks @segunadebayo 

I missed that issue while searching
