### ISSUE TITLE
Typescript error when assigning a responsive style to "size" attribute of "Heading" component but works fine with "display" attribute of adjacent "Text" component

### ISSUE THREAD

**Issue by jakegiri** [chakra-ui/chakra-ui#5187] opened 2021-12-02 17:23 UTC
### Description

When  I provide responsive style to "size" attribute of

### Link to Reproduction

https://github.com/jakegiri/chakraTypescriptError.git

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.7.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/24270559/144469915-eb95aa39-6c05-47b3-bfa4-4034b1303f9b.png)

![image](https://user-images.githubusercontent.com/24270559/144469300-eb5fbc33-9eb5-4845-9541-68c6af04a419.png)

**Comment by segunadebayo** [comment] 2021-12-02 18:22
Hi @jakegiri,

Responsive size and variants aren't supported at the moment. It's an upcoming feature we're looking to add.

See #2105 

Closing this because it's a duplicate of past issues.

**Closed by segunadebayo** 2021-12-02 18:22 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by jakegiri** [comment] 2021-12-02 18:39
@segunadebayo Thanks for clearing the confusion. Btw how would I know when this feature is implemented? Sorry if this is a lame question

**Comment by yonycalsin** [comment] 2022-04-02 02:43
@segunadebayo  Is there any update on the implementation to fix this problem ?
