### ISSUE TITLE
BUG: Using _odd does not work like CSS nth-child(odd)

### ISSUE THREAD

**Issue by ogzhanolguncu** [chakra-ui/chakra-ui#3041] opened 2021-01-13 11:30 UTC
# 🐛 Bug report

> When I used `_odd` and instead of `nth-child(odd)` CSS selector, I've seen unexpected behaviours in the UI.

## 💥 Steps to reproduce

1. Go to http://github.com/ogzhanolguncu/ogzhanolguncu.com/blob/master/components/TimeLineItem.tsx and clone this repo
2. Find line number 22 and try adding `_odd={{
            left: "auto",
  right:"5px"
          }}`
By adding `_odd`, you will override existing CSS and break the solution.

## 🧐 Expected behaviour

> _odd does not behave like an `nth-child(odd)`

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |          v1 |
| Browser          |           Chrome|
| Operating System |    Windows|

## 📝 Additional information

When CSS is used that's the outcome:

![withcss](https://user-images.githubusercontent.com/21091016/104446546-ac18b100-55ab-11eb-9a5e-ae3a95742f5a.PNG)

With _odd

![withodd](https://user-images.githubusercontent.com/21091016/104446563-b33fbf00-55ab-11eb-9c57-60228b3d7da8.PNG)

**Comment by tomdohnal** [comment] 2021-01-20 21:19
If you search for the `_odd` selector in the docs (https://chakra-ui.com/docs/features/style-props), you'll see that `_odd` doesn't stand for `nth-child(odd)` but rather `&:nth-of-type(odd)`

**Comment by TimKolberger** [comment] 2021-01-24 12:19
Because the CSS selectors `:nth-child`, `:first-child` or `:last-child` are not SSR safe, we use the `:nth-of-type` selector.

Closing this, because it is not a bug.

**Closed by TimKolberger** 2021-01-24 12:19 UTC

**Comment by nihalanisumit** [comment] 2021-02-08 15:25
@TimKolberger @ogzhanolguncu how can I use nth-child(odd) or nth-child(even) in chakra?
Because I tried creating a custom class right-side-bar but it still isn't working. What do you mean by it's not SSR safe?
```
.right-side-bar:nth-child(odd) {
    background: #eee;
  }

  .right-side-bar:nth-child(even) {
    background: #e9e9e9;
  }
```

**Comment by nihalanisumit** [comment] 2021-02-08 16:15
okay now applying the nth-of-type selector to all the children of the right-side-bar and this seems to be working for me. This is for anyone struggling to find a css solution.

<Box className="right-side-bar" .... > ...... </Box>
```
.right-side-bar > *:nth-of-type(odd) {
    background: #f6f6f6;
  }

  .right-side-bar > *:nth-of-type(even) {
    background: #e9e9e9;
  }
```

**Comment by with-heart** [comment] 2021-02-08 16:38
I don't have an answer to your question about SSR unfortunately, but I wanted to thank you for following up with a solution @nihalanisumit. Much appreciated that you'd think of others that might come later with a similar problem.
