### ISSUE TITLE
PopoverArrow always has box shadow blur, even when border is solid.

### ISSUE THREAD

**Issue by Tenkir** [chakra-ui/chakra-ui#5934] opened 2022-04-27 14:35 UTC
### Description

When I have a PopoverArrow, I expect the arrow to have the same border as the Popover. Instead it has a 1px blur.

### Link to Reproduction

https://codesandbox.io/s/chakra-popover-bug-v2-4rr1i1

### Steps to reproduce

1. Go to reproduction
2. Click on button labeled `Click`
4. Observe PopoverArrow has a blurred box shadow.

### Chakra UI Version

2.2.4

### Browser

Firefox, Chrome, Safari

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

The style which adds this box shadow is an inline style, so it's not able to be overridden with a `boxShadow` property on the `PopoverArrow` component.

### Screenshot
![Screen Shot 2022-04-27 at 10 34 41 AM](https://user-images.githubusercontent.com/3649828/165543153-3cf8f3c1-d232-4383-840f-65d1534c6151.png)

**Comment by YosefBlandin** [comment] 2022-06-14 02:20
I can't reproduce the issue
![1](https://user-images.githubusercontent.com/65220054/173479670-eab6c52f-98f9-43f0-a250-54071fe055c0.png)

**Comment by Tenkir** [comment] 2022-08-01 13:48
> I can't reproduce the issue ![1](https://user-images.githubusercontent.com/65220054/173479670-eab6c52f-98f9-43f0-a250-54071fe055c0.png)

Looks like an update to codesandbox had broken the reproduction. Updated one is attached, and I have updated the original issue link:

https://codesandbox.io/s/chakra-popover-bug-v2-4rr1i1

**Comment by robcrock** [comment] 2023-04-15 19:02
If this is resolved can the issue be closed?

**Comment by segunadebayo** [comment] 2023-05-02 16:29
This has already been fixed in one of the recent commits. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.

**Closed as completed by segunadebayo** 2023-05-02 16:29 UTC
Labels: Type: Bug 🐛, Component: Popover

**Comment by Tenkir** [comment] 2023-11-14 15:01
@segunadebayo This is fixed in so far as it is no longer blurry, but it is still not correct. The borders protrude out the bottom of the border. My fix in #6412 addressed this.

![image](https://github.com/chakra-ui/chakra-ui/assets/3649828/7395917f-1dd1-4ae9-baf5-c1fcfaa70129)
