### ISSUE TITLE
Slider doesn't work on iOS

### ISSUE THREAD

**Issue by luisrudge** [chakra-ui/chakra-ui#8] opened 2019-09-05 02:16 UTC
I can't change the value when using iOS

**Comment by aghassemi** [comment] 2019-09-05 03:33
Same with Chrome on Android

**Comment by cyan33** [comment] 2019-09-05 05:56
Confirmed that this is can be reproduced on the chrome dev tool in mobile. 

I can take a look if no one hasn't worked on it. :)

**Comment by devanshj** [comment] 2019-09-05 12:53
Can you folks test if the issue is fixed by PR #18 on [this storybook](http://chakra-ui-pr-18.surge.sh/?path=/story/slider--default) which contains the PR

**Comment by luisrudge** [comment] 2019-09-05 12:55
Fixed it for me

**Comment by segunadebayo** [comment] 2019-09-05 14:50
Thanks for looking into this @devanshj

**Closed** 2019-09-05 14:51 UTC

**Comment by devanshj** [comment] 2019-09-05 15:57
@segunadebayo You're welcome!
