### ISSUE TITLE
ModalOverlayProps typescript error

### ISSUE THREAD

**Issue by ockam** [chakra-ui/chakra-ui#2955] opened 2021-01-05 18:25 UTC
# 🐛 Bug report

> `ModalOverlayProps` interface throws an error with Typescript 4.1.3

```
TS2320: Interface 'ModalOverlayProps' cannot simultaneously extend types 'Pick<HTMLMotionProps<"div">, "slot" | "style" | "title" | "animate" | "children" | "inherit" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 286 more ... | "onViewportBoxUpdate">' and 'Pick<ChakraProps, "p" | "filter" | "color" | "css" | "m" | "margin" | "mt" | "marginBlockStart" | "marginTop" | "mr" | "marginInlineEnd" | "marginEnd" | "me" | "marginRight" | ... 306 more ... | "sx">'.
  Named property 'css' of types 'Pick<HTMLMotionProps<"div">, "slot" | "style" | "title" | "animate" | "children" | "inherit" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 286 more ... | "onViewportBoxUpdate">' and 'Pick<ChakraProps, "p" | "filter" | "color" | "css" | "m" | "margin" | "mt" | "marginBlockStart" | "marginTop" | "mr" | "marginInlineEnd" | "marginEnd" | "me" | "marginRight" | ... 306 more ... | "sx">' are not identical.
```

## 🧭 Possible Solution

Adding `css` in the Omit arguments solves the issue for me, but I’m not sure if it’s the appropriate way to solve this problem or if it has unintended side-effects.
```
export interface ModalOverlayProps extends Omit<HTMLMotionProps<"div">, "color" | "css">, Omit<ChakraProps, "transition"> {
    children?: React.ReactNode;
}
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI           | 1.1.1  |
| Typescript          |  4.1.3  |

**Comment by ockam** [comment] 2021-01-07 15:52
Problem still exist in Chakra 1.1.2. Again, adding `css` to the Omit arguments solves the issue.

**Comment by imkrish** [comment] 2021-01-25 21:33
The problem still exists in Chakra 1.1.6.

I have to set skipLibCheck in tsconfig.json to true to get it compiled.

Would be good if we have this fix :)

**Comment by cloud-walker** [comment] 2021-02-18 10:32
Problem is still here in v1.3.3

I'm a ts beginner and not sure how to use the workaround (I don't use ModalOverlayProps directly)

**Comment by ockam** [comment] 2021-02-18 12:46
@cloud-walker: use @imkrish suggestions and simply add `skipLibCheck: true` in `tsconfig.json`.

A bit less type safe, but as a TS beginner, it will make your life easier, since the issue is not directly related to your own code.

**Comment by cloud-walker** [comment] 2021-02-18 16:39
> @cloud-walker: use @imkrish suggestions and simply add `skipLibCheck: true` in `tsconfig.json`.
> 
> A bit less type safe, but as a TS beginner, it will make your life easier, since the issue is not directly related to your own code.

Yeah, I'm currently using `skipLibCheck: true`... but I'm feeling dirty about it 😭

**Comment by adam-thomas-privitar** [comment] 2021-03-11 18:03
Also seeing this on latest TS 4.2.3.

**Comment by segunadebayo** [comment] 2021-03-29 09:54
I can't seem to reproduce this error in my personal projects and Codesandbox with the latest version of Chakra.

Can anyone else confirm this?

**Comment by ockam** [comment] 2021-03-29 11:55
@segunadebayo tested with Chakra 1.4.1 and I still have the error.

More context:
- in tsconfig: `"skipLibCheck": false,`
- Snowpack 3.1.2, with @snowpack/plugin-typescript (error occur when running `snowpack dev`)

**Comment by Cretezy** [comment] 2021-05-22 21:19
Chakra 1.6.2 and also still getting this error.

**Comment by anubra266** [comment] 2021-05-28 17:30
Anybody still getting this error.

**Comment by with-heart** [comment] 2021-05-29 05:03
Could someone please provide a CodeSandbox reproduction?

**Comment by anubra266** [comment] 2021-05-29 05:08
@Cretezy Can you reproduce this in ccodesandbox?

**Comment by with-heart** [comment] 2021-05-29 13:35
Oh, it's not possible to provide a CodeSandbox because latest `typescript` version a CSB can use in the workspace is `4.1.2` 🙃

**Comment by adam-thomas-privitar** [comment] 2021-07-03 01:10
Just a note this went away for me, probably fixed in current version. So hopefully its closeable. Wont close it now in case others are still seeing it.

**Closed** 2021-09-09 12:07 UTC
Labels: Topic: TypeScript 🤠, workaround available ✌️
