### ISSUE TITLE
Controlled Number input & Slider are ignoring `value` prop when it changes

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/chakra-ui#3115] opened 2021-01-21 22:59 UTC
# 🐛 Bug report

Due to the context that is used in both NumberInput & slider, controlled value prop is not working any more. or the component does not change when the state is changed by another event.

last time this was working in Beta version.

Edit 1:

Providing an initial state will make them work perfectly
The problem is: in any form library the initial value would be undefined

## 💥 Steps to reproduce

Check codesandbox

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-ui-react-hook-form-slider-number-input-forked-6k63x?file=/src/App.tsx

**Comment by TimKolberger** [comment] 2021-01-24 12:12
If `value` is undefined at first render, we assume, that the component is uncontrolled. This mirrors the behaviour of the default HTML input component. React will show this warning when switching from an undefined value to a defined one:

> Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.

If you want to force a controlled input, you could pass a default value if your state value is undefined: `value={stateValue || ''}`
A better solution would be to define a default state in your form library, e.g. [Formik initialValues](https://formik.org/docs/api/formik#initialvalues-values) or for [react-hook-form `defaultValues`](https://react-hook-form.com/api/) 

Closing this, because it is not a bug.

**Closed by TimKolberger** 2021-01-24 12:12 UTC

**Comment by omarkhatibco** [comment] 2021-01-25 21:24
HI @timkindberg 

Thanks for your help, however after updating to the latest version. it works again.
