### ISSUE TITLE
[SSR] Color mode flash

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1878] opened 2020-08-30 19:34 UTC
It looks like the changes we made to fix color mode in `1.0.0-rc.3` worked for static generation, but also broke SSR. 

See https://personal-react-boilerplate.now.sh/ for an example.

**Comment by ljosberinn** [comment] 2020-08-31 08:12
did they work for static generation? https://next.chakra-ui.com/ suffers from the same issue

**Comment by ljosberinn** [comment] 2020-08-31 10:56
fyi: the current plan is to revert the `ColorModeScript` implementation back to use `storageManager` and to live with a flash of initial color mode on SSG/static sites. The overhead for `getServerSideProps` should be minimal as it only directly forwards `ctx.req.headers.cookies`.

The issue is generally unsolved except when using CSS variables and in regards to v1 release, we think it's not crucial to support this right away.

The required changes appear huge for a relatively small tradeoff, considering how many other sites live with the same issues (e.g. material-ui docs).

The solution which we currently would expect to work involves declares all possible colors as css variables on `body` via a `ColorModeScript` based on `localStorage`. Every design token and API would need to stay intact to prevent breaking changes, while the underlying implementation refer to css variables. This is e.g. [how docosaurus does it](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-classic/src/index.js#L23).

**Comment by matteofrana** [comment] 2020-09-18 15:43
I think the problem I have is related to this issue (v 1.0 rc3): color mode isn't initialized from localStorage and, from light color mode, I have to toggle mode 2 times to get dark color mode.

See minimal example:
https://codesandbox.io/s/nice-hamilton-71ht5?file=/src/App.js

Will PR #1939 solve this issue?

Thank you,
Matteo

**Comment by ljosberinn** [comment] 2020-09-18 15:49
As far as its possible, yes. SSR apps will have to pass the cookies to `cookieStorageManager(cookies)`, while CSR apps will have to live with a flash of the other color mode for the time being.

**Comment by matteofrana** [comment] 2020-09-19 13:58
Thank you @ljosberinn.
As you can see from the sandbox, it's not just a flash. It doesn't get the color mode from localStorage and, what's even worse, if you click to toggle to dark mode, it doesn't work, but you have to click a second time.

**Comment by ljosberinn** [comment] 2020-09-19 14:32
Yes, we are aware and this has been fixed in said branch :) fwiw you're technically missing the `ColorModeScript` in `rc.3` but that wouldn't help here anyways.
`rc.3` includes an experiment where we tried to eliminiate the flash for all cases, needless to say it sadly didn't work out, although it ironically worked fine in dev.

**Comment by matteofrana** [comment] 2020-09-20 17:10
Thank you! I think chakra is often used for dashboards where SSR is overkill and this problem makes color mode unusable at the moment. Thank you for your work.

**Closed** 2020-09-24 08:32 UTC
Labels: Topic: Color Mode 🌓, Type: Bug 🐛

**Comment by dannyvaughton** [comment] 2020-11-10 10:16
> The required changes appear huge for a relatively small tradeoff, considering how many other sites live with the same issues (e.g. material-ui docs).

I believe the transition to CSS variables is an important one and is not a relatively small tradeoff.

I know this may sound completely pedantic and illogical, however, for me, I can't stand the flash and imperfection of it.

It's probably just me, but it's the reason I can't use this lib at the moment. Don't get me wrong, I love everything about this component library. Aesthetically it's definitely my favourite but I am using Bumbag at the moment for this reason.

**Comment by trevorblades** [comment] 2020-11-13 21:27
I was able to accomplish a non-flashing color mode implementation with Chakra using CSS variables using a method like the one in @joshwcomeau's [article on the subject](https://joshwcomeau.com/gatsby/dark-mode/). I defined a bunch of CSS variables based on theme colors in a pre-body script, and changed my Chakra theme to use those variables instead of theme keys.

[Here's a gist](https://gist.github.com/trevorblades/1bd240c58ad4790fd6c11006e77ab9db) with the relevant parts. I've added a few comments in there explaining some of the things I do. I poked around Bumbag and noticed they were using color variables in a similar way, from what I could tell.

I can help build this feature if the Chakra team approves of this technique, and it doesn't negatively affect other uses of the library. It seems pretty straightforward (define CSS variables and use those in the default theme), but I could be missing something. Happy to discuss! 🙂

**Comment by trevorblades** [comment] 2021-01-29 01:18
Update: I turned the technique above into an NPM library to make it simple to implement. You can read more about that effort [over here](https://github.com/trevorblades/chakra-ui-flashless).

```jsx
import {FlashlessScript, flashless} from 'chakra-ui-flashless';
import {extendTheme} from '@chakra-ui/react';

// 1. extend your theme with `flashless` function
const theme = extendTheme(flashless({...overrides}));

// 2. insert a script tag at the top of your HTML `<body>`
<FlashlessScript theme={theme} />
```

**Comment by with-heart** [comment] 2021-01-29 16:40
@trevorblades Love the gif in the README! And the lib of course ❤️ 

I know that @segunadebayo has talked about wanting to take an approach like that in the future. I believe it'd require a decent amount of change in our internal systems, so it's probably a little far off.

**Comment by Mahavatar5D** [comment] 2021-01-30 05:02
I solved using **ColorModeProvider** component.

Look: [ColorModeProvider native componet](https://github.com/Mahavatar5D/next-chakra-app/blob/main/pages/_app.tsx)

**Comment by trevorblades** [comment] 2021-01-30 21:32
@Mahavatar5D I notice you have the initial value set to `dark` here, so I would expect it to prevent a flash from light to dark mode. However, I would imagine that if you loaded this website with your system set to light mode, you would experience a flash going from dark (initial value) to light (system value detected after JS loads).

**Comment by Mahavatar5D** [comment] 2021-01-30 23:52
@trevorblades, the expression **"value='dark'"** seems redundant, you can disregard it. Use the "options" parameter and change the **"initialColorMode"** property from **"dark"** to **"light"**, and vice versa. I did it and it worked.

You can see it in: [ColorModeProvider native componet](https://github.com/Mahavatar5D/next-chakra-app/blob/main/pages/_app.tsx) and [Theme config](https://github.com/Mahavatar5D/next-chakra-app/blob/main/shared/theme.ts)

**Comment by nickroberts** [comment] 2021-03-23 13:09
FWIW, [next-themes](https://github.com/pacocoursey/next-themes) has the ability to load a light / dark theme from local storage, without the flashing.

I'm not sure if we could leverage that package, or perhaps look at how it works, and implement it.

I think the themes are defined using css variables, however, they have an example on how to use tailwind, as well. I haven't looked too deep into it, so maybe it's not possible with chakra 9because of the css variables), but it's a thought.

@trevorblades your solution works great, plus css variables awesome! However, I wouldn't be able to use it until a way to handle user-defined theme selection. If I get some time, perhaps I can take a look to see if it can be implemented in your package.

@Mahavatar5D your solution still flashes if the default mode is different from the user-selected mode.

I'm still new to using chakra (and emotion, I've always used styled-components), so forgive me if I don't know a ton about chakra, yet!

**Comment by mikeytown19** [comment] 2021-08-23 03:45
@nickroberts I can't seem to implement it correctly either. Hopefully, a fix is implemented soon.

**Comment by SemperFortis** [comment] 2021-09-19 15:31
@nickroberts @mikeytown19 It is possible but my solution may seem verbose. How I solved it was by using next-themes with chakra, creating a mapping to each other but next-themes will take precedence over Chakra on the initial load, which prevents flashing. Toggling between themes after works as expected.

**Comment by kozlovvski** [comment] 2021-11-14 21:33
I also managed to create a working solution using `next-themes` in a way that @SemperFortis described. For anyone struggling, please check out [my solution in next-themes issue](https://github.com/pacocoursey/next-themes/issues/59#issuecomment-968366980)

It should work with these versions:
`next@12.0.2`
`next-themes@^0.0.15`
`@chakra-ui/react@^1.7.1`

**Comment by jeromevvb** [comment] 2023-07-06 09:28
For anyone looking to solve this issue with Chakra `2.7.1` and next app directory `13.4.8`
We need to get the cookie stored by Chakra and set manually the body classname and html data-theme.

Here's my code for RootLayout (the first layout.tsx within your app directory)

```javascript


import ThemeProvider from '@/chakra/ThemeProvider'
import { cookies } from 'next/headers'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies()
  const defaultTheme = 'dark';
  const uiColorMode =
    (cookieStore.get('chakra-ui-color-mode')?.value as 'light' | 'dark') || defaultTheme

  return (
    <html
      lang='en'
      data-theme={uiColorMode}
      style={{ colorScheme: uiColorMode }}
    >
      <head />
      <body className={`chakra-ui-${uiColorMode}`}>
        <ThemeProvider colorMode={uiColorMode}>{children}</ThemeProvider>
      </body>
    </html>
  )
}

```

And here's my ThemeProvider, make sure the `ChakraProvider` uses `cookieStorageManager`



```javascript

'use client'

import {
  ChakraProvider,
  StyleFunctionProps,
  extendTheme,
} from '@chakra-ui/react'
import { mode } from '@chakra-ui/theme-tools'
import { cookieStorageManager } from './components'

export default function ThemeProvider({
  children,
  colorMode,
}: {
  children: React.ReactNode
  colorMode: 'light' | 'dark'
}) {
  const theme = extendTheme({
    config: {
      initialColorMode: colorMode,
      useSystemColorMode: false,
    },
    styles: {
      global: (props: StyleFunctionProps) => ({
        body: {
          bg: mode('#fff', '#000')(props),
        },
      }),
    }
  })

  return (
    <>
      <ChakraProvider colorModeManager={cookieStorageManager} theme={theme}>
        {children}
      </ChakraProvider>
    </>
  )
}

```


I hope this can helps :)

**Comment by leonmjuancarlos** [comment] 2024-01-17 22:43
@jeromevvb You're amazing. This worked for me 👏

**Comment by khelkun** [comment] 2024-04-19 17:49
seems it's `import { cookieStorageManager } from @chakra-ui/react'` instead of `import { cookieStorageManager } from './components'` in your code snippet @jeromevvb
