### ISSUE TITLE
[Request] Add some quick-start templates in the website

### ISSUE THREAD

**Issue by aditya-mitra** [chakra-ui/chakra-ui#3087] opened 2021-01-18 12:47 UTC
# 🚀 Feature request

> Please describe your request in one or two sentences.

Can there be some full page templates in the chakra-ui website?

Somewhat like what (material-ui has](https://material-ui.com/getting-started/templates/)?

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feaure is related to a problem you've noticed. Mention it as well

ChakraUI is very good for building great sites. It would nice if there could be some **official templates for a ⚡ quickstart.**

[Material-UI](https://material-ui.com/getting-started/templates/) and [Tailwind CSS](http://google.com/search?q=tailwind+css+templates) have some good templates. 

Anybody who is using chakra-ui for the first time would find it best to start from a template. :smile: 

I understand there are starters like for *nextjs* and *gatsbyjs* but they are more like a **setup** and not a template.

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

Add some templates for a quickstart in the main website.

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

**Comment by TimKolberger** [comment] 2021-01-18 20:00
Closing this as duplicate of #1281

**Closed by TimKolberger** 2021-01-18 20:00 UTC
