### ISSUE TITLE
TabIndicator is not aware of tab size changes 

### ISSUE THREAD

**Issue by dglav** [chakra-ui/chakra-ui#8300] opened 2024-02-19 07:31 UTC
### Description

When I an event caused the Tab component to increase its width, the associated TabIndicator width didn't change.

### Link to Reproduction

[Codesandbox](https://codesandbox.io/p/devbox/dreamy-franklin-6cvhxt-forked-76hwdg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsslp10g00063b85prku497j%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsslp10g00023b85eelmupw3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsslp10g00043b856db56rlw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsslp10g00053b85exw951wv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsslp10g00023b85eelmupw3%2522%253A%257B%2522id%2522%253A%2522clsslp10g00023b85eelmupw3%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsslp10g00053b85exw951wv%2522%253A%257B%2522id%2522%253A%2522clsslp10g00053b85exw951wv%2522%252C%2522activeTabId%2522%253A%2522clssmlrmc00j13b86yxvnpzwa%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clssmlrmc00j13b86yxvnpzwa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clsslp10g00043b856db56rlw%2522%253A%257B%2522id%2522%253A%2522clsslp10g00043b856db56rlw%2522%252C%2522activeTabId%2522%253A%2522clsslpiey00a03b854mqni8ra%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsslp10g00033b85d0cp9nnh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsslp1gr000bd8f857u98yyl%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clsslpiey00a03b854mqni8ra%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Initial load: Tab element width = 100px, TabIndicator width = 100px
2. Click a button that adds an SVG element inside the Tab element
3. Tab element width increases to 140px, but TabIndicator width is still 100px

### Chakra UI Version

1.8.9

### Browser

Arc v1.29.0 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by rothbart** [comment] 2024-07-21 17:44
Running into the same issue.

**Comment by segunadebayo** [comment] 2024-08-24 13:49
Duplicate of #7450

**Closed by segunadebayo** 2024-08-24 13:49 UTC

**Comment by rothbart** [comment] 2024-08-24 13:53
I'm not sure this is a dupe. The 'position=relative' fix mentioned in that thread doesn't work, and this isn't happening on window resize (it's happening when Tabs get a new size because their children re-rendered with updated content).
