### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Emyboy** [chakra-ui/chakra-ui#7021] opened 2022-11-22 01:54 UTC
### Description

After installing chakra and importing the provider. This happened. Any ideas?

![image](https://user-images.githubusercontent.com/34845973/203197190-57cd71c5-3e4d-42fb-a70a-6141fa2bbe91.png)

### Link to Reproduction

no-url-ATM

### Steps to reproduce

1. Use node 16  ``nvm install 16`` then run  ``nvm use 16``
2. Create new CRA projects
3. Install Chakra-UI ``npm i @chakra-ui/react @emotion/react @emotion/styled framer-motion``
4. start the project ``npm start``

### Chakra UI Version

^2.3.0

### Browser

Microsoft Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Dependency Tree 
![image](https://user-images.githubusercontent.com/34845973/203197760-5b1bc599-bb86-4ee7-87db-286ff600bbf2.png)

**Comment by anddoutoi** [comment] 2022-11-22 09:08
> 2. Create new CRA projects

Dependency Tree
```json
  "dependencies": {
    
    "react-scripts": "^2.1.3"
    
  }
```
🤔

**Comment by segunadebayo** [comment] 2022-11-22 09:49
Duplicate of #6828

**Closed by segunadebayo** 2022-11-22 09:49 UTC
