### ISSUE TITLE
popover trigger doesn't close in Safari and Firefox

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#3461] opened 2021-02-26 03:52 UTC
### 🐛 Bug

Right now in Safari or Firefox, after a popover has already been opened, clicking the trigger a second time will quickly close it (due to the click outside) and then re-open it again. This bug does not appear in Chrome. (You can reproduce on the Popover docs page: https://chakra-ui.com/docs/overlay/popover)

**Comment by dodas** [comment] 2021-02-26 14:05
I can't reproduce this issue in the docs:
![popover](https://user-images.githubusercontent.com/14360171/109309796-07dd8780-7844-11eb-93d5-a5e530c1a002.gif)

**Comment by ianstormtaylor** [comment] 2021-02-26 16:34
@dodas interesting, that makes me feel a little better. It looks like the bug does not appear in Chrome, but it *does* appear in Safari and Firefox. (I've updated the original issue to make that clear.)

**Comment by dodas** [comment] 2021-02-27 21:35
So far I tracked it down to the `useFocusOnShow` hook.
Popover toggling works fine if you use `autoFocus={false}`.

**Comment by dodas** [comment] 2021-02-28 20:09
Turns out the problem is [Firefox/Safari on Mac OS don't focus `<button>` on click](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus).
That causes a bug in Chakra's code, [exactly here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/popover/src/use-popover.ts#L213), because `event.relatedTarget` is `null` in these 2 browsers, instead of the popover toggle `<button>`.

**Comment by segunadebayo** [comment] 2021-03-20 19:48
I pushed a fix for this. Should be available in the next release.

If after the upgrade the problem still exists in your application, I'll re-open it.

**Closed by segunadebayo** 2021-03-20 19:48 UTC
Labels: Type: Bug 🐛

**Comment by yss14** [comment] 2022-05-06 07:43
@segunadebayo Good news: On Firefox it seems to be fixed. Bad new: I would like to re-open the issue since the problem still exists for both Safari desktop and mobile.

![ChakraUI Bug Popover Safari](https://user-images.githubusercontent.com/4346842/167088675-dbd89b00-4344-4a2d-9882-70cfed868761.gif)

I simply took the [first code example](https://chakra-ui.com/docs/components/overlay/popover) from the docs and pasted it into a [codesandbox](https://codesandbox.io/s/pensive-tree-9ip0yi?file=/src/index.tsx) with latest `@chakra-ui/react` installed.

I tested it on Safari desktop `14.1.2` and mobile Safari on iOS 14.5.

**Comment by KirillKirill** [comment] 2022-06-22 12:36
@yss14 hey! try to set `autoFocus={false}` to the `<Popover />` component. It works out for me

**Comment by declan94** [comment] 2022-07-29 06:34
But unfortunately this would make `close On Blur` fail to work

> @yss14 hey! try to set `autoFocus={false}` to the `<Popover />` component. It works out for me

**Comment by Rangoons** [comment] 2022-09-07 21:24
This is still an issue. We are trying to get by with using `<Menu>` but we are using `react-virtual` inside and `Menu` makes this feel clunky and requires work arounds.

**Comment by jonahallibone** [comment] 2022-12-20 05:34
+1 also having this issue in chrome

**Comment by KirillKirill** [comment] 2022-12-20 07:13
i was able to solve that this way:

hook:

`const usePopoverControls = (buttonRef: RefObject<HTMLButtonElement>, popoverRef: RefObject<HTMLElement>) => {
  const { isOpen, onOpen, onClose } = useDisclosure();

  useEffect(() => {
    const handleClickOutside = (e: Event) => {
      if (popoverRef.current && !popoverRef.current.contains(e.target as Node)) {
        if (isOpen && buttonRef.current && buttonRef.current.contains(e.target as Node)) {
          e.preventDefault();
        }
        onClose();
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [popoverRef, isOpen, onClose, buttonRef]);

  const handleOpenMenu = () => {
    onOpen();
  };

  const handleCloseMenu = () => {
    onClose();
  };

  return {
    handleOpenMenu,
    handleCloseMenu,
  };
};` 

and then in component:

`const MyPopover: FC<MyPopoverProps> = ({ props }) => {
  const buttonRef = useRef<HTMLButtonElement>(null);
  const popoverRef = useRef<HTMLElement>(null);

  const { handleOpenMenu, handleCloseMenu } = usePopoverControls(buttonRef, popoverRef);

  return (
    <Popover
      strategy="fixed"
      onOpen={handleOpenMenu}
      onClose={handleCloseMenu}
      {...stuff}
    >
      {({ isOpen, onClose }) => (
        <>
          <PopoverTrigger>
            <MyButton ref={buttonRef} isActive={isOpen} />
          </PopoverTrigger>
          <Portal>
            <PopoverContent
              ref={popoverRef}
              {...stuff}
            >
              {...otherStuff}
            </PopoverContent>
          </Portal>
        </>
      )}
    </Popover>
  );
};

export default MyPopover;`

**Comment by NairiAreg** [comment] 2024-03-02 09:11
I have that issue on Opera https://github.com/chakra-ui/chakra-ui/issues/3461#issuecomment-1119345526
Simple example, I guess maybe my component is reRendering after close and it is reopening immediately
