### ISSUE TITLE
useBreakpoint and useBreakpointValue hooks causes react #185 error (Maximum update depth exceeded)

### ISSUE THREAD

**Issue by GabrielMochi** [chakra-ui/chakra-ui#3182] opened 2021-01-27 18:42 UTC
# 🐛 Bug report

> The page content keeps reloading infinitely when using `useBreakpoint` or `useBreakpointValue`, causing "maximum update depth exceeded" error in react. This problem only occurs the when page's width is between 769px and 1535px. Also, I can only reproduce this error when building Next.js for production using Docker.

## 💥 Steps to reproduce

1. Add `useBreakpoint` or `useBreakpointValue` hooks
2. Add some console.log passing any value that you want in the same place where the hook are implemented
3. Generate a build using Docker (Dockerfile example below). Command: `docker build . -t test`
4. Run the application through Docker. Command: `docker run -p 80:80 -it test`
4. Open the browser on application's port
5. Sets window's width between 769px and 1535px
5. Open Browser's console to see the log that you inserted in the code being printed repeatedly

## 💻 Link to reproduction

> - Code Example:
>   [Code Example](https://codesandbox.io/s/intelligent-black-ptb8h?file=/src/App.tsx)

> - Dockerfile Example:
>   [Dockerfile Example](https://codesandbox.io/s/intelligent-black-ptb8h?file=/Dockerfile)

## 🧐 Expected behavior

> The page's content shouldn't be reloading infinitely when using `useBreakpoint` or `useBreakpointValue` hooks.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.1.6      |
| React          |          17.0.1         |
| Next.js          |          10.0.2         |
| Node          |          14.15.4-alpine (Docker image)          |
| Browser          |      Goocle Chrome - Version 87.0.4280.141 (Official Build) (64-bit)      |
| Operating System |     Ubuntu 20.04.1 LTS       |

## 📝 Additional information

[Screenshot](https://i.ibb.co/Sm2rBr8/Screenshot-2021-01-27-at-15-34-34.png)

**Comment by with-heart** [comment] 2021-01-27 19:48
Weird. I followed the steps and I just see the message being printed twice (due to `React.StrictMode` which enabled by default with CRA). I did notice that you said you can only reproduce with Next.js in prod though, which this isn't, so maybe that's the reason this isn't working for me.

**Comment by with-heart** [comment] 2021-01-27 19:52
That range of pixels though is exactly the range between our default `md` (`48em`) and `2xl` (`96em`) breakpoints at default browser font size of `16px`. Is your project doing anything with custom breakpoints in `theme`?

**Comment by cschroeter** [comment] 2021-01-31 21:47
Closing in favour of #3042

**Closed by cschroeter** 2021-01-31 21:47 UTC
