### ISSUE TITLE
NumberInput disabled style not working

### ISSUE THREAD

**Issue by yjkwon07** [chakra-ui/chakra-ui#6714] opened 2022-09-19 05:37 UTC
### Description

when I use props isDisabled, not working disabled style (ex. cursor: now-allowed).  also, extendTheme is not working too.

### Link to Reproduction

NumberInput

isDiabled: https://codesandbox.io/s/cranky-fire-qf24c9?file=/src/index.tsx
extendTheme: https://codesandbox.io/s/billowing-smoke-vu6s8j?file=/src/index.tsx

### Steps to reproduce

```
 components: {
    NumberInput: {
      baseStyle: {
        field: {
          _disabled: {
            opacity: 0.4,
            cursor: "not-allowed"
          }
        }
      }
    }
  }

```

![image](https://user-images.githubusercontent.com/31876632/190955258-02f5ffce-2e7b-4893-a72d-b4ecc13f9c73.png)

### Chakra UI Version

2.3.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment] 2022-09-21 09:15
Closing as duplicate of #6627

**Closed by anubra266** 2022-09-21 09:15 UTC
