### ISSUE TITLE
Docs 1.0: Add SearchField and/or order components alphabetically

### ISSUE THREAD

**Issue by JohannesKlauss** [chakra-ui/chakra-ui#2603] opened 2020-11-24 16:18 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

With 0.8 the component docs are sorted alphabetically, so you can find what you are looking for pretty fast.
With 1.0 the component list is sorted by semantics. This makes it really hard to find the docs for specific components. For example to find the docs for the Accordion component you have to know that it is filed under "disclosure" and where that group is sorted relative to the other groups.

## Describe the solution you'd like

Either provide a top bar search field to look up specific component docs or provide the possibility to sort the components alphabetically. I personally dislike the semantical grouping. It makes sense for a kitchen sink like showcase, but users of chakra will most likely be using the docs to lookup specific components as fast as they can.

**Comment by with-heart** [comment] 2020-11-24 16:23
Hi @JohannesKlauss, I'm going to close this as a duplicate of #2264 for now. I agree that it's hard to find things but we're working on adding search functionality currently. If adding search doesn't resolve this, we can definitely revisit a flattened sidebar later.

**Closed by with-heart** 2020-11-24 16:23 UTC
Labels: Topic: Documentation 📚
