### ISSUE TITLE
Button error on submit using props loadingText and isLoading 

### ISSUE THREAD

**Issue by saxxas88** [chakra-ui/chakra-ui#4787] opened 2021-10-04 14:49 UTC
### Description

When translate page on Chrome, error generated when click Button and used the props loadingText and isLoading. Bug is present from version 1.6.6, while doesn't exists until version 1.6.5 .

### Link to Reproduction

https://codesandbox.io/s/dreamy-greider-1uqyl

### Steps to reproduce

1. Go to 'https://1uqyl.csb.app/'
2. Translate the webpage on Chrome 
3. Click on Button
4. See error ' Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.'

### Chakra UI Version

^1.6.6

### Operating System

- [X] macOS
- [x] Windows
- [x] Linux

**Comment by aboveyunhai** [comment] 2021-10-04 22:03
I cannot confirm but it is probably a `React` or `Google Translate page` bug? Google translate mutate the `dom` so it causes inconsistency between the `dom` and react `virtual dom`.  Maybe you should try out the same thing in regular react application.

**Comment by saxxas88** [comment] 2021-10-05 05:27
These Button component properties worked until @chakra-ui/react 1.6.5.
In the same example project, just change the version of
@chakra-ui/react to notice the difference


Il mar 5 ott 2021, 00:03 aboveyunhai ***@***.***> ha scritto:

**Comment by saxxas88** [comment] 2021-10-05 05:30
These Button component properties worked until @chakra-ui/react 1.6.5.
In the same example project, just change the version of
@chakra-ui/react to notice the differenze.

**Comment by aboveyunhai** [comment] 2021-10-05 06:30
> These Button component properties worked until @chakra-ui/react 1.6.5. In the same example project, just change the version of @chakra-ui/react to notice the differenze.

the issue starts from `@chakra-ui/react 1.6.6-next.1`, and it only appears when we use `isLoading`.
Interesting, wonder what happen behinds those commits.

This commit is particularly suspicious for me, but most likely I'm wrong.
https://github.com/chakra-ui/chakra-ui/commit/b14a19dfd970f3508eb7e73bd0fbae2ffcf574ad?branch=b14a19dfd970f3508eb7e73bd0fbae2ffcf574ad&diff=unified#diff-636c77268f1dbadc586f809af693f048118d1b710c54dcdef095f40d374f0553R122

**Comment by aboveyunhai** [comment] 2021-10-05 06:54
I reduce your problem into the following case;
https://codesandbox.io/s/quizzical-andras-ijh7q?file=/src/index.js
It is indeed interesting. I felt like the working version (<1.6.5) does not justify the true issue
You can try to switch between `detected language` and other `language`, and click button to see what happens inside the button.

**Comment by saxxas88** [comment] 2021-10-05 10:54
I don't think it's a React problem.

**Comment by saxxas88** [comment] 2021-10-05 14:10
@aboveyunhai I don't understand how this example is related to the case I proposed

**Comment by aboveyunhai** [comment] 2021-10-05 18:25
> @aboveyunhai I don't understand how this example is related to the case I proposed. The problem is not related to the changes of state only in React, but to the changes of state in React related to a component of Chakra-ui working up to the previous version.

No, even in 1.6.5, both components (Chakra, regular react button) failed in my testing cases. In fact, I'm trying to figure out the source issues regardless it's Chakra or not. 
As far as how I understand Chakra UI or other UI libs. the button is most likely built on top of the html `<button/>`. 
If it's the case, the implementation could be **correct** but does not work **as intent**. 
My assumption (which could be wrong) may provide some insides for Chakra Team to make a work around.

**Comment by segunadebayo** [comment] 2021-10-05 19:56
Hi @saxxas88,

This issue is not related to Chakra UI itself. The button itself is just a `<button>` element with some styles applied to it so I don't understand how that error will happen.

It's likely due to some Chrome extension, I doubt it's a react problem as well but I might be wrong.

I'm going to close this as it's unrelated to Chakra.

**Closed by segunadebayo** 2021-10-05 19:56 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by saxxas88** [comment] 2021-10-06 09:29
@segunadebayo 
chakra-ui 1.6.5 :

https://user-images.githubusercontent.com/45594922/136177015-4efe57d4-aedf-42f6-a172-ecfad722ecbd.mp4

chakra-ui ^1.6.6 : 

https://user-images.githubusercontent.com/45594922/136177070-20031c3f-c4ab-4651-84b8-b769fc980d1c.mp4

**Comment by Edjevw12** [comment] 2022-02-07 14:29
It's unrelated to chakra,  you should wrap your text for the button/link elements in a span. 

```js
<Button><Box as="span">CLICK</Box></Button>
```

**Comment by aboveyunhai** [comment] 2022-02-07 20:57
> It's unrelated to chakra,  you should wrap your text for the button/link elements in a span. 
> 
> ```js
> <Button><Box as="span">CLICK</Box></Button>
> ```

Just an question, if this solved the issue. Does it mean for project that require some sorts of internationalization supports. It will be annoying to capsulize the text like this for many components.

**Comment by macko911** [comment] 2022-02-14 09:54
If I understand it correctly the issue IS sort of related to Chakra because of the way it wraps button content with an extra `span` based on the `isLoading` prop?
https://github.com/chakra-ui/chakra-ui/blob/d24f935aa66d35b07e4e7dc456ec9cfcfacbec53/packages/button/src/button.tsx#L150-L158

I couldn't think of a proper solution to this so for now I've created a wrapper component for chakra Button that makes sure all Buttons have content wrapped in a `span`

```tsx
import { forwardRef } from 'react'
import { Button as ChakraButton, ButtonProps } from '@chakra-ui/react';

const Button = forwardRef<HTMLButtonElement, ButtonProps>(({ children, ...props }, ref) => {
	return (
		<ChakraButton ref={ref} {...props}>
			{/*
				https://github.com/chakra-ui/chakra-ui/issues/4787
				Need to wrap all Button children in a span because of issue with Google Translate
			*/}
			<span>{children}</span>
		</ChakraButton>
	);
});
```

**Comment by macko911** [comment] 2022-02-15 09:55
I came across the same issue when specifying `loadingText` prop, which also needs to be wrapped with a `span` for the same reason. Another problem here is that TS expect the prop to be a `string`.
