### ISSUE TITLE
Chakra components broken/unstyled in Storybook

### ISSUE THREAD

**Issue by jbarzegar** [chakra-ui/chakra-ui#3607] opened 2021-03-17 21:00 UTC
# 🐛 Bug report

Chakra styles seem to get lost when using it with the newest version of CRA & Storybook.  Chakra works fine if the same components are rendered outside of storybook.  In the reproduction, I included a counter-story using [Theme-UI](theme-ui.com/) and unfortunately this issue seems isolated to chakra

## 💥 Steps to reproduce

No steps to reproduce, Bug occurs on mount.

## 💻 Link to reproduction

[Reproduction repo](https://github.com/jbarzegar/chakra-storybook-repro) (check `standard-cra` dir)
[Deployed reproduction](https://6052692da97c1c38d3003cd5--elated-wing-e2a169.netlify.app/?path=/story/chakra-counter--counter-story)

## 🧐 Expected behavior
Styles should be applied to components in storybook the same way as other environments.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |        `1.3.4`    |
| Browser          |  `Firefox(v86.0.1)`, `Chrome(v89.0.4389.90)`         |
| Operating System |    `macOS Mojave(v10.14.6)`       |
| `@storybook/react` |  `6.1.21`

**Comment by with-heart** [comment] 2021-03-17 22:12
Closing this as a duplicate of #2527. This is a problem with `emotion` version conflicts between Storybook and Chakra, as Storybook is still using `emotion` v10 while we're on v11. There a few possible solutions in that issue, but including these two lines in your `.storybook/main.js` config should resolve the problem: https://github.com/chakra-ui/chakra-ui/blob/main/.storybook/main.js#L22-L23

**Closed by with-heart** 2021-03-17 22:12 UTC

**Comment by nidomiro** [comment] 2021-11-12 18:39
Is it possible to document this solution on the main page? I was about to go insane because chackra-ui was broken inside storybook and I couldn't figure out why.

**Comment by FilipeNMarques** [comment] 2022-05-18 14:51
> Closing this as a duplicate of #2527. This is a problem with `emotion` version conflicts between Storybook and Chakra, as Storybook is still using `emotion` v10 while we're on v11. There a few possible solutions in that issue, but including these two lines in your `.storybook/main.js` config should resolve the problem: https://github.com/chakra-ui/chakra-ui/blob/main/.storybook/main.js#L22-L23

Thank you!!
