### ISSUE TITLE
Black color isn't chaning while customizing the theme.

### ISSUE THREAD

**Issue by nishu-murmu** [chakra-ui/chakra-ui#5550] opened 2022-02-09 06:03 UTC
### Description

I wanted to change the default black and white color in theme, white color seems to work but black color isnt changing.

### Link to Reproduction

https://codesandbox.io/s/youthful-monad-8t587?file=/src/index.js

### Steps to reproduce

I have commented where the issue is in `index.js` file

### Chakra UI Version

1.8.1

### Browser

Google Chrome 97.0.4692.99

### Operating System

- [x] macOS
- [x] Windows
- [X] Linux

**Comment by TimKolberger** [comment] 2022-02-10 21:14
I could not see any usage of the colors token black and white in the linked CodeSandbox.

Kindly see the updated [CodeSandbox](https://codesandbox.io/s/determined-lucy-cilkf?file=/src/index.js) or the code below.

```js
import { ChakraProvider, extendTheme, Text } from "@chakra-ui/react";

const theme = extendTheme({
  colors: {
    white: "#4FD1C5",
    black: "#2B6CB0",
    brand: {
      100: "#f7fafc",
      // ...
      900: "#1a202c"
    }
  }
});

ReactDOM.render(
  <ChakraProvider theme={theme}>
    <Text color="black" bg="white">
      This text is black
    </Text>
    <Text color="white" bg="black">
      This text is white
    </Text>
    <Text color="brand.100">This text is brand.100</Text>
    <Text color="brand.900">This text is brand.900</Text>
  </ChakraProvider>,
  document.getElementById("root")
);
```

If you are in need to define global styles, see [Chakra UI Docs | Global Styles](https://chakra-ui.com/docs/features/global-styles).

Closing this because it is not a bug.

**Closed by TimKolberger** 2022-02-10 21:14 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by nishu-murmu** [comment] 2022-02-11 14:51
Thank you, I thought it would set automatically.
