### ISSUE TITLE
[Stack][V1] Stack spacing overrides children margins

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#1128] opened 2020-07-04 13:43 UTC
Currently `Stack` uses `*:not(style) ~ *:not(style)` but this selector has more specificity (read more [here](https://css-tricks.com/specifics-on-css-specificity/)) than the class applied by emotion to stack children

A solution would be to add the `!important` to every margin style applied to child of stack, so we should document that

A sandbox with an example
https://codesandbox.io/s/upbeat-wind-s45ww?file=/src/App.js

**Comment by with-heart** [comment] 2020-07-05 01:22
Duplicate of #1121. I've reposted your comment there as it has useful information :)

**Closed by with-heart** 2020-07-05 01:22 UTC
