### ISSUE TITLE
Error with @chakra-ui/image 1.1.1 (chakra-ui 1.7.1) when running tsc

### ISSUE THREAD

**Issue by mihett05** [chakra-ui/chakra-ui#5082] opened 2021-11-13 10:33 UTC
### Description

When I started development of new app with vite and chakra-ui, I noticed that there is TS error in @chakra-ui/image on compile

### Link to Reproduction

It's error with typescript

### Steps to reproduce

1. Create new app using with importing chakra 1.7.1
2. Run `tsc`
3. See error

### Chakra UI Version

1.7.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

TS error log:
```js
node_modules/@chakra-ui/image/dist/declarations/src/use-image.d.ts:1:23 - error TS2688: Cannot find type definition file for 'next'.

1 /// <reference types="next" />
```

**Comment by cschroeter** [comment] 2021-11-13 10:58
Thank you for taking the time to create this issue. Unfortunately, it does not contain a demo setup so we can work on this issue.

Therefore we have to close this issue. You can create a new issue at any time - please use the corresponding issue template.

Happy hacking ✌️

**Closed by cschroeter** 2021-11-13 10:58 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by Moeface** [comment] 2021-11-15 05:41
I too am having this issue as of 1.7.1.

**Comment by oscartbeaumont** [comment] 2021-11-15 23:44
I am also having this issue. My project is using [Vite](https://vitejs.dev/) and not [Next.js](https://nextjs.org/) which I think is what Chakra is looking for types from.
I temporarily fixed it by running `yarn add -D next`.
When I get some free time I will make an example project to reproduce the bug.

**Comment by thomaseizinger** [comment] 2021-11-16 23:40
> Thank you for taking the time to create this issue. Unfortunately, it does not contain a demo setup so we can work on this issue.

Here is a sandbox: https://codesandbox.io/s/objective-saha-q7tbc?file=/tsconfig.json
You will have to download it and run `yarn run tsc` to see the error because it only happens during type-checking and not bundling.

**Comment by paulopontovaz** [comment] 2021-11-18 19:13
This is happening to me too. I just created a very small Vite project with React + TS. Vite uses `tsc` before running `vite build` by default. After I installed `@types/next`, similar to what @oscartbeaumont did, the issue was handled, although not solved.

**Comment by thomaseizinger** [comment] 2021-11-18 22:15
@cschroeter Can you reopen this issue please? It is still a problem!

**Comment by tkesgar** [comment] 2021-11-25 09:47
It seems that there is a line `/// <reference types="next" />` in the compiled TypeScript definition file for `use-image` module. It will cause issue on projects that do not use Next.js, since the package does not exist.

https://unpkg.com/browse/@chakra-ui/image@1.1.1/dist/declarations/src/use-image.d.ts

I do not have a clue why this line would exist. It only occurs in one file.

Some workarounds:
- Add `"skipLibCheck": true` to your `tsconfig.json`. This will skip package definitions to be checked deeply: https://www.typescriptlang.org/tsconfig#skipLibCheck
- If you are using Yarn, you can try [resolution](https://yarnpkg.com/cli/set/resolution). I don't use Yarn so I have not tried this.
- You can manually remove the line in the file. Search the `node_modules` folder for `/// <reference types="next" />` and remove any lines from the file `use-image.d.ts`. This will not work on automated environments such as CI, but if you are still working in local environment, this is a temporary workaround until a proper fix is created.

**Comment by shadowdreamer** [comment] 2021-12-03 16:10
@cschroeter still has this problem in v1.7.2

**Comment by JamesWrightDev** [comment] 2021-12-17 01:36
> * Add `"skipLibCheck": true` to your `tsconfig.json`. This will skip package definitions to be checked deeply: https://www.typescriptlang.org/tsconfig#skipLibCheck

This did not initially work (even though `skipLibcheck` was enabled in my `tsconfig.json`), my solution was to add a flag on my build command i.e `"build": "tsc --skipLibCheck && vite build"`

**Comment by keidarcy** [comment] 2021-12-19 13:40
`v1.7.3` same problem.
for temporarily solution set `"skipLibCheck": true,` in tsconfig.json

**Comment by Dammmien** [comment] 2021-12-20 15:49
Same problem for me with `v1.7.3` and I'm not using Vite:
```json
  "dependencies": {
    "@chakra-ui/react": "1.7.3",
    ...
    "esbuild": "0.14.6",
    ...
    "react": "17.0.2",
    ...
    "typescript": "4.5.4"
  }
```

**Comment by tkesgar** [comment] 2021-12-21 12:36
I looked at `use-image.ts` but it does not seem to contain any references to Next.js globals, nor it imports `next`.

I tried compiling the package on local but the line `/// <reference types="next" />` does not appear:

![image](https://user-images.githubusercontent.com/2698543/146929811-eebaffd7-7472-457c-ab62-24f07779c85f.png)

The package does have `next` installed because it is used in `examples/nextjs-typescript`:

```
yarn why v1.22.17
[1/4] Why do we have the module "next"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "next@11.1.3"
info Reasons this module exists
   - "_project_#chakra-nextjs" depends on it
   - Hoisted from "_project_#chakra-nextjs#next"
   - Hoisted from "_project_#chakra-nextjs-ts#next"
info Disk size without dependencies: "48.23MB"
info Disk size with unique dependencies: "48.23MB"
info Disk size with transitive dependencies: "48.23MB"
info Number of shared dependencies: 167
Done in 1.78s.
```

Any other ideas on where to look at?
