### ISSUE TITLE
When styling Tooltip with theme variants, background colour is not applied to arrow if hasArrow={true}

### ISSUE THREAD

**Issue by selvinkuik** [chakra-ui/chakra-ui#4775] opened 2021-10-01 11:18 UTC
### Description

When styling Tooltip with theme variants, background colour is not applied to arrow if hasArrow={true}

### Link to Reproduction

https://codesandbox.io/s/musing-allen-r7gtj

### Steps to reproduce

Preview of the output, note the arrow should be white.

![Screenshot 2021-10-01 at 12 17 22](https://user-images.githubusercontent.com/3469560/135611395-295d1e81-e81e-408d-9f5f-aded8b1dd4bc.png)

### Chakra UI Version

1.6.5

### Browser

Google Chrome 94

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TimKolberger** [comment] 2021-10-03 15:28
Hi @selvinkuik

To update the arrow bg you need to set the corresponding css variable `--popper-arrow-bg`.

At the top of every component documenatation page is a link to their theme style. It makes it easier to override the styles if you know what the default looks like.

![image](https://user-images.githubusercontent.com/16899513/135760724-4e4ccc93-aeb0-4c34-92d2-83ceb3aa969c.png)

I updated your codesandbox example like this: 

```ts
const theme = extendTheme({
  components: {
    Tooltip: {
      variants: {
        white: {
          "--popper-arrow-bg": "colors.white",
          bg: "white",
          color: "black"
        }
      }
    }
  }
});
```

I am closing this, because it is not a bug in chakra-ui.

**Closed by TimKolberger** 2021-10-03 15:28 UTC
Labels: Type: Bug 🐛, needs triage
