### ISSUE TITLE
ref.current return "undefine" when using initialRef on Modal.

### ISSUE THREAD

**Issue by whistledev0910** [chakra-ui/chakra-ui#5257] opened 2021-12-17 19:10 UTC
### Description

 You can see the details in the picture I attached.

### Link to Reproduction

https://chakra-ui.com/docs/overlay/modal

### Steps to reproduce
When open modal, initialRef.current is undefined.
![image](https://user-images.githubusercontent.com/88497295/146596101-2806357f-ee19-4ab6-a427-aa99daf354c4.png)

When close modal, initialRef.current have value.
![image](https://user-images.githubusercontent.com/88497295/146596228-d8ade47e-688d-4cd2-b1b8-f5f5ac5f249f.png)

Because the result returned when I call initialRef.current is undefined I cannot continue to the next steps. Please tell me again why I am getting 'undefine'. Tkank you very much!

### Chakra UI Version

1.6.10

### Browser

Microsoft Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by primos63** [comment] 2021-12-18 05:13
I believe this to be a misunderstanding of useEffect and how the components are rendered.
Good [guide](https://overreacted.io/a-complete-guide-to-useeffect/) on useEffect by Dan Abramov.
As the refs used in the docs example work correctly, I will close this issue.

**Closed by primos63** 2021-12-18 05:13 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by whistledev0910** [comment] 2021-12-18 05:16
I'm just looking for a way to be able to get the initialRef.current when the modal is displayed. Because the result returned is undefined, I cannot continue. Please tell me where am I going wrong.

**Comment by nvmnghia** [comment] 2022-04-18 08:07
@whistledev0910  any update? I bumped into this too. it seems that the component containing `<Modal>` renders twice, both has `isOpen = true`.

**Comment by JTBrinkmann** [comment] 2022-04-18 13:58
Primos said it perfectly:
> I believe this to be a misunderstanding of useEffect and how the components are rendered.

The issue is that you are trying to access the ref to an element **before** it is even rendered. At the time of your `console.log()`, the element is not yet in the browser's DOM. `initialRef.current` cannot have a correct value yet. Once it is rendered, `initialRef.current` will reference it, as you noticed. When a Modal is not open, its content is not rendered, so `initialRef.current` will be undefined. **After** the Modal is rendered, `initialRef.current` is set.

This is not Chakra or Modal specific, you will get the same result if you change the component to end with e.g. `return !isOpen ? <div>closed</div> : <div ref={initialRef}>open</div>`.

If you want to call a callback as soon as you can get hold of a reference to the DOM element, you can instead pass a **function** to the ref prop, like `<Input ref={initializeInput} />`. See [Callback Refs in the React docs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs).

**Comment by nvmnghia** [comment] 2022-04-19 01:44
I think I understand the reason now. What I'm doing is accessing something hook-related conditionally. I still don't understand this part:

> At the time of your console.log(), the element is not yet in the browser's DOM

since it's already `isOpen`. Maybe I have to read more about the rendering internal.

**Comment by JTBrinkmann** [comment] 2022-04-19 14:45
I see, you are right, I was somewhat wrong. The useEffect callback does get called after the render function of your component finishes, so it is indeed reasonable to expect the ref to be populated. I investigated it a bit more and noticed, that the issue is in Chakra's Portal (which is used by Modal). Portals mount their content in a `useSafeLayoutEffect` callback, which is executed after your `useEffect`.

## Workaround 1

extract the your modal's content to a separate component and use `useEffect` in there.
```js
function BasicUsage() {
  const buttonRef = useRef(null);
  const { isOpen, onOpen, onClose } = useDisclosure();

  return (
    <>
      <Button onClick={onOpen}>Open Modal</Button>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <MyModalContent buttonRef={buttonRef} onClose={onClose} />
      </Modal>
    </>
  )
}

function MyModalContent({ buttonRef, onClose }) {
  useEffect(() => {
    console.log('buttonRef.current', buttonRef.current)
  })
  return (
    <ModalContent>
      <ModalHeader>Modal Title</ModalHeader>
      <ModalCloseButton />
      <ModalBody>Bla bla</ModalBody>
      <ModalFooter>
        <Button onClick={onClose} ref={buttonRef}>
          Close
        </Button>
      </ModalFooter>
    </ModalContent>
  )
}
```


## Workaround 2

pass a callback to the `ref` prop:
```html
<Button
   ref={(ref) => {
      buttonRef.current = ref; // (optional)
      myCallback(ref)
  }}>
    Close
</Button>
```
