### ISSUE TITLE
Slider only works for one drag (broken even on documentation site)

### ISSUE THREAD

**Issue by tomhicks** [chakra-ui/chakra-ui#3071] opened 2021-01-16 12:23 UTC
# 🐛 Bug report

Slider stops working with the mouse after ending the first drag. Keyboard controls continue to work.

## 💥 Steps to reproduce

1. Go here: https://chakra-ui.com/docs/form/slider#usage
2. Use slider once with mouse
3. Try to drag slider a second time
4. Drag does not work

## 💻 Link to reproduction

https://chakra-ui.com/docs/form/slider#usage

## 🧐 Expected behavior

Slider should work for more than one drag

## 🧭 Possible Solution

?? Can probably work around it by changing the key when you've finished dragging!

## 🌍 System information

Latest chrome

**Comment by auto200** [comment] 2021-01-16 12:35
I just encountered this bug and wanted to submit an issue 😲

**Comment by mohamedabusrea** [comment] 2021-01-16 14:12
I also encountered this bug!!!

**Comment by dodas** [comment] 2021-01-16 14:42
Closing as a duplicate of #3040.
It is already fixed and waiting for release.

**Closed by dodas** 2021-01-16 14:42 UTC

**Comment by dodas** [comment] 2021-01-17 19:55
Released now in `@chakra-ui/react@v1.1.5`.
