### ISSUE TITLE
Issue with limits on useNumberInput hook

### ISSUE THREAD

**Issue by droyson** [chakra-ui/chakra-ui#5118] opened 2021-11-19 08:34 UTC
### Description

When I reach the min/max limit while using the useNumberInput hook it takes me 2 clicks to increment/decrement

### Link to Reproduction

https://chakra-ui.com/docs/form/number-input#create-a-mobile-spinner

### Steps to reproduce

1. Keep on decrementing till you hit the lower limit 
2. Click on the `+` button. The number doesn't increment .
3. Click on `+` button again the number starts to increment.

Attaching the screen recording for the same:

https://user-images.githubusercontent.com/28538540/142590496-f671d0ed-8ff2-46d6-bad4-ea2808fc2364.mov

### Chakra UI Version

1.6.10

### Browser

Google Chrome 95.0.4638.69

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

On further inspection observed the update function keeps on getting called recursively when the lower limit is reached. When the user clicks `+` first time the recursive call stops and then the update gets called with the new value.

**Comment by primos63** [comment] 2021-11-24 06:53
Thanks for contributing. I'm going to close this as it looks like it's a duplicate of #4776 which has a PR #4982 submitted to fix the issue.

**Closed by primos63** 2021-11-24 06:53 UTC
Labels: Type: Bug 🐛, needs triage
