### ISSUE TITLE
[ColorModeProvider] Color mode does not work in production

### ISSUE THREAD

**Issue by amolmt** [chakra-ui/chakra-ui#305] opened 2019-12-21 08:25 UTC
**Describe the bug**
Switching between dark and light mode is not working in production build.

**Expected Behavior**
After clicking on the color mode switcher button it should be switching theme colors between light and dark.

**To Reproduce**
I am using chakra-ui with gatsby with below mentioned versions:
`"gatsby": "^2.18.8",
"gatsby-plugin-chakra-ui": "^0.1.0",
`

**code**
`<ThemeProvider theme={theme}>
      <CSSReset />
      <ColorModeProvider>
        <Header siteTitle={data.site.siteMetadata.title} />
          <main>{children}</main>
          <Footer />
      </ColorModeProvider>
    </ThemeProvider>`

**Comment by MykalMachon** [comment] 2019-12-22 09:58
Hello @amolmt, **I think this is more an issue with Gatsby (_specifically, React_) than it is with Chakra-UI.** 

I've experienced bugs similar to this one myself when using gatsby. From what I know it has to do with the way Gatsby implements React's rehydrate method on statically generated pages. You can read more about it [here](https://www.gatsbyjs.org/docs/react-hydration/) and [here](https://github.com/gatsbyjs/gatsby/issues/9136).

**Comment by KenzoBenzo** [comment] 2020-01-23 18:45
Hey @amolmt & @MykalMachon! I've got it working successfully working for Gatsby. The trick is that the root of Gatsby is `gatsby-browser.js`. So the code I've got is:

```JavaScript
import React from "react"
import { ThemeProvider, ColorModeProvider, CSSReset } from "@chakra-ui/core"
import theme from "./theme/theme"

export const wrapRootElement = ({ element }) => (
  <ThemeProvider theme={theme}>
    <ColorModeProvider>
      <CSSReset />
      {element}
    </ColorModeProvider>
  </ThemeProvider>
)
```

**Comment by dimitrisnl** [comment] 2020-01-24 22:13
@KenzoBenzo 

I've tried this version too, but it seems that some elements don't have the dark-theme colors applied. Here's your website on the very first visit

<img width="1439" alt="Screenshot 2020-01-25 at 12 10 55 AM" src="https://user-images.githubusercontent.com/4951004/73107759-57e27000-3f07-11ea-86bc-a7818477c3be.png">
<img width="1354" alt="Screenshot 2020-01-25 at 12 11 09 AM" src="https://user-images.githubusercontent.com/4951004/73107760-587b0680-3f07-11ea-83a3-af01b3a75c8e.png">

Refreshing, or toggling the button on the top-right, works. The moment the localstorage gets populated there is no issue. But to this day I haven't worked around the same issue you're facing.

**Comment by b-b0t** [comment] 2020-03-13 12:34
+1

**Comment by KenzoBenzo** [comment] 2020-03-13 12:46
As a middle ground solution, I defined a few variables in my color theme as such:
```mode: {
    light: {
      logo: "#102a43",
      background: "#fff",
      cardBG: "#EFF2FB",
      text: "#334E68",
      heading: "#102a43",
      icon: "#9FB3C8",
      link: "#9F00FF",
    },
    dark: {
      logo: "#ffffff",
      background: "#102a43",
      cardBG: "#243B53",
      text: "#EFF2FB",
      heading: "#fff",
      icon: "#486581",
      link: "#F8CCFF",
    },
  },```
_note: better would have been to be able to call the color variables but I couldn't get it to work_

Then manually set the colors like so:
```
const HeroComponent = ({ title, subtitle }) => {
  const { colorMode } = useColorMode()
  return (
    <Heading
          mb={4}
          as="h1"
          lineHeight="shorter"
          fontWeight="900"
          color={`mode.${colorMode}.heading`}
          letterSpacing="wider"
        >
          {title}
    </Heading>
    <Text color={`mode.${colorMode}.text`} lineHeight="tall" mb={8}>
          {subtitle}
    </Text>
 )
}```

This will take control until local storage is set.

**Comment by jletey** [comment] 2020-03-31 18:58
This is very annoying, and would be happy to open a PR to fix it. Could anyone give me some guidance on how to get started?

**Comment by segunadebayo** [comment] 2020-04-01 14:52
Hi guys,

I understand it's a pain at the moment to get ColorMode working properly, that's why it was set to "in progress" in the docs. We'll fix this more permanently in the next release.

Looking through possible solutions, I found that you might need to use this no-flash script for it to work https://github.com/donavon/use-dark-mode/blob/develop/noflash.js.txt

If you're using Gatsby, there's a gatsby plugin you can use as well.

**Comment by jletey** [comment] 2020-04-01 19:16
> I found that you might need to use this no-flash script for it to work https://github.com/donavon/use-dark-mode/blob/develop/noflash.js.txt

@segunadebayo Thanks for finding this. However this script doesn't incorporate well with a Next.js and TypeScript setup. If anyone has a good way of including this script into this setup lmk!

**Comment by jletey** [comment] 2020-06-13 11:49
@segunadebayo Hiya 👋 What's the progress on this? I noticed [`initialize-color-mode.tsx`](https://github.com/chakra-ui/chakra-ui/blob/master/packages/color-mode/src/initialize-color-mode.tsx), but I'm still having the same issue:

![Screenshot 2020-06-13 at 12 48 34](https://user-images.githubusercontent.com/62398724/84567963-38dc6180-ad74-11ea-9847-57bef5c36435.png)

Is there any fix for this 🙏

**Comment by balibebas** [comment] 2020-06-19 15:38
> The trick is that the root of Gatsby is `gatsby-browser.js`.

@KenzoBenzo Thanks for the tip. Works great in development but Gatsby fails to generate HTML with `gatsby build` when the theme files are kept in the `src` folder and `Icon` is used. When theme files are kept in `src` the following [error](https://github.com/chakra-ui/chakra-ui/issues/430) occurs:

```
WebpackError: TypeError: Cannot read property 'question-outline' of undefined
```

Is that why you moved your theme files to your project root? If so, it's worth noting [here](https://github.com/chakra-ui/chakra-ui/issues/305#issuecomment-577818739) to save people time.

**Comment by dimitrisnl** [comment] 2020-06-19 16:08
@balibebas No, you need to include this in your `gatsby-ssr.js`

```js
export { wrapRootElement } from "./gatsby-browser"
```

This way you will get the icons during the build step too.

**Closed** 2020-09-27 12:57 UTC
Labels: Topic: Gatsby Plugin 🔌, Type: Bug 🐛

**Comment by RyanPinPB** [comment] 2020-11-10 19:46
I'm not sure if this is the correct place to post my issue, but after googling and looking for solutions, this looks like the most relevant page.

I'm using Gatsby w/ Chakra and have an issue with either local storage or how the ColorMode is being accessed.

Here's my repo: https://github.com/RyanPinPB/pdm-gatsby
Live site: https://pearsondigitalmarketing.com

ColorMode and components are styled correctly on localhost, but in production, the site has an issue when it renders my header after localstorage has saved darkMode=true.

You can reproduce this issue by going to my site, toggling dark mode, and refreshing. Or, if your browser has auto-themeing depending on your OS (or time of day), it will show the issue at night, or if your browser/OS prefers dark mode.

What is weird, is that certain components receive the correct darkMode styling (colorings and background), but my logo, menu, and header background are not correct. Even tho all 3 of these are using colorMode styling conditionals as follows:

  const bgColor = {
    light: "rgba(255,255,255,.6)",
    dark: "rgba(26, 32, 44, .6)",
  }
  const color = { light: "brand.400", dark: "brand.900" }


bg={bgColor[colorMode]}
color={color[colorMode]}

I added a console log to both index and header to see if one of them is rendering before the colorMode is triggered/called from local storage, but both console logs seem to have the correct colorMode state. I'm having a hard time figuring out why my header in darkmode has the wrong background color and colors.

Any help is greatly appreciated.

**Comment by hardikmodi1** [comment] 2020-11-28 08:33
Facing the same problem. 
Live Site - [https://hardikmodi.in](https://hardikmodi.in) 
Way to reproduce the issue is visit the site, toggle dark mode and refresh. Some component receives the dark mode styling some not. Like on home page post title does not get the correct styles. Once you toggle the dark mode it works as expected.

**Comment by with-heart** [comment] 2020-11-28 21:36
@RyanPinPB @hardikmodi1 Which version of Chakra are you on?

**Comment by hardikmodi1** [comment] 2020-11-29 05:49
I am using 0.8.0

**Comment by hardikmodi1** [comment] 2020-11-29 10:40
@with-heart  @RyanPinPB Just upgraded to v1.0 and it is working perfectly fine in production too. You can checkout my website for example.

**Comment by RyanPinPB** [comment] 2020-11-29 17:05
> @RyanPinPB @hardikmodi1 Which version of Chakra are you on?

I switched to v1 and everything works. Had to update a few things, but colorMode is now displaying properly

**Comment by with-heart** [comment] 2020-11-29 17:37
Glad to hear v1 fixed the issues for both of you! Color mode is hard and we put a lot of work into v1 to make sure it works reliably!
