### ISSUE TITLE
Change how Color Mode behaves: allow automatic setting

### ISSUE THREAD

**Issue by Manc** [chakra-ui/chakra-ui#4914] opened 2021-10-25 07:07 UTC
### Description

I've been digging into the code because I had trouble setting up Color Mode intuitively. In my opinion the following should generally be the default behaviour in 2021:

1. When a user visits the website for the first time, the system setting should be applied automatically (e.g. dark mode at night).
2. When the system's color mode changes, all the user's open app windows and websites should be expected to change to the new color mode.
3. The user may have the ability to lock in a different preferred color mode per website if there is an option for that on the website. This preference should then be persisted.
4. If the user has locked in a preferred color mode, they should still have the option to revert that back to "automatic". The persisted preference (e.g. in local storage) should then be deleted.

This is how it works on GitHub, https://developer.apple.com, and many other sites. It totally makes sense (to me).

<img width="1008" alt="Screenshot of the Footer of the Apple website" src="https://user-images.githubusercontent.com/811578/138649794-153d642a-affb-45d1-849a-2d5c24135bf6.png">

### Problem Statement/Justification

To my understanding of the Chakra UI code, this is not possible. I believe there's one central flaw: There is no differentiation between *current* color mode and *user preferred* color mode.

Currently, even if the config is set to consider the system's color mode, it may correctly detect the mode, but will then immediately persist that mode to local storage. Later, when the system mode changes, the website's mode will not change, because the previous mode has been persisted and will only ever change when the user click's, for example, the sun or moon button. Unless the user manually deletes the mode in local storage, the mode will never change back to "automatic", which should be the default in the most cases by far.

### Proposed Solution or API

`setColorMode` (of the `useColorMode()` hook) currently accepts a value of type `any`. It should accept `"light" | "dark" | "system"`.

[`localStorageManager`](https://github.com/chakra-ui/chakra-ui/blob/f77fd9999ec1105cf846cd830019d2c3ba5a0f4e/packages/color-mode/src/storage-manager.ts#L18) should only store the value if it is `"light" || "dark"` and *delete* the currently stored value if it is `"system"`.

A key problem is this bit ([reference](https://github.com/chakra-ui/chakra-ui/blob/f77fd9999ec1105cf846cd830019d2c3ba5a0f4e/packages/color-mode/src/color-mode-provider.tsx#L117)):

    if (useSystemColorMode) {
        removeListener = addListener(setColorMode)
    }

What happens here: Whenever the system color mode changes, set and persist the mode to local storage – forever.

BTW: I also propose that [`export const storageKey = "chakra-ui-color-mode"`](https://github.com/chakra-ui/chakra-ui/blob/f77fd9999ec1105cf846cd830019d2c3ba5a0f4e/packages/color-mode/src/storage-manager.ts#L5) can be customised in the config. It may be an edge case, but some people (like me) will want to integrate the Chakra UI site into only a sub-path of a bigger website (sharing the same domain) and there may be already a preference with a different (neutral) name.

### Alternatives

I tried to work around it by implementing my own `localStorageManager`, however this is not enough as the `ColorModeProvider` requires some changes.

### Additional Information

I'd be happy to assist with the changes, but would like to get feedback on the proposed changes first. Thank you!

**Comment by takethefake** [comment] 2021-11-01 14:28
Hej @Manc thanks for reaching out!

We currently have a PR that should tackle this according to your wishes (https://github.com/chakra-ui/chakra-ui/pull/4634) Unfortunately I currently don't know when we will merge this since it may have implications on current expected behavior and maybe something we roll out in a major version.

**Comment by anubra266** [comment] 2021-11-09 12:37
Closing this as duplicate of #4987

**Closed by anubra266** 2021-11-09 12:37 UTC
Labels: needs triage

**Comment by luis-c-goncalves-alb** [comment] 2024-02-23 15:56
Any way to make `useSystemColorMode:true/false` dynamic? Like with some hook or external package? I´m struggling with that and don´t see anything helpfull in docs. Thanks
