### ISSUE TITLE
useToast can't be closed

### ISSUE THREAD

**Issue by marekhoeven** [chakra-ui/chakra-ui#2360] opened 2020-10-28 19:16 UTC
# Bug report

## Describe the bug

While opening a toast seems to work fine, trying to close it does not work at the moment. Also, the duration is not working it seems.

## To reproduce

You can see this bug also on the documentation site: https://next.chakra-ui.com/docs/feedback/toast

1. Click on 'Show Toast'
2. Try to close the toast, by clicking on the 'x'
3. Also notice that it does not close by itself

Bug also happens on my local reactjs-project

## Minimal reproduction

https://next.chakra-ui.com/docs/feedback/toast

## Expected behavior

Make the close button, close the toast and durationset close it after the set time

**Comment by ljosberinn** [comment] 2020-10-28 19:24
duplicate of #2345 #2328 #2331 - will be fixed with the next rc

**Closed by ljosberinn** 2020-10-28 19:24 UTC
