### ISSUE TITLE
isTruncated property of Text does not truncate the text when nested within Flex and Box

### ISSUE THREAD

**Issue by iainfreestone** [chakra-ui/chakra-ui#2611] opened 2020-11-24 22:33 UTC
# Bug report

## Describe the bug

Adding isTruncated to a ```<Text>``` component  nested within ```<Flex>``` ```<Box>``` does not truncate the text and the layout is also affected

## To reproduce

```
<Flex>
      <Box>
        <Text bg="teal.200" isTruncated>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
          tristique purus eu magna volutpat, sed suscipit erat dignissim. Etiam
          mollis mauris vitae ante tempus consectetur. Curabitur egestas, ante
          non varius congue, mauris erat rhoncus neque, in vestibulum libero
          nulla vel diam. Etiam in nisi erat. Quisque vehicula diam sit amet
          rhoncus lacinia. Vestibulum venenatis tellus non sapien ultricies
          tincidunt. Nam malesuada iaculis odio, quis porta eros sollicitudin
          id. Sed in mauris tristique, facilisis lacus nec, pretium lectus.
          Fusce sed pretium sapien, eleifend bibendum purus. Sed rutrum libero
          vehicula rhoncus imperdiet. Duis mattis tortor quis luctus lacinia.
        </Text>
      </Box>
      <Box>
        <Text bg="teal.400">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
          tristique purus eu magna volutpat, sed suscipit erat dignissim. Etiam
          mollis mauris vitae ante tempus consectetur. Curabitur egestas, ante
          non varius congue, mauris erat rhoncus neque, in vestibulum libero
          nulla vel diam. Etiam in nisi erat. Quisque vehicula diam sit amet
          rhoncus lacinia. Vestibulum venenatis tellus non sapien ultricies
          tincidunt. Nam malesuada iaculis odio, quis porta eros sollicitudin
          id. Sed in mauris tristique, facilisis lacus nec, pretium lectus.
          Fusce sed pretium sapien, eleifend bibendum purus. Sed rutrum libero
          vehicula rhoncus imperdiet. Duis mattis tortor quis luctus lacinia.
        </Text>
      </Box>
    </Flex>
```

## Minimal reproduction

[Code Sandbox Reproduction](https://codesandbox.io/s/hidden-leaf-32cpu)

## Expected behavior

Expected the long text to be truncated and the flex layout to be unaffected.

## Screenshots

Without isTruncated

![image](https://user-images.githubusercontent.com/22638086/100158719-88d35e80-2ea4-11eb-9aa6-531e85bdf0db.png)

With isTruncated
![image](https://user-images.githubusercontent.com/22638086/100158753-9852a780-2ea4-11eb-95c5-30e38b63bfd2.png)

## System information

- OS: Windows
- Browser (if applies): Chrome
- Version of @chakra-ui/react: 1.0.1
- Version of Node.js: 12.16.1

## Additional context

No additional comments

**Comment by TimKolberger** [comment] 2020-11-25 08:01
`isTruncated` is shorthand for [`text-overflow: ellipsis`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow).
This needs a container with `overflow: hidden` to work. Otherwise the overflow is visible and there is no need for the browser to truncate the text.

```jsx
<Flex>
  <Box overflow="hidden">
    <Text bg="teal.200" isTruncated>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
          tristique purus eu magna volutpat, sed suscipit erat dignissim. Etiam
          mollis mauris vitae ante tempus consectetur. Curabitur egestas, ante
          non varius congue, mauris erat rhoncus neque, in vestibulum libero
          nulla vel diam. Etiam in nisi erat. Quisque vehicula diam sit amet
          rhoncus lacinia. Vestibulum venenatis tellus non sapien ultricies
          tincidunt. Nam malesuada iaculis odio, quis porta eros sollicitudin
          id. Sed in mauris tristique, facilisis lacus nec, pretium lectus.
          Fusce sed pretium sapien, eleifend bibendum purus. Sed rutrum libero
          vehicula rhoncus imperdiet. Duis mattis tortor quis luctus lacinia.
      </Text>
  </Box>
</Flex>
```

I am closing this issue, because it is not a bug in chakra, just another curiosity of CSS.

**Closed by TimKolberger** 2020-11-25 08:01 UTC

**Comment by binajmen** [comment] 2021-04-21 09:48
Hi @TimKolberger,

I'm having a similar issue in a `<Table>` component, but the `overflow` doesn't seem to work:

```js
            <Td overflow="hidden">
              <Text isTruncated>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
                fermentum aliquam pulvinar. Aliquam et enim dapibus, malesuada
                nisi in, lacinia lacus. Ut a ultrices dolor. Aenean facilisis
                erat eu metus interdum sollicitudin.
              </Text>
            </Td>
```

https://codesandbox.io/s/cool-fire-2y7ox?file=/src/index.js

**Comment by TimKolberger** [comment] 2021-04-21 10:04
Maybe this solves your issue:

This would truncate the text if it exceeds the maximum width and it does not mess with the table layout.

```jsx
<Td>
  <Text isTruncated maxW="sm">
     {yourContent}
  </Text>
</Td>
```

Otherwise you could [open a Github Discussion](https://github.com/chakra-ui/chakra-ui/discussions/new) in the Q&A section to make your question visible to other users.

**Comment by dctanner** [comment] 2023-03-17 14:45
Fwiw it took me a good hour to work out how to correctly truncate inside a Flex. In the end I had to do this. Maybe we can add an example to the docs?

```
<Flex minW="0">
  <Box overflow="hidden">
    <Text isTruncated>Long text to truncate</Text>
  </Box>
</Flex>
```
