### ISSUE TITLE
Upgrading chakra-ui/react from v2.3.4 to v2.3.5 breaks vitest

### ISSUE THREAD

**Issue by saifbechan** [chakra-ui/chakra-ui#6783] opened 2022-10-03 11:58 UTC
### Description

When I upgrade chakra-ui/react from v2.3.4 to v2.3.5 it breaks vitest

### Link to Reproduction

https://github.com/saifbechan/nextjs-ts-eslint-chakraui-vitest-playwright

### Steps to reproduce

1. Check out the repository
2. Run `yarn`
3. Run `yarn test`
4. Everything works fine
5. Upgrade chakra-ui/react to 2.3.5
6. Run `yarn test`
7. You will get the following error
8. `ReferenceError: Cannot access '__vite_ssr_import_5__' before initialization`

### Chakra UI Version

2.3.5

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2022-10-03 12:32
The change we made between those versions is to provide explicit `exports` in the package.json for every component. I'm guessing there's something in Vitest that doesn't work or something we're not doing correctly.

Thanks for bringing this up

**Comment by sj-e2digital** [comment] 2022-10-04 19:42
I don't think the current `exports` configuration is correct. Either the esm files should be `.mjs` or the commonjs files `.cjs`, with the correct `type` property in package.json (module or commonjs).

**Comment by han-sz** [comment] 2022-10-05 01:38
I've noticed this issue when moving from chakra-ui `2.2.6` (tests run fine) to `2.2.7` and above (tests are broken) 

```
 ❯ node_modules/@chakra-ui/icon/dist/index.esm.js:11:6
ReferenceError: Cannot access '__vite_ssr_import_5__' before initialization
      9| import { cx } from "@chakra-ui/shared-utils";
     10| var fallbackIcon = {
     11|   path: /* @__PURE__ */ React.createElement("g", {
       |      ^
     12|     stroke: "currentColor",
     13|     strokeWidth: "1.5"
```

I've updated `vitest` from `0.21` to `0.23.4` and `vite` to `3.1.4` and our unit tests are still failing

**Comment by han-sz** [comment] 2022-10-05 06:00
**Workaround for now**

A workaround is to load the component that triggers the issue dynamically with `React.lazy` and `import`:

```
React.lazy(() => import('../components/MySelect`))
```

where `MySelect` is the component that uses the component that causes the issue

**Comment by RIP21** [comment] 2022-10-09 16:06
I confirm it's not a random thing. Happens to me too.

**Comment by saifbechan** [comment] 2022-10-09 19:46
> I confirm it's not a random thing. Happens to me too.

Yes it happens in all my projects. For now I locked the version to 2.3.4 and disabled Dependabot for now.

**Comment by South-Paw** [comment] 2022-10-11 10:08
Made a post in [Discord questions forum](https://discord.com/channels/660863154703695893/1029331164017729598/1029331164017729598), while unrelated to vitest, I've got some components from our design system breaking in apps when updating to 2.3.5. They work fine if I downgrade back to 2.3.4.

After much digging, I'm also left wondering if the exports changes in 2.3.5 are the culprit.

**Comment by pedrosimao** [comment] 2022-10-18 16:47
I am starting fresh with a project and could not get it working. I have tried to downgrade to the suggested versions, and I still face the same issue.

**Comment by michielglibert** [comment] 2022-10-19 08:09
Also having this issue, our migration to Vite is postponed because of this...

**Comment by itkrt2y** [comment] 2022-10-19 10:33
This looks like a vite's bug. https://github.com/vitejs/vite/issues/10444
You can fix vitest by `deps.fallbackCJS = true` for now. https://vitest.dev/config/#deps-fallbackcjs

**Comment by pedrosimao** [comment] 2022-10-19 13:11
@itkrt2y thanks a lot for the tip. Solved the issue on my side!

**Comment by lucasfrutig0** [comment] 2022-10-26 15:07
> **Workaround for now**
> 
> A workaround is to load the component that triggers the issue dynamically with `React.lazy` and `import`:
> 
> ```
> React.lazy(() => import('../components/MySelect`))
> ```
> 
> where `MySelect` is the component that uses the component that causes the issue, and to stub the component when in a test environment:
> 
> ```
> import.meta.env.TEST ? (<div data-testid="invite-select" />) : (<MySelect />)
> ```

i have the same problem and i use chackra v2.3.6, but i dont understand correctly why you import with lazy

**Comment by segunadebayo** [comment] 2022-11-01 18:20
Thanks for the tip @itkrt2y .

Kindly use this fix for now https://github.com/chakra-ui/chakra-ui/issues/6783#issuecomment-1283788233

**Comment by calvinf** [comment] 2022-11-04 00:20
Setting the following under `test` in my `vite.config.ts` fixed `vitest` for me for now (until the eventual fix lands in https://github.com/vitejs/vite/issues/10444). 

```typescript
      deps: {
        fallbackCJS: true,
      },

      ssr: {
        // required while deps.fallbackCJS is required
        noExternal: ['@chakra-ui/react'],
      },
```

**Comment by LizardLiang** [comment] 2022-11-21 02:47
I have my package setup like this 
![image](https://user-images.githubusercontent.com/12999887/202952093-ee403c3c-042c-49a7-8482-bfc7f52f131d.png)

and my vite,config,ts like this
![image](https://user-images.githubusercontent.com/12999887/202952169-1e607024-3f2e-4b31-9318-13e973d08202.png)

still having the same problem 
![image](https://user-images.githubusercontent.com/12999887/202952256-c2f40e5b-04fa-4293-be94-c9ae8fbbcfe0.png)

Does anyone have a fix for this?

thanks

**Comment by gabriel-durr** [comment] 2022-12-01 14:48
Also having this problem, waiting for fix.

**Comment by masives** [comment] 2022-12-08 14:31
I noticed also an issue with my application that imports npm package that exporst chakra theme. On version 2.3.4 everything works correctly while on 2.3.5 it suddenly stops styling my imported components because it's initiating `@emotion/react` more then once. `@emotion/react` is peer dependency in my npm package so it's not using multiple versions.

The weird thing is that it only breaks on dev, using `vite build` make app work properly.

It leads to reverse of "it works for me" - it only works properly on prod builds but not on dev. 

Unfortunately I cannot share code since it's a business project.

**Comment by paradox37** [comment] 2022-12-20 15:45
I was just about to report a bug that @masives mentioned. Here is the reproduction repo: https://github.com/paradox37/monorepo

Exactly same issue as @masives described, I get this in console:
`You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.`

Going back to 2.3.4 and issue is not present.

**Closed** 2022-12-23 17:54 UTC

**Comment by paradox37** [comment] 2022-12-28 16:10
@segunadebayo This is still not working properly? Do I need to open a new issue? Even with 2.4.5, I still see an error I posted in my previous message, and CSS is not applied.
