### ISSUE TITLE
Add a prop to change the color mode key in local storage

### ISSUE THREAD

**Issue by hrishikeshpaul** [chakra-ui/chakra-ui#5554] opened 2022-02-09 18:33 UTC
### Description

The way Chakra persists the color mode in an application is by storing it in the browser's local storage under the key name `chakra-ui-color-mode`. It would be great if we could pass a prop to the `ColorModeScript` component to give a custom key name for storing the color mode.

### Problem Statement/Justification

Adding more customizations can help in really personalizing the application. Since the prefix for css variables can be passed as a prop, I feel like changing the color mode key name in the persistent storage can be great addition too. 

### Proposed Solution or API

Add a property to the `ColorModeScriptProps` interface.

```ts
interface ColorModeScriptProps {
  initialColorMode?: ConfigColorMode;
  nonce?: string;
  storageKeyName?: string;
}
```

Not sure if the name `storageKeyName` is the most appropriate, but that is just the idea.

### Additional Information

Image of where/how Chakra stores the color mode in the browser.

<img width="481" alt="chakra-ui-color-mode" src="https://user-images.githubusercontent.com/22999894/153266552-eb671ba1-40c8-4cb0-b009-120d8f428aed.png">

Additionally, I'd love to make a contribution if this approved!

**Comment by JClackett** [comment] 2022-02-10 12:49
Would love this, as working on a lot of projects with chakra makes this really needed in development. Obviously in production the key is scoped to the domain...

**Comment by hrishikeshpaul** [comment] 2022-02-10 21:18
@TimKolberger think thats great! In the future if something else also has to use the localStorage, it'll be useful to have it prefixed. The only downside I can think about is if someone would want to have a custom name for the localStorage key, instead of just a prefix.

**Comment by takethefake** [comment] 2022-03-05 13:07
I took a look at this and found it quite hard to create an elegant solution for ColorMode and the localstorage key.

The Problem ist. `StorageManager` which is used in `ColorMode` can be initiated outside of the chakra scope. that's why we can't call the theme config in `localStorageManager` to get the `localStorage-Prefix` 

we could change the type of `localStorageManager` from an` object` to a `function`, which accepts a `prefix` and then initiate the `localStorageManager` in   `ColorModeProvider` with the prefix which is defined in the theme.

All in all I'm not to happy with this chang, since it is a breaking change for the API which isn't worth the tradeoff for now, why I would like to close this issue for now.

What do you think @TimKolberger ?

**Comment by TimKolberger** [comment] 2022-03-07 22:55
Uff, sounds heavy. Thank you for the investigation @takethefake!

Since we allow a custom localStorageManager isn't it already possible to define a custom key?

I just found in a quick search that the ColorModeScript has a hardcoded reference to it. Could allowing this to be changed by the user provide full external control?

This would not make it configurable in the theme, but has the same effect.

**Comment by JClackett** [comment] 2022-04-16 09:03
Don't think this should be stale, am still running into scenarios where I have to clear my cookies to reset the color mode in dev

**Comment by segunadebayo** [comment] 2022-05-17 04:05
We now provide a way to customize the storage keys.

- Use the `createLocalStorageManager` or `createCookieStorageManager` to create a new storage for the color mode
- Pass the new manager to the `ChakraProvider`
- If you use `ColorModeScript`, pass the `storageKey` prop and set it to the key that matches the step above

```jsx
const manager = createLocalStorageManager("my-key")

// in root
<ChakraProvider  colorModeManager={manager} />

// in script
<ColorModeScript storageKey="my-key" />
```

**Closed** 2022-05-17 08:34 UTC
Labels: Type: Feature 🚀, Topic: Color Mode 🌓
