### ISSUE TITLE
Chakra-ui hover doesn't work for Box

### ISSUE THREAD

**Issue by mike-fam** [chakra-ui/chakra-ui#2971] opened 2021-01-07 09:24 UTC
# 🐛 Bug report
Passing a value for the `_hover` prop of a `Box` component doesn't do anything when the Box is hovered on.

## 💥 Steps to reproduce
Have this component.
```JSX
<Box
  width="200px"
  height="200px"
  background="tomato"
  _hover={{
    background: "teal"
  }}
>
  hi
</Box>
```
## 💻 Link to reproduction
[Code Sandbox](https://codesandbox.io/s/chakra-box-hover-fhnrx?file=/src/App.js)

## 🧐 Expected behavior
I think the Box component in the example above should change its background color whenever I hover the mouse on?

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.1.2       |
| Browser          |       Chrome and Firefox     |
| Operating System |     MacOs       |

**Comment by TimKolberger** [comment] 2021-01-07 20:12
`teal` refers to a color palette in chakra UI. Try `teal.500`. See https://chakra-ui.com/docs/theming/theme for an overview of all color palettes in the default theme.

Closing this because it is not a bug in chakra UI.

**Closed by TimKolberger** 2021-01-07 20:12 UTC
