### ISSUE TITLE
`disabled` prop does not work for `MenuItem` despite the type allowing it

### ISSUE THREAD

**Issue by RunDevelopment** [chakra-ui/chakra-ui#7260] opened 2023-01-18 21:58 UTC
### Description

The type for `MenuItem` allows both the `disabled` and `isDisabled` props, but only `isDisabled` works. `disabled` will be silently ignored with no warning whatsoever. This is a regression from #5296.

Please fix this by either changing the type so `disabled` is no longer a prop of `MenuItem` or making it so that `disabled` works.

The cause of the problem seems to be that the `MenuItemProps` (which do omit `disabled`) are merged with `React.ComponentProps<"button">` (which includes `disabled`) in `ComponentWithAs`.

### Chakra UI Version

2.3.5

**Comment by Ragunanthan-Eleviant** [comment] 2023-01-19 07:55
you can use isDisabled props for now.

**Comment by segunadebayo** [comment] 2023-04-24 20:52
Sort of duplicate of #7269

Please use `isDisabled` for now.

**Closed by segunadebayo** 2023-04-24 20:52 UTC
