### ISSUE TITLE
Chakra UI doesn't work with Next.js 13

### ISSUE THREAD

**Issue by ivanovserge** [chakra-ui/chakra-ui#7166] opened 2022-12-26 17:47 UTC
### Description

When I try to launch my app I see Next.js error:

SyntaxError: Named export 'cancelSync' not found. The requested module 'framesync' is a CommonJS module, which may not support all module.exports as named exports.

### Link to Reproduction

https://codesandbox.io/p/sandbox/divine-http-0zb56h

### Chakra UI Version

2.4.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by raghavlakhanpal** [comment] 2022-12-26 19:41
same issue

**Comment by prabhjotsinghchadha** [comment] 2022-12-26 20:01
I am getting the same issue as well

**Comment by kgilliam125** [comment] 2022-12-26 20:32
FYI thread with the same issue at https://github.com/chakra-ui/chakra-ui/issues/7167 . Has a little more info

**Comment by bibakroy** [comment] 2022-12-27 09:17
I solved this issue. Just changed the versions as it is below:

`yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`

You can try it. Will definitely work.

**Comment by kamilsk** [comment] 2022-12-27 10:24
@bibakroy it's not a solution, it's a workaround. another workaround is to make `git checkout package-lock.json <sha1>`. the root cause isn't solved anyway.

**Comment by guilhermeguain** [comment] 2022-12-27 11:35
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.

Dont work for me, still with error.

**Comment by Samandcode** [comment] 2022-12-27 21:18
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.

Didn't work for me

**Comment by guilhermeguain** [comment] 2022-12-27 21:28
> > I faced this issue and solved it. Just changed the versions as it is below:
> > `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> > You can try it. Will definitely work.
> 
> Didn't work for me

Oh worked this time. Thanks

**Comment by shinebayar-g** [comment] 2022-12-27 21:47
It's a duplicate of https://github.com/chakra-ui/chakra-ui/issues/7170

**Comment by itsbrex** [comment] 2022-12-28 05:40
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.

Chiming in to say this worked for me as well! 🙏💪

**Comment by 0xkeivin** [comment] 2022-12-28 06:54
> 

Confirmed this works. thank you !

**Comment by 0xkeivin** [comment] 2022-12-28 06:55
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.


Confirmed this works. thank you !

**Comment by st3fus** [comment] 2022-12-28 14:34
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.

Still have the issue...

**Comment by sanyam2301** [comment] 2022-12-28 18:31
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.

This Worked for me as well 🙏👌

**Comment by Samandcode** [comment] 2022-12-28 19:49
> > I faced this issue and solved it. Just changed the versions as it is below:
> > `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> > You can try it. Will definitely work.
> 
> Didn't work for me

Works now 

Thank you very much

**Comment by nirajpdn** [comment] 2022-12-29 02:03
> npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1

It is still not working in vercel.

**Comment by conceptofmind** [comment] 2022-12-29 04:06
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.

This worked for me as well.

**Comment by segunadebayo** [comment] 2022-12-29 21:59
This issue happened due to our recent move to `.mjs` file extensions for better ESM detection. Some of our internal dependencies did not fully support ESM.

I've gone ahead to fix most of the ESM/CJS-related errors. I just published a new version.

If, after upgrading and the problem still exists in your application, please open a new issue, and we'll look into it.

**Closed by segunadebayo** 2022-12-29 21:59 UTC
Labels: Priority: High 🚨, Topic: Next.js ▲

**Comment by Tolu-Mals** [comment] 2022-12-30 15:55
> yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1

Works for me now, thank you!

**Comment by Tolu-Mals** [comment] 2022-12-30 15:55
> This issue happened due to our recent move to `.mjs` file extensions for better ESM detection. Some of our internal dependencies did not fully support ESM.
> 
> I've gone ahead to fix most of the ESM/CJS-related errors. I just published a new version.
> 
> If, after upgrading and the problem still exists in your application, please open a new issue, and we'll look into it.

Works for me now, thank you!

**Comment by narthkings** [comment] 2023-01-02 13:16
i think this issue still persists
<img width="1021" alt="Screen Shot 2023-01-02 at 12 53 49 PM" src="https://user-images.githubusercontent.com/25045543/210236336-a49e8435-579c-42a6-ab61-f65e3dbe066a.png">
@segunadebayo

**Comment by amirhoseinsalehi** [comment] 2023-11-28 16:38
I found a solution that worked for me, it will help most of you I guess.
the root cause of this issue is about next13 and chakra that doesn't support server-side in advance!
anyway, I created a file for Chakra Provider solely and imported it as a lazy component and it fixed my issue :

<img width="589" alt="Screen Shot 2023-11-28 at 8 08 37 PM" src="https://github.com/chakra-ui/chakra-ui/assets/32030546/23e1b5a1-da85-4ee1-8fe4-b7d57e66a3f2">

<img width="646" alt="Screen Shot 2023-11-28 at 8 07 40 PM" src="https://github.com/chakra-ui/chakra-ui/assets/32030546/d982c080-fbdf-4738-b39e-711242c94a88">
)
