### ISSUE TITLE
[Theme] gatsby-plugin-chakra-ui

### ISSUE THREAD

**Issue by jhonaikerf** [chakra-ui/chakra-ui#425] opened 2020-02-20 00:41 UTC
I am using the plugin with gatsby-starter-blog, following the documentation with src / gatsby-plugin-chakra-ui / theme.js
And the file is ignored.

**Comment by trevorblades** [comment] 2020-02-22 19:54
This is a duplicate of #347. There's some more info in that issue about the cause of this error, and it will be fixed when #362 gets merged/released.

**Closed** 2020-02-24 15:54 UTC

**Comment by uselessdev** [comment] 2020-07-17 23:46
Hi, @trevorblades I'm getting this same error here and I don't know if I've messed up some config or is the same bug.
