### ISSUE TITLE
[Progress] color attribute adds an additional ".500"

### ISSUE THREAD

**Issue by poroia** [chakra-ui/chakra-ui#590] opened 2020-04-08 11:11 UTC
**Describe the bug**
The color property appears to add an extra ".500" no matter what for the Progress component, so the color property breaks and no color is shown.

![image](https://user-images.githubusercontent.com/36049897/78777350-3d3c6680-794e-11ea-851a-b7b25461bfb7.png)
![image](https://user-images.githubusercontent.com/36049897/78777406-4fb6a000-794e-11ea-9a5e-835c8503593d.png)
![image](https://user-images.githubusercontent.com/36049897/78777432-5e04bc00-794e-11ea-8135-0e9c06408bac.png)

**Expected Behavior**
Should properly display theme colors. Other components work but it appears that this one doesn't.

**To Reproduce**
Create progress component: `<Progress color="gray.700" />`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80

**Additional context**
React 16.12.0

Just started using the library, love it so far!

**Comment by poroia** [comment] 2020-04-08 11:13
Just noticed that someone opened an issue with the exact same problem: https://github.com/chakra-ui/chakra-ui/issues/569. My bad

**Comment by poroia** [comment] 2020-04-08 11:31
After some additional research, I noticed that the values were hardcoded in for the purposes of `useColorMode()`. Should an option be added to override the usage of color mode for this component so that normal theming can be used?

**Comment by gnyani** [comment] 2020-04-12 10:45
Hi, 

I just had a quick look into this and from what I see this is the current behavior of all chakra elements including Button, CircularProgress, etc and the reason for hardcoding `.500` a suffix is to support two color modes i.e., `Light mode` and `Dark mode`.  

I see two things which need fixing here:
1. Maybe I think all the components should support passing two color props `lightThemeColor` and `darkThemeColor` and if only one of them is passed, we should use the current logic. 
2. In some components `variantColor` prop is used and in some places its just `color`. 

These are just my ideas and I think whoever has more insights can suggest a better idea, once the implementation is finalized, I can open a PR to fix this. 

Cheers !!.

**Comment by segunadebayo** [comment] 2020-04-15 06:59
Thanks for looking into this @gnyani.

I'll close this for now considering it's a duplicate of the referenced issue #569.

Also, we've solved this in preparation for the next release. The solution we're going with is to allow users to have full control over the styling.

**Closed by segunadebayo** 2020-04-15 06:59 UTC
