### ISSUE TITLE
`collection` type inference is lost when using SelectRoot comp from snippet

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#9032] opened 2024-10-29 18:24 UTC
### Description

When I use the `SelectRoot` component from the select snippet, I expect it to properly infer the type of `collection` prop. But it resolves to any. Most likely caused by the `forwardRef` func.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-8qckke?file=README.md

### Steps to reproduce

1. Hover mouse onto `collection` prop, it shows `any`

### Chakra UI Version

3.0.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by baptisteArno** [comment] 2024-10-29 18:30
To fix it:

```tsx
interface SelectRootRefType
  extends React.FC<ChakraSelect.RootProps<CollectionItem>> {
  <T extends CollectionItem>(
    props: ChakraSelect.RootProps<T>,
  ): ReturnType<React.FC<ChakraSelect.RootProps<T>>>;
}

export const SelectRoot: SelectRootRefType = forwardRef(function SelectRoot(
  props,
  ref: React.Ref<HTMLDivElement>,
) {
  return (
    <ChakraSelect.Root
      {...props}
      ref={ref}
      positioning={{ sameWidth: true, ...props.positioning }}
    />
  );
});
```

**Comment by Ploppy3** [comment] 2024-11-04 12:53
Similar UNSOLVED problem with JSDOC:

So solution should be to force the type like this:

```jsx
export const AccordionItemTrigger = forwardRef(
  /** @param {import("@chakra-ui/react").AccordionItemTriggerProps} props */
  function AccordionItemTrigger(props, ref) {
    // ...
  }
);
```

The problem is that the type definition doesn't work.

`accordion.d.ts`

![image](https://github.com/user-attachments/assets/dd0f3a84-b967-4656-92fd-c0ddfd4324be)

Because this `import { Accordion as ArkAccordion } from "@ark-ui/react/accordion";` can't be resolved by the Typescript Compiler.

**Comment by Ploppy3** [comment] 2024-11-04 14:03
The problem seems to be that the import:

`import { Accordion as ArkAccordion } from "@ark-ui/react/accordion";`

Should be instead:

`import { Accordion as ArkAccordion } from "@ark-ui/react";`

**Comment by segunadebayo** [comment] 2024-11-04 20:16
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Closed by segunadebayo** 2024-11-04 20:16 UTC
