### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [chakra-ui/chakra-ui#5659] opened 2022-02-25 19:54 UTC
### Description

When customizing input border color from theme configs, it doesn't reflect any change

### Link to Reproduction

https://stackblitz.com/edit/nextjs-the8yv?file=pages/_app.js

### Chakra UI Version

1.8.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TimKolberger** [comment] 2022-02-26 11:12
I updated the custom theme in the stackblitz example to this:

```ts
const customTheme = extendTheme({
  components: {
    Input: {
      variants: { // notice the trailing 's'
        outline: {
          field: { // notice the added field property
            borderColor: 'purple.500',
          },
        },
      },
    },
  },
});
```

It is currently hard to get the theming styles right, because of missing types.
Providing better typings for the theme has a high priority right now, this will get better over time.
My approach is to go to have a look at the default theme styles.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/16899513/155840988-ed9c5136-ac70-4b43-b4d4-3e6338167119.png">

Closing this as it is not a bug.

**Closed by TimKolberger** 2022-02-26 11:12 UTC
Labels: Type: Bug 🐛, needs triage
