### ISSUE TITLE
The CSSObject type is missing custom pseudo selectors included in the theme

### ISSUE THREAD

**Issue by csandman** [chakra-ui/chakra-ui#6263] opened 2022-07-01 22:05 UTC
### Description

When trying to access the `_disabled` or `_focus` pseudo-selectors from a Chakra theme object, I'm getting TypeScript errors.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-invalid-cssobject-0yto3k

### Steps to reproduce

If you look at the code in the linked sandbox, you can see that an error is being thrown when trying to access the `_focus` key from the CSSObject returned from `useMultiStyleConfig`.  However, this key does exist as you can see by the `console.log` and the object shown in the resulting HTML.

I believe the `CSSObject` type needs to be extended to allow the custom psuedo selectors created in this package to be accessed.  If not, the returned value from `useMultiStyleConfig` and `useStyleConfig` should be an extended interface from `CSSObject`.

### Chakra UI Version

2.2.1 but this has been the case for as long as I can remember

### Browser

I'm seeing this error in VSCode and CodeSandbox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The resulting error:

```
Property '_focus' does not exist on type 'CSSObject'.
  Property '_focus' does not exist on type 'CSSWithMultiValues'.
```

**Comment by TylerAPfledderer** [comment] 2022-07-01 22:24
Related to #6261

**Comment by csandman** [comment] 2022-08-01 20:05
This is still an issue as far as Im aware

**Comment by segunadebayo** [comment] 2023-04-24 21:56
Duplicate of https://github.com/chakra-ui/chakra-ui/issues/6261

**Closed by segunadebayo** 2023-04-24 21:56 UTC
Labels: Topic: TypeScript 🤠, Topic: Styled System 💅🏻
