### ISSUE TITLE
atribute triggers to <MenuButton>

### ISSUE THREAD

**Issue by cindRoberta** [chakra-ui/chakra-ui#2947] opened 2021-01-05 00:19 UTC
# 🚀 Feature request

> atribute triggers to activate \<MenuButton\>

## ✅ Proposed solution or API

> <MenuButton triggers=["click", "mouveover"]>\</MenuButton\>

**Comment by dodas** [comment] 2021-01-05 01:12
Closing as duplicate of #1380.
Please feel free to continue discussion there.

**Closed by dodas** 2021-01-05 01:12 UTC
