### ISSUE TITLE
[Menu] Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by sadi304** [chakra-ui/chakra-ui#1319] opened 2020-07-20 15:20 UTC
```
  useEffect(function () {
    if (activeIndex !== -1) {
      -> focusableItems.current[activeIndex] && focusableItems.current[activeIndex].focus();
      updateTabIndex(activeIndex);
    }

    if (activeIndex === -1 && !_isOpen && wasPreviouslyOpen) {
      buttonRef.current && buttonRef.current.focus();
    }

    if (activeIndex === -1 && _isOpen) {
      menuRef.current && menuRef.current.focus();
    }
  }, [activeIndex, _isOpen, buttonRef, menuRef, wasPreviouslyOpen]);
```

Debugger shows `focusableItems.current` remains null at some points when clicking on the menu items.

`@chakra-ui/core": "0.8.0"`

**Comment by segunadebayo** [comment] 2020-07-21 15:49
This is a duplicate of #653. We've resolved this in the upcoming v1 release.

Kindly permit me to close this. As walk-around, try to avoid rendering empty menu items within the list.

Cheers

**Closed by segunadebayo** 2020-07-21 15:49 UTC
