### ISSUE TITLE
Supplying a variant to Drawer will not change styles

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#3760] opened 2021-04-07 14:15 UTC
When I am trying to override the defaults styles of the Drawer component via a variant the styles I have supplied are not coming through:
https://codesandbox.io/s/no-margin-chakra-forked-f21mj?file=/src/App.tsx

```
export const Drawer = {
  variants: {
    mob: {
      width: "80vw"
    }
  }
};
import { extendTheme } from "@chakra-ui/react";

const appTheme = {
  components: {
    Drawer
  }
};


const theme = extendTheme(appTheme);

    <ChakraProvider resetCSS theme={theme}>
      <Drawer
        isOpen={true}
        onClose={() => {}}
        motionPreset="slideInRight"
        variant="mob"
      >

```

We should see `width: 80vw` on the component rendered:
![image](https://user-images.githubusercontent.com/1344898/113881149-12c8f780-97b4-11eb-86c0-d5d36eb5cd38.png)

Charka UI: 1.3.3

**Comment by hutber** [comment] 2021-04-09 14:44
Is it possible that the Drawer should not accept a variant?

**Comment by TimKolberger** [comment] 2021-04-09 21:07
The Drawer is a [multipart component](https://chakra-ui.com/docs/theming/advanced#multipart-or-composite-component). 

In your example you are setting the width, so I think it appropriate to add an additional size, not a variant:

```js
export const Drawer = {
  sizes: {
    mob: {
      drawer: {
        width: "80vw",
      },
    },
  },
};
```

```tsx
<Drawer size="mob" />
```

Please [see Drawer default theme code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/drawer.ts#L66)

Closing this issue because it is not a bug.

**Closed by TimKolberger** 2021-04-09 21:07 UTC
