### ISSUE TITLE
Investigate TypeScript intellisense slowness

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1387] opened 2020-07-24 20:11 UTC
Multiple users have reported TypeScript intellisense slowness for Chakra 1.0. We definitely want to make sure the DX for Chakra is excellent, so if this affecting you, please respond with the following information:

- Project type (next/CRA/etc.)
- Chakra version
- OS version
- IDE+version
- TypeScript version
- Paste a copy of your `tsconfig.json`

**Comment by PierreAndreis** [comment] 2020-07-24 20:23
**Project type** 
One on a custom webpack in a mono repo and another running parcel 2.0 
**Chakra version**
1.0.next6
**OS version**
macOS High Sierra (Hackintosh with i7)
macOS Catalina (Macbook 15" Late 2015 with i7)
**IDE+version**
vscode 1.47.2
**TS Version**
3.9.6

**Comment by jordangarcia** [comment] 2020-07-24 20:33
**Project type**
NextJS /w Chakra and a mono repo using only react.

**Chakra version**
1.0.next6

**OS version**
macOS Catalina 10.15.6 (Macbook Pro 16" 2019 - i9, 32gb ram)

**IDE+version**
vscode 1.47.2

**TS Version**
3.9.5

**Comment by pedroleinar** [comment] 2020-07-24 20:54
Project type
One on a custom webpack in a mono repo
Chakra version
1.0.next6
OS version
Ubuntu 20.04 LTS (i5 4690 4x4 1600mhz SSD 500mb/s)
IDE+version
vscode 1.47.2
TS Version
3.9.6

**Comment by pedroleinar** [comment] 2020-07-24 20:56
**Project type**
Custom webpack in a mono repo

**Chakra version**
1.0.next6

**OS version**
Ubuntu 20.04 LTS (i5 4690 4x4 1600mhz SSD 500mb/s)

**IDE+version**
vscode 1.47.2

**TS Version**
3.9.6

**Comment by laurentlucian** [comment] 2020-07-24 20:59
**Project type**
Parcel 2.0.0-beta.1

**Chakra version**
1.0.next6

**OS version**
macOS Catalina (Macbook Pro 15" 2015, i7, 16GB)
Ubuntu 18.04 LTS (Ryzen 5 3600, 32GB 3200mhz)

**IDE+version**
vscode 1.47.2

**TS Version**
3.9.7

**TS Config**
```
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "include": ["src", "src/@types/index.d.ts"]
}
```

**Comment by zeehjr** [comment] 2020-07-24 21:01
**Project type**
CRA with typescript template

**Chakra version**
1.0.next6

**OS version**
Ubuntu 20.04 LTS (i5 7200U, 2x8GB RAM 1333mhz)

**IDE+version**
vscode 1.47.2

**TS Version**
3.9.7

**Comment by PTaylour** [comment] 2020-07-25 16:17
**Project type**
Gatsby /w Chakra

**Chakra version**
1.0.next6

**OS version**
macOS Catalina 10.15.6 (Macbook Pro 16" 2019 - i9, 32gb ram)

**IDE+version**
vscode 1.47.2

**TS Version**
typescript@3.9.7

**tsconfig.json**
```
{
  "compilerOptions": {
    "noEmit": true,
    "strict": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react",
    "resolveJsonModule": true
  }
}
```

I'm using `"@typescript-eslint/parser": "^2.26.0",` with

```
{
  "root": true,
  "env": { "browser": true },
  "parserOptions": { "project": "./tsconfig.json" },
  "extends": [
    "airbnb-typescript",
    "airbnb/hooks",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:jest/recommended",
    "plugin:testing-library/recommended",
    "plugin:testing-library/react",
    "prettier",
    "prettier/@typescript-eslint",
    "prettier/react"
  ],
  "plugins": ["simple-import-sort"],

  "rules": {
    // Auto-sort imports
    "sort-imports": "off",
    "import/order": "off",
    "simple-import-sort/sort": "error",

    // Using a type system makes it safe enough to spread props
    "react/jsx-props-no-spreading": "off",

    // Save writing a lot of JSX.Element
    "@typescript-eslint/explicit-function-return-type": "off",

    // allow importing devDeps in tests
    "import/no-extraneous-dependencies": ["error", { "devDependencies": true }],

    "no-underscore-dangle": "off"
  }
}
```

**Comment by ljosberinn** [comment] 2020-07-25 16:42
@PTaylour are you able to upgrade `@typescript-eslint/parser`? 2.26 is heavily outdated, it's on `3.7.0`.

This is my tsconfig in a nextjs repo - I do **not** see any issues, maybe this helps:
```js
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es6",
    "allowSyntheticDefaultImports": true
  },
  "exclude": ["node_modules"],
  "include": ["**/*.ts", "**/*.tsx"]
}
```
using [this eslint config (everything on latest).](https://github.com/ljosberinn/eslint-config-galex/blob/master/package.json#L32).

OS version
Win10 Beta Branch, Ryzen 5 3600 6 Core, 3.6GHz; 16GB Ram
(fwiw, I had no issues on my old 6 year old pc either, only recently upgraded)

IDE+version
vscode 1.48.0

TS Version
typescript@4.0.0-dev.20200725

**Comment by kentongray** [comment] 2020-07-25 18:43
Not sure if the negative is helpful but FYI not seeing any issues on Jetbrains IDE (IntelliJ/Rider) with Chakra 1.0.0-next6.

**Comment by with-heart** [comment] 2020-07-25 19:58
@ljosberinn Could you push that repo somewhere? I used your `tsconfig.json` in a CRA project with matching VSCode and TS versions with no extensions and I still noticed lag with intellisense loading.

**Comment by with-heart** [comment] 2020-07-25 19:58
@kentongray Good to know

**Comment by ljosberinn** [comment] 2020-07-25 20:38
@with-heart https://github.com/ljosberinn/personal-react-boilerplate it's this one. What qualifies as laggy? It has a delay for ~1s maybe for me.

**Comment by with-heart** [comment] 2020-07-25 21:07
@ljosberinn It seemed to vary but I'd say 1s-5s depending. The intellisense dropdown is populated immediately, but it takes that amount of time for it to load the tooltip information and to be able to auto-import by selecting that option.

**Comment by PierreAndreis** [comment] 2020-07-26 06:34
I think this issue might more associated to vscode and its intellisense as the type checking in my terminal is pretty fast. The only problem is intellisense it is pretty slow.

**Comment by PTaylour** [comment] 2020-07-27 08:31
@ljosberinn I've upgraded `@typescript-eslint/parser` and done a clean install. It appears to be a lot faster (~1s-2s to populate the tooltip and be able to auto-import), whereas before it was much slower.

**Comment by ljosberinn** [comment] 2020-07-27 08:43
very interesting, thanks!

**Comment by with-heart** [comment] 2020-07-27 12:48
@PierreAndreis I think it's something relating to the ts language server. I'm running into the same issue with `nvim`  using `coc.vim`.

Doing more investigation into this issue today.

**Comment by remorses** [comment] 2020-07-27 13:06
The typescript intellisense is based on the typescript language server that tsc itself uses, so we can use the tsc compile time as a metric of intellisense speed.

Looking at the code there are a lot of types that could be optimized 
- instead of using `PropsOf` to declare the components props type we should declare the props as a concrete type, this way tsc has to evaluate less code
```tsx
// instead of this
export type AlertTitleProps = PropsOf<typeof chakra.div>

// do this
export const AlertTitle: FC<AlertTitleProps> = ...
```
- remove the use of `PropsOf` in `ChakraComponent` and other relative types

**Comment by ljosberinn** [comment] 2020-07-27 14:32
@remorses Thanks, I planned on looking through the types this evening anyways now that we're closer to a stable API.

On a sidenote, `React.FC` has plenty of reasons not to be used anymore, see https://github.com/facebook/create-react-app/pull/8177 for this. :)

**Comment by ganeshkrishnasharma** [comment] 2020-07-27 16:44
Yes, this is definitely an issue. I just finished upgrading to version `1.0.0-rc.0` - The slowness in type checking , server hot reloading is clearly visible. Please look at this issue on priority. I have the latest macbook pro 16 inch with 2.3 GHz 8-Core Intel Core i9. @segunadebayo @with-heart 

1. Project type : `Create React App with typescript template`
2. Chakra version : `1.0.0-rc.0`
3. OS version : `macOS Catalina v 10.15.6` - `2.3 GHz 8-Core Intel Core i9/ 16GB RAM`
4. IDE+version : `VS Code Version: 1.47.2`
5. TypeScript version : `3.9.3`
6. copy of tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext",
      "webworker",
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "noImplicitAny": false
  },
  "include": [
    "src"
  ]
}
```

**Comment by ljosberinn** [comment] 2020-07-27 20:31
create-react-app uses a heavily outdated @typescript-eslint parser which is probably guilty here. although eslint-config-react-app has `^3.0.0` in its package.json, what actually ends up in a fresh CRA project is `2.24.0`.

**Comment by kentongray** [comment] 2020-07-27 23:24
> @kentongray Good to know. What OS?

macOS Catalina

**Comment by with-heart** [comment] 2020-07-28 23:48
Some related discussion today in Discord: https://discordapp.com/channels/660863154703695893/724006907634778132/737690655601721367

**Comment by ganeshkrishnasharma** [comment] 2020-07-29 14:07
@with-heart @ljosberinn , actually the slowness is observed only after upgrading to chakra-ui v1. With chakra-ui v 0.8.0 , it was very fast and smooth :)

**Comment by with-heart** [comment] 2020-07-29 19:17
@ganeshkrishnasharma Yeap, this is definitely related to the 1.0 rewrite and not previous versions

**Comment by segunadebayo** [comment] 2020-08-06 11:40
We've made good improvements to the types of all components. Expect the TypeScript IntelliSense to be fast after the next `rc` release.

We've also moved most component prop definition from `type` to `interface` which is a massive win when it comes to speed of resolving types. All these with the `as` prop still working well 🥳

Thanks to @ljosberinn for leading the effort.

**Closed by segunadebayo** 2020-08-06 11:40 UTC
Labels: Topic: TypeScript 🤠

**Comment by with-heart** [comment] 2020-08-07 04:37
@ljosberinn saving the day!

**Comment by ljosberinn** [comment] 2020-08-07 07:12
glad its resolved but @santialbo did the heavy lifting here :)

**Comment by remorses** [comment] 2020-08-09 16:47
Intellisense is still slow, i did some investigation and the problem is the `ComponentWithAs` type, i tried tweaking that types removing the `As` generic argument and everything becomes super smooth, making intellisense instantaneous

The `as` generic argument delays intellisense even if you son't use it, the delay is about `400ms` average for me

I think we should remove the as generic and instead encourage people to use the new `chakra.tag` approach

The as approach could be added maybe in the future, we shouldn't add it in the `1.0` release or it will be impossible to remove (because of breaking changes) and it will make everyone experience worse

I opened #1582 to add this to the v1 checklist
