### ISSUE TITLE
Animation lag on iphone

### ISSUE THREAD

**Issue by Sotatek-HoangNguyen7** [chakra-ui/chakra-ui#7668] opened 2023-05-18 07:34 UTC
### Description

https://github.com/chakra-ui/chakra-ui/assets/96707915/709b5e4f-cfe4-4753-918e-3caf1cb05a69

IOS: 16.3.1 | Safari 

### Link to Reproduction

https://chakra-ui.com/docs/components/drawer

### Steps to reproduce

drawer, Transitions, Accordion component

### Chakra UI Version

2.6.1

### Browser

 safari, chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2023-05-28 19:18
Duplicate of #6131

**Closed by segunadebayo** 2023-05-28 19:18 UTC
