### ISSUE TITLE
[NumberInput] Not able to submit form with decimal value

### ISSUE THREAD

**Issue by kennethacohen** [chakra-ui/chakra-ui#1961] opened 2020-09-04 19:13 UTC
# Bug report

## Describe the bug
I am attempting to use the `NumberInput` component in a form to represent price (with cents). Upon form submission, I keep hitting the. HTML5 validation

## To reproduce
Repro here: https://codesandbox.io/s/naughty-khorana-bfypu?file=/src/App.tsx:371-372

Submitting the for with whole numbers is fine, but html error is thrown when submitting decimals

## Expected behavior
I believe we should be able to submit forms with decimals using the NumberInput

## System information

- Browser: Chrome
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]

**Comment by with-heart** [comment] 2020-09-04 19:58
The issue is here: https://github.com/chakra-ui/chakra-ui/blob/acc6e161518e77873023106d13126ddce45f4a8e/packages/number-input/src/use-number-input.ts#L333-L334

We need to think about how to handle this correctly. Here's my thinking:

- by default, `NumberInput` only validates whole numbers
- decimal mode can be enabled by
	- a specific flag prop (`isDecimal`?)
	- and/or checking `step` prop and if it's a decimal number, automatically switch to decimal mode
- if decimal mode:
	- switch `inputMode` to `"decimal"`
	- switch `pattern` to `"[0-9]*(.[0-9]+)?"` which validates for decimals
		- whole numbers are valid
		- `123.123` is valid
		- `0.123` is valid
		- `.123` is valid

**Comment by kennethacohen** [comment] 2020-09-04 22:33
Would maybe be nice to just expose the pattern prop to allow for customization?

Any recommendations for a temporary workaround?

**Comment by segunadebayo** [comment] 2020-09-06 08:51
@with-heart, I agree with your recommendations.

I think we should default to decimal though, given that a user might type decimals directly regardless of the `step` prop. The `step` prop only applies when. using the Up/Down keys or clicking the stepper buttons.

The `pattern` is the main cause of this issue not really `inputMode`. I'll update it as suggested, and also allow the user to pass this via props.

**Comment by segunadebayo** [comment] 2020-09-06 09:04
@kennethacohen, I've just pushed a fix for this following my comments.

We'll release an update shortly.

**Closed by segunadebayo** 2020-09-06 09:04 UTC
Labels: Type: Bug 🐛
