### ISSUE TITLE
Why are there some very tiny borders around the Avatar?

### ISSUE THREAD

**Issue by geekskai** [chakra-ui/chakra-ui#4304] opened 2021-06-29 12:28 UTC
### Description

When I am using the Avatar component and refresh the page several times, there is a high probability that a very small border color will appear around the avatar. However, when I add a little style to the Avatar component, the small border above Disappeared!

### Link to Reproduction

https://codesandbox.io/s/condescending-bogdan-tuse5?file=/src/App.js

### Steps to reproduce

1. Enter the page to carefully observe whether there is a small frame, if it does not appear, refresh the page several times, if it still does not appear, refresh the codesendbox, so that it can be reproduced! It seems that this component of the official website also has this problem! You have to be very careful to see this subtle difference!

### Chakra UI Version

1.6.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/37830362/123796904-336a9e80-d918-11eb-819d-1436be882a6d.png)
Take a closer look at the border in the picture above. Are there any very subtle colors?

But if I refresh the page many times, this very subtle border may disappear. Look at the picture below. Does anyone know what the problem is? ?

![image](https://user-images.githubusercontent.com/37830362/123797033-5e54f280-d918-11eb-830b-8db032e9d802.png)

**Comment by Can-Chen** [comment] 2021-06-30 02:49
👀

**Comment by Can-Chen** [comment] 2021-06-30 02:52
![截屏2021-06-30 10 50 34](https://user-images.githubusercontent.com/50009783/123894599-04dcda00-d991-11eb-941f-71cac8087c8c.png)

avatar appear be similar to border

**Comment by jimboslicethat** [comment] 2021-07-15 18:17
I am seeing this issue as well. I am conditionally setting the background to transparent when src is present in the props as a temporary work around.

**Comment by anilanar** [comment] 2021-08-05 08:51
We are running visual regression tests using Chromatic and we get random avatar borders with random colors. Sometimes it appears like a mixed rainbow color, sometimes it doesn't exist. This looks like a rendering bug on Chromium perhaps.


See the image.

![image](https://user-images.githubusercontent.com/753736/128321195-82a92868-ef4c-4303-abc5-64ba0a0ed501.png)

I think it's caused by using `border-radius` for both the wrapper `span` and also for the `img`. I think the problem disappears by removing `border-radius`  from `img` and by adding `overflow: hidden` to the wrapper `span` but I didn't confirm this 100%.

**Comment by anilanar** [comment] 2021-08-06 11:47
I figured out the solution and also figured out why the border color is random:

It's caused by avatar fallback's background color!

Using `bg="transparent"` immediately fixes the issue but also breaks the fallback, obviously.

So `Avatar` component requires a little bit of refactoring to apply the background color only for the fallback and not for the actual image which breaks Chrome's rendering.

**Comment by geekskai** [comment] 2021-08-07 06:44
> I figured out the solution and also figured out why border color appears to be random:
> 
> It's caused by avatar fallback's background color!
> 
> Using `bg="transparent"` immediately fixes the issue but also breaks the fallback, obviously.
> 
> So `Avatar` component requires a little bit of refactoring to apply the background color only for the fallback and not for the actual image.
> 
> BTW, gotta get rid of the default bg color too, border-radius on images + bg color simply doesn't work well together it seems.
> 
> My workaround:
> 
> ```ts
> /**
>  * Workaround for chakra bug:https://github.com/chakra-ui/chakra-ui/issues/4304
>  * Temporarily disable initials/fallback by not passing name prop so that chromatic
>  * doesn't go nuts every PR.
>  * Use transparaent background to override the default gray background.
>  */
> export const Avatar = ({ src, size }: AvatarProps): JSX.Element => (
>   <ChakraAvatar
>     // name={name}
>     src={src}
>     size={size}
>     bg="transparent"
>   />
> );
> ```

**Comment by geekskai** [comment] 2021-08-07 06:47
> > I figured out the solution and also figured out why border color appears to be random:
> > It's caused by avatar fallback's background color!
> > Using `bg="transparent"` immediately fixes the issue but also breaks the fallback, obviously.
> > So `Avatar` component requires a little bit of refactoring to apply the background color only for the fallback and not for the actual image.
> > BTW, gotta get rid of the default bg color too, border-radius on images + bg color simply doesn't work well together it seems.
> > My workaround:
> > ```ts
> > /**
> >  * Workaround for chakra bug:https://github.com/chakra-ui/chakra-ui/issues/4304
> >  * Temporarily disable initials/fallback by not passing name prop so that chromatic
> >  * doesn't go nuts every PR.
> >  * Use transparaent background to override the default gray background.
> >  */
> > export const Avatar = ({ src, size }: AvatarProps): JSX.Element => (
> >   <ChakraAvatar
> >     // name={name}
> >     src={src}
> >     size={size}
> >     bg="transparent"
> >   />
> > );
> > ```

At the beginning, I tried you to do this, but when the name and src are not available, the default avatar should be online. If you follow your scheme, the default avatar will be completely transparent and nothing can be seen!

https://codesandbox.io/s/vigorous-rgb-qcxpy?file=/src/App.js:499-531

```
 <Avatar
   size="2xl"
   color="black"
   // The default avatar will be overwritten, and nothing will be seen!
   bgColor="transparent"
   // name="wisesa"
   // src="https://www.wisesa.dev/404"
  />

```

**Comment by anilanar** [comment] 2021-08-07 12:31
@geekskai

As I said, using `bg="transparent"` breaks the avatar fallback (name initials) and it probably breaks the default avatar too. Avatar component needs to be refactored to fully fix this issue.

**Comment by anubra266** [comment] 2021-11-10 09:51
cc @segunadebayo

**Comment by anilanar** [comment] 2022-01-19 21:36
A rough workaround until this is fixed:

```
import * as C from '@chakra-ui/react';
import { useEffect, useState } from 'react';

/**
 * Workaround for chakra bug:https://github.com/chakra-ui/chakra-ui/issues/4304
 */
export const Avatar = ({ src ...props }) => {
  const [hasError, setHasError] = useState(false);

  useEffect(() => {
    setHasError(false);
  }, [src]);

  return (
    <C.Avatar
      src={src}
      onError={() => setHasError(true)}
      bg={src && !hasError ? 'transparent' : undefined}
      {...props}
    />
  );
};
```

Basically this is what needs to be fixed in Avatar component: bg color needs to be removed if image was successfully loaded, because border radius + background color + image combination doesn't work across almost all browsers.

**Comment by anilanar** [comment] 2022-04-25 08:01
@segunadebayo This shouldn't be closed, can someone reopen?

**Comment by anilanar** [comment] 2022-06-12 16:56
ping ping not stale.

**Comment by anilanar** [comment] 2022-07-31 01:50
not state.

**Comment by Pagebakers** [comment] 2022-08-02 15:48
> A rough workaround until this is fixed:
> 
> ```js
> import * as C from '@chakra-ui/react';
> import { useEffect, useState } from 'react';
> 
> /**
>  * Workaround for chakra bug:https://github.com/chakra-ui/chakra-ui/issues/4304
>  */
> export const Avatar = ({ src ...props }) => {
>   const [hasError, setHasError] = useState(false);
> 
>   useEffect(() => {
>     setHasError(false);
>   }, [src]);
> 
>   return (
>     <C.Avatar
>       src={src}
>       onError={() => setHasError(true)}
>       bg={src && !hasError ? 'transparent' : undefined}
>       {...props}
>     />
>   );
> };
> ```
> 
> Basically this is what needs to be fixed in Avatar component: bg color needs to be removed if image was successfully loaded, because border radius + background color + image combination doesn't work across almost all browsers.

I was thinking about this approach as well. 👌

**Closed** 2022-09-19 16:41 UTC
Labels: Type: Bug 🐛, needs triage
