### ISSUE TITLE
custom breakpoints are buggy.

### ISSUE THREAD

**Issue by codekcv** [chakra-ui/chakra-ui#3907] opened 2021-04-24 14:13 UTC
# 🐛 Bug report

They are not working as intended. It is skipping certain breakpoints that are custom set.

## 💥 Steps to reproduce

1. Create boilerplate react app and install chakra UI
2. Create custom breakpoint function, use these values:
`const breakpoints = createBreakpoints({
  sm: "300px",
  md: "500px",
  lg: "700px",
  xl: "900px"
});`
3. Apply that breakpoint in ChakraProvider theme.
4. Try it out. it doesn't work

## 💻 Link to reproduction

CodeSandbox is also even more broken in this one. It doesn't even trigger any responsiveness when changing window width, no color are set.
https://codesandbox.io/s/zen-dan-fplmw?file=/pages/_app.js

## 🧐 Expected behavior

All breakpoints are used and working properly.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| nextjs | 10.1.3 |
| Chakra UI        |     1.5.2    |
| Browser          |    Chrome Version 90.0.4430.72        |
| Operating System |   archlinux-2021.04.01-x86_64 & kernel v5.11  |

## Screenshot.
It's using green background when it should be blue according to my breakpoints.
![Screenshot from 2021-04-24 20-55-55](https://user-images.githubusercontent.com/51011835/115961682-13021a80-a54a-11eb-9acc-496829621bc0.png)

## Whole code:
![Screenshot from 2021-04-24 22-14-36](https://user-images.githubusercontent.com/51011835/115961792-899f1800-a54a-11eb-9c48-94987294987c.png)

**Comment by with-heart** [comment] 2021-04-24 14:34
Closing as duplicate of #3042

**Closed by with-heart** 2021-04-24 14:34 UTC
