### ISSUE TITLE
Set width using this shortcut width={1/2} is no longer works 1.4.1

### ISSUE THREAD

**Issue by svspicious** [chakra-ui/chakra-ui#3673] opened 2021-03-26 08:46 UTC
# 🐛 Bug report

as mentioned here https://chakra-ui.com/docs/features/responsive-styles#under-the-hood
![image](https://user-images.githubusercontent.com/35674157/112604454-bcb99300-8e48-11eb-9a5e-53955d79a27c.png)

we can set width using this shortcut `w={1/2}` and it should be converted to `width="50%"` (it still works at v1.3.x). After upgrading to 1.4.1 it no longer works but instead its chagned to 0.125rem (?) and it ruined all my layout.
![image](https://user-images.githubusercontent.com/35674157/112604837-30f43680-8e49-11eb-9a85-afac1adcb3b6.png)

## 💥 Steps to reproduce

Set width using `1/2`, `1`, etc.
```jsx
<Box padding={4}>
  <Box w={1/2} height="40px" bg="tomato" />
  <Box w={1/2} height="40px" bg="green.300" />
</Box>
```

![image](https://user-images.githubusercontent.com/35674157/112605295-bbd53100-8e49-11eb-98aa-ba5b3f24b8d4.png)

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/agitated-paper-wqvni

## 🧐 Expected behavior

`w={1/2}` should be converted to `width="50%"` etc.

## 🧭 Possible Solution

maybe check constant definition for width value

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.4.1 |
| Browser          | Chrome latest |
| Operating System | Windows 10 latest |

## 📝 Additional information

![image](https://user-images.githubusercontent.com/35674157/112605763-3aca6980-8e4a-11eb-8406-5ebfce63915b.png)
should be like this
![image](https://user-images.githubusercontent.com/35674157/112605796-43bb3b00-8e4a-11eb-9cf2-31591f3e5983.png)

**Comment by segunadebayo** [comment] 2021-03-26 09:59
Duplicate of https://github.com/chakra-ui/chakra-ui/issues/3396.

Please check the recommendation there

**Closed by segunadebayo** 2021-03-26 09:59 UTC
