### ISSUE TITLE
TS2590: Expression produces a union type that is too complex to represent when on TS 5.0.3

### ISSUE THREAD

**Issue by bryanjswift** [chakra-ui/chakra-ui#7526] opened 2023-04-01 15:16 UTC
### Description

Simple components are producing `TS2590: Expression produces a union type that is too complex to represent` after updating `@chakra-ui/system` to 2.5.5 and `typescript` to 5.0.3. Here is a minimal case.

```ts
// index.tsx
import { Container } from '@chakra-ui/react';

const t = () => <Container />;
```

Still produces an error for me with this configuration.

```jsonc
// package.json
{
  "name": "chakra-7526-reproduction",
  "packageManager": "yarn@4.0.0-rc.42",
  "dependencies": {
    "@chakra-ui/icons": "^2.0.18",
    "@chakra-ui/react": "^2.5.5",
    "@chakra-ui/system": "^2.5.5",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "framer-motion": "^10.10.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@tsconfig/node18": "^1.0.1",
    "@types/react": "^18.0.31",
    "@types/react-dom": "^18.0.11",
    "typescript": "^5.0.3"
  }
}
```

```jsonc
// tsconfig.json
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "composite": true,
    "declarationMap": true,
    "incremental": true,
    "lib": [
      "dom",
      "es2021"
    ],
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react",
    "target": "es2018",
    "outDir": "dist/",
    "declaration": true,
    "emitDeclarationOnly": true,
    "isolatedModules": true
  },
  "include": [
    "src/**/*",
    "test/**/*"
  ],
  "exclude": [
    "node_modules"
  ],
  "references": [
  ]
}
```

### Link to Reproduction

https://gist.github.com/bryanjswift/3caee09992569aa385a15290842c3e92

### Steps to reproduce

1. Clone gist at https://gist.github.com/bryanjswift/3caee09992569aa385a15290842c3e92
2. Execute `yarn tsc`
3. See the compilation errors

### Chakra UI Version

2.5.5

### Browser

n/a

### Operating System

I have not tested other operating systems, this should not be an indication it only occurs on macOS.

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This has been reported and closed at least twice

### https://github.com/chakra-ui/chakra-ui/issues/7459

Closed with the indication the issue was fixed in `@chakra-ui/system` but as demonstrated in the minimal reproduction provided it was not fixed.

### https://github.com/chakra-ui/chakra-ui/issues/3714

Closed due to inactivity, community "consensus" was to downgrade the `typescript` version

### https://github.com/emotion-js/emotion/issues/3068

Same issue reported in the emotion repository.

**Comment by lexxa-tech** [comment] 2023-04-02 03:20
Its seems like vscode automatically upgrade its typescript version to 5.0. regardless of the typescript version that we use in the project workspace. so the solution is :

1.  Ctrl + P and then type ">"
2.  type "typescript"
3. Select : "Typescript : Select typescript version..."
4.  Select : "Use the workspace version"
5. Now, the error is gone

**Comment by bryanjswift** [comment] 2023-04-02 03:32
> Its seems like vscode automatically upgrade its typescript version to 5.0. regardless of the typescript version that we use in the project workspace. so the solution is :
> 
> 1. Ctrl + P and then type ">"
> 2. type "typescript"
> 3. Select : "Typescript : Select typescript version..."
> 4. Select : "Use the workspace version"
> 5. Now, the error is gone

The error is not in VSCode, it is from the command line as demonstrated in the reproduction steps which include the command `yarn tsc`. Also, I _want_ to be using TypeScript 5, in which case my workspace version would be TypeScript v5. I am not looking for a temporary fix but rather am reporting an error preventing the use of the latest versions of two libraries which could previously be used together. Put simply, using a different version of TypeScript does not “solve” this problem.

**Comment by manurgdev** [comment] 2023-04-02 17:24
Same issue after upgrade TypeScript from 4.5.5 to 5.0.3

**Comment by nandotess** [comment] 2023-04-03 01:00
I'm using Nx.dev (`15.8.6`), so I'm tied to `typescript` `4.9.5`. This issue started to happen as soon as I updated `@chakra-ui/react` to `2.5.5`. Downgrading it to `2.5.4` was the only solution that worked for me.

**Comment by violabg** [comment] 2023-04-03 07:32
I have the same issue with 2.5.5 even if I force the workspace to use  typescript 4.9.5

**Comment by paustint** [comment] 2023-04-03 21:13
Lots of conversation happening on this ticket as well: https://github.com/chakra-ui/chakra-ui/issues/3714

Summary of what I think I know:

1. Latest VSCode update uses a newer version of Typescript, so some people (like me) just experience the issue in the editor but the codebase compiles and deploys properly
    * Can be solved by setting your VScode TS version manually or with the setting `"typescript.tsdk": "node_modules/typescript/lib"`
3. It appears Chakra `2.5.5` is compatible with Typescript 5 (from this thread), but may not be compatible with Typescript 4.9.x

**Comment by bryanjswift** [comment] 2023-04-03 21:43
> 2. It appears Chakra `2.5.5` is compatible with Typescript 5 (from this thread), but may not be compatible with Typescript 4.9.x

Chakra `2.5.5` is _not_ compatible with TypeScript 5 and is what prompted my creating this ticket.

**Comment by paustint** [comment] 2023-04-03 23:46
> Chakra 2.5.5 is not compatible with TypeScript 5, at least when using @chakra-ui/system and is what prompted my creating this ticket.

Gotcha, I just assumed that from this comment https://github.com/chakra-ui/chakra-ui/issues/7526#issuecomment-1493396539

> I'm using Nx.dev (15.8.6), so I'm tied to typescript 4.9.5. This issue started to happen as soon as I updated @chakra-ui/react to 2.5.5. Downgrading it to 2.5.4 was the only solution that worked for me.

**Comment by EddieEldridge** [comment] 2023-04-07 11:02
Fixed for me by upgrading from **@chakra-ui/react** to 2.5.5 with Typescript 5+.

**Comment by violabg** [comment] 2023-04-07 14:58
> I'm using Nx.dev (`15.8.6`), so I'm tied to `typescript` `4.9.5`. This issue started to happen as soon as I updated `@chakra-ui/react` to `2.5.5`. Downgrading it to `2.5.4` was the only solution that worked for me.

same with nx.dev (15.9.2), @chakra-ui/react 2.5.5 and  typescript 4.9.5 or 5.0.3

I get the error at build time

**Comment by karfau** [comment] 2023-04-16 12:22
Since we are still using React 17, we are still using @chakra/*@1 and we are also experiencing this issue when trying to upgrade typescript to 5.0.3.

Any plans to provide a patch for v1 to make it compatible with ts v5?

**Comment by TimMensch** [comment] 2023-04-17 21:17
@bryanjswift A bit of experimentation finds that the problem only reproduces with:

```
    "jsxImportSource": "@emotion/react",
```
...in `tsconfig.json`.  Comment out that line and the bug vanishes. 

This makes me wonder if this is in fact an Emotion bug? Or maybe just a poor interaction between the two libraries?

**Comment by karfau** [comment] 2023-04-17 21:29
Is this something that is specific to chakra-ui v2?
I'm not able to find any occurrence of `jsxImportSource` in our codebase that uses v1

**Comment by TimMensch** [comment] 2023-04-17 21:31
@karfau 

It's an Emotion/React thing. See:

https://emotion.sh/docs/typescript

**Comment by TimMensch** [comment] 2023-04-17 21:32
@karfau Have you tried TypeScript 5.0.5 along with the newest Chakra libraries?

**Comment by karfau** [comment] 2023-04-17 21:41
@TimMensch as I described in https://github.com/chakra-ui/chakra-ui/issues/7526#issuecomment-1510358596 we are still using react 17, and my current understanding is that chakra-ui v2 requires react v18, so we will not be able to update that for "a while" until we migrated a huge bunch of a legacy code base, which is in progress but will still take a while.

**Comment by JakeGinnivan** [comment] 2023-04-18 01:25
I posted in the closed one. https://github.com/chakra-ui/chakra-ui/issues/7459#issuecomment-1511547120

I found I had some duplicated chakra packages in my pnpm lockfile.

Setting dedupe-peer-dependents=true in my .npmrc

Then removing "jsxImportSource": "@emotion/react", from my tsconfig fixed it.

Running latest of everything now without the error.

**Comment by heath-freenome** [comment] 2023-04-19 16:35
I'm stuck on the 1.x version of chakra-ui for the moment, I don't use the `jsxImportSource` at all. Just upgrading to TS 5.0.2 broke my very simple button. I'm guessing there is something in the chakra types that doesn't work well with TS 5.x

**Comment by bryanjswift** [comment] 2023-04-19 17:01
> @bryanjswift A bit of experimentation finds that the problem only reproduces with:
> 
> ```
>     "jsxImportSource": "@emotion/react",
> ```
> 
> ...in `tsconfig.json`. Comment out that line and the bug vanishes.
> 
> This makes me wonder if this is in fact an Emotion bug? Or maybe just a poor interaction between the two libraries?

This is good to know, thanks for investigating and finding this. I am not sure if my team's codebase can remove this line. My understanding is that chakra uses emotion libraries under the hood (see https://github.com/chakra-ui/chakra-ui/blob/77cfa68fb9399d098c3ed71bc8183930e3789dc3/packages/core/system/package.json#L50) which I think means this bug still belongs in chakra-ui, unless there's a different value that should be used in `jsxImportSourc` when using chakra libraries.

**Comment by leonard-henriquez** [comment] 2023-04-24 14:17
On my part we still have the same error even if we remove this line
```
"jsxImportSource": "@emotion/react",
```

**Comment by riceboyler** [comment] 2023-04-25 14:56
> I'm using Nx.dev (`15.8.6`), so I'm tied to `typescript` `4.9.5`. This issue started to happen as soon as I updated `@chakra-ui/react` to `2.5.5`. Downgrading it to `2.5.4` was the only solution that worked for me.

FWIW, I'm on nx as well and successfully use TS `5.0.4` with it. The only thing that fixed this issue for us was removing the `jsxImportSource` line from all of our tsconfig files (since nx is a monorepo and we have multiple libraries).

**Comment by csm-kb** [comment] 2023-04-30 01:54
+1, using pnpm and confirmed no duplicates + latest version on a minimal new Next stack with Chakra UI + Emotion:
```
"@chakra-ui/react": "~2.6.0",
"typescript": "~5.0.4",
```
I also make sure that VS Code is pointing to the `node_modules` Typescript install.

Removing the `"jsxImportSource": "@emotion/react"` line from `tsconfig.json` does mitigate, but wanting to confirm behavior since that makes it easier to work with Emotion without comment-importing at the top!

**Comment by hixus** [comment] 2023-05-07 11:29
Might not be same for others but hit this today after updating typescript to 5.0.4. I had some forgotten resolutions from a bug while a back https://github.com/chakra-ui/chakra-ui/issues/6372#issuecomment-1195010546 . After removing now unnecessary resolutions everything started working fine.

**Comment by FreePhoenix888** [comment] 2023-06-05 12:46
https://stackoverflow.com/a/74847054/13545849

**Comment by nagayama** [comment] 2023-07-18 07:16
I removed `"jsxImportSource": "@emotion/react"` from tsconfig.json and put `"types": ["@emotion/react/types/css-prop"]` instead, and it builds without error in my environment.

**Comment by younes0** [comment] 2023-08-05 05:38
@nagayama that doesn't work on next.js, I get 
`Warning: Invalid value for prop `css` on <div> tag.`

**Comment by younes0** [comment] 2023-08-05 05:49
@nagayama your solutions works !

Note for Next, you need to change `next.config.js` in order to avoid error `Warning: Invalid value for prop `css` on <div> tag.`
``` tsx
/** @type {import('next').NextConfig} */
const nextConfig = {
  compiler: {
    emotion: true,
  }
}
```

**Comment by sudarshan-kj** [comment] 2023-08-07 06:33
Using Chakra 1.8 and Typescript 5 was causing this error. Downgraded Typescript to 4.9.5 and it started working fine. Maybe Charka 2.X.X supports Typescript  5.

**Comment by DeolaJ** [comment] 2023-08-24 10:50
Can confirm that this works for "@chakra-ui/react": "^2.5.5" and "typescript": "^5.1.6".

**Comment by Mizumaki** [comment] 2023-08-28 06:27
Reproduced with `"@chakra-ui/react": "^2.8.0"`, `"@emotion/react": "^11.11.1"` and `"typescript": "^5.2.2"`.

> I removed "jsxImportSource": "@emotion/react" from tsconfig.json and put "types": ["@emotion/react/types/css-prop"] instead, and it builds without error in my environment.

And this works very well.
Thanks

**Comment by tylerbecks** [comment] 2023-08-30 17:15
Removing emotion allowed me to unblock chakra

**Comment by asankasira** [comment] 2023-09-18 14:59
https://stackoverflow.com/a/77126751/3660710

**Comment by veeramarni** [comment] 2023-10-18 14:52
May we know when this issue will be resolved? We want to make using of Typescript v5 and this seems to be blocker

**Comment by FreePhoenix888** [comment] 2023-10-20 04:05
> May we know when this issue will be resolved? We want to make using of Typescript v5 and this seems to be blocker

I use chakra with ts 5. There is probably some problem on your side. Try to update chakra and typescript to latest versions

**Comment by bryanjswift** [comment] 2023-10-20 04:17
> > May we know when this issue will be resolved? We want to make using of Typescript v5 and this seems to be blocker
> 
> I use chakra with ts 5. There is probably some problem on your side. Try to update chakra and typescript to latest versions

I appreciate the attempt to help but this is inaccurate. The issue seems to be a type definition conflict between chakra and emotion/css and is clearly demonstrated by the minimal reproduction included in my original bug report.

**Comment by FreePhoenix888** [comment] 2023-10-20 09:19
> > > May we know when this issue will be resolved? We want to make using of Typescript v5 and this seems to be blocker
> > 
> > 
> > I use chakra with ts 5. There is probably some problem on your side. Try to update chakra and typescript to latest versions
> 
> I appreciate the attempt to help but this is inaccurate. The issue seems to be a type definition conflict between chakra and emotion/css and is clearly demonstrated by the minimal reproduction included in my original bug report.

Thank you! Have you tried to create issue in emotion repos?

**Comment by timkindberg** [comment] 2023-10-30 18:49
Happening to us too with Chakra 1 / TS 4:
- @chakra-ui/react @ 1.2.1
- typescript @ 4.5.5

We get this error on ONE SINGLE component in my codebase that doesn't look at all special compared to the thousands of other components. Looks like this:
```
export const TitleBlockLink = forwardRef(({ children, ...props }: LinkProps, ref) => (
  <Link variant="inlineGray" size="sm" ref={ref} {...props}>
    {children}
  </Link>
))
```

Our codebase is filled with components just like this, so it's confusing why it's marking this single one.

**Comment by vladkens** [comment] 2023-12-25 14:14
> > I removed `"jsxImportSource": "@emotion/react"` from tsconfig.json and put `"types": ["@emotion/react/types/css-prop"]` instead, and it builds without error in my environment.
> 
> Thanks @nagayama, this solution worked for me when using **Chakra UI 2.8** (`"@chakra-ui/react": "^2.8.1"`) with **Nx.dev 16.8** (`"@nx/next": "16.8.1"`) that forces the usage of **Next.js 13** (`"next": "13.3.0"`) and **Typescript 5** (`"typescript": "5.1.6"`) .
> 
> Example of one of the apps `tsconfig.json`:
> 
> ```json
> {
> 	"extends": "../../tsconfig.base.json",
> 	"compilerOptions": {
> 		"jsx": "preserve",
> 		// "jsxImportSource": "@emotion/react",
> 		"allowJs": false,
> 		"esModuleInterop": true,
> 		"allowSyntheticDefaultImports": true,
> 		"strict": true,
> 		"forceConsistentCasingInFileNames": true,
> 		"noEmit": true,
> 		"resolveJsonModule": true,
> 		"isolatedModules": true,
> 		"incremental": true,
> 		"types": ["jest", "node", "chrome", "@emotion/react/types/css-prop"]
> 	},
> 	"include": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "next-env.d.ts"],
> 	"exclude": [
> 		"node_modules",
> 		"jest.config.ts",
> 		"src/**/*.spec.ts",
> 		"src/**/*.test.ts"
> 	]
> }
> ```
> 
> Looking forward for the final solution where I could revert this change. Thank you!

Thanks. This worked for me as well

**Comment by Irrelon** [comment] 2024-01-18 13:12
For me, deleting the `node_modules` folder and then reinstalling all the deps with `yarn install` did the trick.

**Comment by effinrich** [comment] 2024-07-09 21:43
> ```json
> "types": ["jest", "node", "chrome", "@emotion/react/types/css-prop"]
> ```

Thanks for this simple fix. Such a giant pain in the ass.

**Comment by segunadebayo** [comment] 2024-10-04 14:46
Closing based on the suggestion above.
https://github.com/chakra-ui/chakra-ui/issues/7526#issuecomment-2218781281

**Closed by segunadebayo** 2024-10-04 14:46 UTC
Labels: Topic: TypeScript 🤠
