### ISSUE TITLE
Links in changelog to release notes is broken

### ISSUE THREAD

**Issue by paustint** [chakra-ui/chakra-ui#8574] opened 2024-06-14 13:01 UTC
### Description

On this page https://github.com/chakra-ui/chakra-ui/blob/main/CHANGELOG.md, the links to the release numbers are not correct and produce 404

### Link to Reproduction

N/A

### Steps to reproduce

go here https://github.com/chakra-ui/chakra-ui/blob/main/CHANGELOG.md
click on the latest release
go to 404 page

### Chakra UI Version

n/a

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2024-06-16 22:37
Duplicate of #8508 

Will get to it shortly

**Closed by segunadebayo** 2024-06-16 22:37 UTC
