### ISSUE TITLE
ButtonContent is causing NotFoundError if translated via Google

### ISSUE THREAD

**Issue by STiXzoOR** [chakra-ui/chakra-ui#7449] opened 2023-03-14 12:32 UTC
### Description

When a page is translated via Google Translate and there is a loading state on the button a `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` occurs due to the fact that `ButtonContent` is returning a `Fragment`. Replacing the fragment with `span` or `div` fixes this issue.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/23358296/225001767-33a6902a-1065-46e4-8f94-fb0481782523.png">

<img width="840" alt="image" src="https://user-images.githubusercontent.com/23358296/225001826-0ed4656a-27e8-4c98-bef6-60f38e6d3245.png">

### Link to Reproduction

https://codesandbox.io/s/brave-joana-cnomkp

### Steps to reproduce

1. Go to CodeSandbox example
2. Click on Open in New Window
3. Translate with page to some non english language
4. Press the button
5. The error will occur

### Chakra UI Version

2.5.1

### Browser

Chromium based

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2023-03-18 16:14
This is a duplicate of #6004

Changing it to a `span` or `div` will result in a breaking change in the layout (esp. for those using `display: flex`

Kindly wrap the button's content and loadingText within a `span` to resolve this.

```jsx
<Button
      isLoading={isLoading}
      loadingText={<span>Loading ...</span>}
    >
      <span>Submit</span>
    </Button>
```

PS: I've just pushed an update to widen the loadingText type to accept a ReactNode instead of a string.

**Closed by segunadebayo** 2023-03-18 16:14 UTC
