### ISSUE TITLE
Tooltip stuck after button click when showDelay is present 

### ISSUE THREAD

**Issue by ozadari5** [chakra-ui/chakra-ui#6682] opened 2022-09-13 11:49 UTC
### Description

When I have a tooltip on button that opens modal / switch page, if showDelay exist, the tooltip will show in dealy and will not close itself

### Link to Reproduction

https://codesandbox.io/s/async-mountain-3zmnm1?file=/src/app.js

### Steps to reproduce

hover over the button for less than 1s (the showDelay)
click the button before the tooltip is open
now the tooltip will appear in delay, i would have expected it not to appear at all

### Chakra UI Version

latest

### Browser

chrom 103

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

GIf:

![Sep-13-2022 14-46-07](https://user-images.githubusercontent.com/92675396/189893484-1017f5ae-636b-48f1-ab3b-76f5fc670bc9.gif)

**Comment by luanorlandi** [comment] 2022-09-30 18:19
Seems like the issue happens due to the modal overlay. The tooltip can no longer identify that the cursor moved away of hovering the tooltip, or something like this

I also wonder if this would happen with any overlay, even custom implementation

**Comment by luanorlandi** [comment] 2022-09-30 18:25
It could also be the case that clicking the button will open the tooltip in different behavior. Even without the modal, clicking the button keeps the tooltip in an open state after the cursor moves away. So this might be an intentional behavior

**Comment by anubra266** [comment] 2022-10-03 11:12
@ozadari5 this issue is fixed in the latest version. Your reproduction points to v0 which is no longer maintained.

**Closed by anubra266** 2022-10-03 11:12 UTC
