### ISSUE TITLE
Console error when turning on device emulation in Chrome

### ISSUE THREAD

**Issue by ryo-hisano** [chakra-ui/chakra-ui#2925] opened 2021-01-01 09:04 UTC
# 🐛 Bug report

When I turn on emulation of device in Desktop Chrome and click the radio button and checkbox, I get the error "Unable to prevent Default inside passive event listener invocation."

This error does not occur when emulation is turned off.
The same problem occurs when you actually create a React app locally.

Also, there is no real harm, only a Chrome Console error occurs.

## 💻 Link to reproduction

[Radio - Chakra UI](https://chakra-ui.com/docs/form/radio)

[Checkbox - Chakra UI](https://chakra-ui.com/docs/form/checkbox)

## 📝 Additional information

- Screenshots or code

Turn on device emulation
![image](https://user-images.githubusercontent.com/33693531/103436109-8d392700-4c5b-11eb-91ff-67f2c9840873.png)

Turn off device emulation
![image](https://user-images.githubusercontent.com/33693531/103436124-b2c63080-4c5b-11eb-93e3-ab3b15529f12.png)

**Comment by Meansereirith** [comment] 2021-01-16 04:38
I'm having this same issue. Please let me know when you found any quick solution

**Comment by segunadebayo** [comment] 2021-01-29 19:15
Considering this isn't a real issue, permit me to close it.

I can't seem to reproduce this though and I doubt if it's coming from Chakra UI itself. If it becomes a real blocker to your project, feel free to let us know.

Cheers.

**Closed by segunadebayo** 2021-01-29 19:15 UTC
Labels: Status: Needs Reproduction ♺

**Comment by hiroppy** [comment] 2021-02-16 05:35
hm, I'm facing this issue when I use Radio component. @segunadebayo would you reopen this issue?

**Comment by dodas** [comment] 2021-02-16 21:08
Hey @hiroppy, could you provide a reproduction, please?

**Comment by hiroppy** [comment] 2021-02-17 14:18
yep, thanks. I'll prepare it soon.

**Comment by srflp** [comment] 2021-03-26 15:49
Hey, this bug still exists.

Steps to reproduce:
1. Open one of the following links to be able to interact with the Checkbox or Radio component.
- [simple reproduction on codesandbox](https://codesandbox.io/s/unable-to-preventdefault-inside-passive-event-listener-invocation-wybod?file=/src/App.js)
- https://chakra-ui.com/docs/form/checkbox
- https://chakra-ui.com/docs/form/radio
2. Turn on Chrome devtools.
3. Turn on "device toolbar" by clicking "Toogle device toolbar" button (upper-left corner of devtools).
4. Click on label of Checkbox or Radio component.
5. Each click should trigger the following error:

![image](https://user-images.githubusercontent.com/17103865/112651204-77976000-8e4c-11eb-8bd8-8964624c1b69.png)
I'm testing it on the latest Chrome (Chrome 89, Windows 10).

Text form:
```
Unable to preventDefault inside passive event listener invocation.
```

In CodeSandbox, the stack trace points to this function that I think may have something to do with this issue:
https://github.com/chakra-ui/chakra-ui/blob/5274a3157ea62b899362eb3cdb808cef16ed1e7e/packages/checkbox/src/use-checkbox.ts#L364-L370

**Comment by cppng** [comment] 2021-03-30 17:11
This issues still persit

**Comment by jaredLo** [comment] 2021-04-15 09:28
> Hey, this bug still exists.
> 
> Steps to reproduce:
> 
> 1. Open one of the following links to be able to interact with the Checkbox or Radio component.
> 
> * [simple reproduction on codesandbox](https://codesandbox.io/s/unable-to-preventdefault-inside-passive-event-listener-invocation-wybod?file=/src/App.js)
> * https://chakra-ui.com/docs/form/checkbox
> * https://chakra-ui.com/docs/form/radio
> 
> 1. Turn on Chrome devtools.
> 2. Turn on "device toolbar" by clicking "Toogle device toolbar" button (upper-left corner of devtools).
> 3. Click on label of Checkbox or Radio component.
> 4. Each click should trigger the following error:
> 
> ![image](https://user-images.githubusercontent.com/17103865/112651204-77976000-8e4c-11eb-8bd8-8964624c1b69.png)
> I'm testing it on the latest Chrome (Chrome 89, Windows 10).
> 
> Text form:
> 
> ```
> Unable to preventDefault inside passive event listener invocation.
> ```
> 
> In CodeSandbox, the stack trace points to this function being invoked by `callAllHandlers`:
> https://github.com/chakra-ui/chakra-ui/blob/5274a3157ea62b899362eb3cdb808cef16ed1e7e/packages/checkbox/src/use-checkbox.ts#L364-L370
> 
> 
> https://github.com/chakra-ui/chakra-ui/blob/5274a3157ea62b899362eb3cdb808cef16ed1e7e/packages/utils/src/function.ts#L11-L20

I'm having this problem as well, identical to this one.

**Comment by Hubiwan** [comment] 2021-05-14 15:33
Am not trying to necro this one, but has this one been resolved by any chance?

Not a big deal but looks like we still get this very message "Unable to prevent Default inside passive event listener invocation." when using radio buttons in emulator mode (it can be checked directly on the [doc itself](https://chakra-ui.com/docs/form/form-control), by just selecting any of Naruto's character and just looking chrome dev tool console in device emulator mode).

Would be glad to hear any workaround if any, tks.

**Comment by MarcLongJoyride** [comment] 2021-08-17 20:51
Can this please be reopened? We are having this issue on our site as well.

**Comment by dayoolacodes** [comment] 2021-10-05 12:57
this issue still persists. check https://chakra-ui.com/docs/form/checkbox and open your browser's console.

**Comment by oncet** [comment] 2021-10-19 14:07
Having this warning after selecting a `Radio` component.

`vendor.89ffc88f.js:27 Unable to preventDefault inside passive event listener invocation.`

**Comment by matthewrose** [comment] 2022-01-24 17:59
For those still experiencing this error: The issue is because the components' `label` element needs the following style: `touch-action: none`. I added it as a global style for now in my theme. See: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by yaniv691** [comment] 2022-02-03 12:43
Still happening in Feb 2022... is there an ETA on when this is going to be resolved?

**Comment by astahmer** [comment] 2022-02-20 15:53
thank you @matthewrose that solved it
```ts
const theme = extendTheme({
    config: { initialColorMode: "light" },
    components: { Checkbox: { baseStyle: { label: { touchAction: "none" } } } },
});
```

**Comment by astahmer** [comment] 2022-02-20 15:55
thank you @matthewrose that solved it
```ts
const theme = extendTheme({
    config: { initialColorMode: "light" },
    components: { Checkbox: { baseStyle: { label: { touchAction: "none" } } } },
});
```

**Comment by rishm17** [comment] 2022-03-03 15:28
Did anyone manage to resolve this?

**Comment by dodas** [comment] 2022-03-03 21:23
Is this actually causing some issues, or is it just an error in the console?

**Comment by oncet** [comment] 2022-03-03 22:44
> Is this actually causing some issues, or is it just an error in the console?

I think it's just a warning/error in the console, I haven't found this to cause any issues.

**Comment by matthewrose** [comment] 2022-03-04 00:33
It's a simple fix though. Here's where the style I referenced above could be added to fix the issue if that helps: 

https://github.com/chakra-ui/chakra-ui/blob/9747c534327145fb4a7e3e6c88a3ecfb7cf1b4fb/packages/checkbox/src/checkbox.tsx#L29

**Comment by Darwin97VA** [comment] 2022-03-18 18:18
Same: Did anyone manage to resolve this?

**Comment by Chukwuamaka** [comment] 2022-03-31 15:30
> Is this actually causing some issues, or is it just an error in the console?

In emulator mode, it prevents my form submit API call from going through. I also noticed that for checkboxes, the error only occurs when you click on the text part of the checkbox. Clicking directly on the box does not trigger the error.

I hope the issue will be reopened and eventually resolved.

**Comment by egurinko** [comment] 2022-05-03 10:18
> For those still experiencing this error: The issue is happening because the components' `label` element needs the following style: `touch-action: none`. I added it as a global style for now in my theme. See: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

As @matthewrose explained, `label` component needs `touch-action` style.
For quick fix, customizing theme is easy to suppress the error.

```ts
import { extendTheme, theme as defaultTheme } from '@chakra-ui/react';

const theme = extendTheme({
  components: {
    Checkbox: { // can be Radio
      baseStyle: {
        label: {
          touchAction: 'none',
        },
      },
    },
  },
});
```

**Comment by regMeet** [comment] 2022-05-28 06:56
@egurinko still not working, i'm using Radio buttons but I couldn't make it work with your solution

**Comment by matthewrose** [comment] 2022-05-28 10:31
@regMeet and others who view this: the style should not be on not on the `label` part but instead the `container` part. Look here and you will see where `styles.container` is used: 

https://github.com/chakra-ui/chakra-ui/blob/9747c534327145fb4a7e3e6c88a3ecfb7cf1b4fb/packages/checkbox/src/checkbox.tsx#L149

So the example from @egurinko should be updated to the following:

```js
import { extendTheme } from '@chakra-ui/react';

const theme = extendTheme({
  components: {
    Checkbox: { // can be Radio
      baseStyle: {
        container: {
          touchAction: 'none',
        },
      },
    },
  },
});
```

That being said it should be simple to fix this in the code for the component or theme in `chakra-ui` itself. (see my previous comment)

**Comment by alanalbertengo-santex** [comment] 2022-05-29 19:46
@matthewrose  still not working for me when using mobile web view and Radio component and clicking on the Radio's label

**Comment by matthewrose** [comment] 2022-08-23 22:38
Update: I realize now after further testing that the `touch-action` fix is not removing this violation in all cases for me. After digging deeper it seems that the issue is due to `preventDefault` being called from a "passive" event listener, which is unnecessary and incorrect.

React uses passive event listeners for `onTouchStart`, `onTouchMove`, and `onWheel` events. (Read: https://github.com/facebook/react/pull/19654)

So I now suspect the fix for chakra is needed here, in the `stopEvent` function of use-checkbox.ts: https://github.com/chakra-ui/chakra-ui/blob/main/packages/checkbox/src/use-checkbox.ts#L341

What I'm saying is we should not be using `preventDefault` for these and other `passive` events. So in that code, we should check to make sure the event is not passive (as React uses for `onTouchStart`, `onTouchMove`, and `onWheel`) and prevent the call to `preventDefault` in those cases.

**Comment by poomthiti** [comment] 2022-11-17 06:58
ran into this issue recently for the radio component, my solution is to add pointerEvents: "none" css to the label part
```
const Radio: ComponentStyleConfig = {
  baseStyle: {
    label: {
      pointerEvents: "none",
    },
  }
}
```
Seems to be working fine at the moment

**Comment by gustavolzangelo** [comment] 2022-11-17 16:43
> ran into this issue recently for the radio component, my solution is to add pointerEvents: "none" css to the label part
> 
> ```
> const Radio: ComponentStyleConfig = {
>   baseStyle: {
>     label: {
>       pointerEvents: "none",
>     },
>   }
> }
> ```
> 
> Seems to be working fine at the moment

This one worked for me

**Comment by niels-k-86** [comment] 2022-12-01 10:17
This is still a problem in the latest version.

If I use a Checkbox or Radio button within a Modal, it prevents touch scrolling. This is a major issue as far as I'm concerned and this ticket should be reopened.

**Comment by maliheNoroozi** [comment] 2023-05-24 09:34
I'm using Radio buttons and checkbox. When clikcing on their labels, I am having this issue. Still no solution?

**Comment by ordep2v** [comment] 2023-07-11 18:42
I solved my problem, in 2023 this bug still happens. When i clicked in radio input option, this error returns "Unable to preventDefault inside passive event listener invocation.".

How to solve?

Go to ur global styles in chakra and add "pointer-events: none;". PS: In my chakra version, this is the current className of label in Radio component, you need to evaluate if it's the same.

![chakra-error](https://github.com/chakra-ui/chakra-ui/assets/66853097/74178d5b-4cc4-46c4-abe2-6190c5dc34d3)

**Comment by barry-genies** [comment] 2024-06-13 16:49
Solved this by not using <HStack> to wrap the <Radio> components. Instead, using <Flex>
![Screenshot 2024-06-13 at 9 48 58 AM](https://github.com/chakra-ui/chakra-ui/assets/122313320/048ffc5b-8865-40d9-bfbc-e6a23c1622c8)
