### ISSUE TITLE
Width prop in Box is broken when it's 1/2

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/chakra-ui#3396] opened 2021-02-15 21:43 UTC
# 🐛 Bug report

Hi,

I just update to chakra the latest version `v1.3.3` and noticed that the width prop is broken when the value is `1/2`.

Usually `1/2` should return `50%`, now is returning `0.125rem`.

## 💥 Steps to reproduce

open the codesandbox 
try to change width between `1/4` & `1/2`

## 💻 Link to reproduction

https://codesandbox.io/s/bold-field-ni35l?file=/src/App.tsx

## 🧐 Expected behavior

Using `1/2` should return `50%`.

**Comment by dodas** [comment] 2021-02-15 22:50
This PR got merged in the last release: https://github.com/chakra-ui/chakra-ui/pull/3237
`1/2` is `0.5`, so it uses that value from `spacing`.

Probably nobody thought that could be a breaking change.
Hmm, I'm not sure how we should deal with this.

cc @with-heart

**Comment by omarkhatibco** [comment] 2021-03-03 14:24
Hi, 

any update on this issue ?

**Comment by segunadebayo** [comment] 2021-03-04 07:58
Yes, that #3237 PR is the cause of the issue.

This is an oversight on our part and indeed a breaking change. We'll avoid things like this in the future.

Kindly replace "1/2" with "50%" in your codebase @omarkhatibco.

Thanks.

**Closed by segunadebayo** 2021-03-04 07:58 UTC
Labels: Type: API discussion 💡, Type: Bug 🐛

**Comment by geunjae-grip** [comment] 2023-07-19 10:39
This is still written in the example. I spent a lot of time because of this content.
