### ISSUE TITLE
Setting isDisabled to false on a checkbox triggers disabled arrow in Chrome

### ISSUE THREAD

**Issue by Catchpowle** [chakra-ui/chakra-ui#2364] opened 2020-10-28 23:19 UTC
# Bug report

## Describe the bug

Setting isDisabled to false allows the checkbox to be used as it should however in Chrome a disabled arrow is still displayed. This makes it difficult to create wrapper components that default these value to false.

## To reproduce

```
<Checkbox isDisabled={false}>Checkbox</Checkbox>
```

## Minimal reproduction

https://codesandbox.io/s/cranky-gates-pkd4n?file=/src/App.tsx

## Expected behavior

The disabled arrow should not be displayed if the checkbox is not disabled.

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.7
- Version of Node.js: 12.16.1

**Comment by avaragado** [comment] 2020-10-29 07:54
Duplicate of #2339 - fixed by #2340

**Closed** 2020-10-29 09:00 UTC
