### ISSUE TITLE
Accordion DefaultIndex prop paints first time not collapsed

### ISSUE THREAD

**Issue by maapteh** [chakra-ui/chakra-ui#5146] opened 2021-11-24 09:53 UTC
### Description

When im using the defaultIndex prop of the Accordion i expect the panel to be rendered opened at first

### Link to Reproduction

Here you can see the flow, so no user interaction is taking place this is just the first render!

https://codesandbox.io/s/friendly-tamas-i1esm?file=/pages/index.tsx (reproduction added!)

### Steps to reproduce

- Here you can see im passing the first elements to start opened (defaultIndex, The initial index(es) of the expanded accordion item) 
- Then the first cycle you see all are not opened
- Then it starts to slowly open the first items which where set in the defaultIndex

That gives problems when im trying to pre-render something inside it.

### Chakra UI Version

latest

### Browser

Chrome

### Operating System

- macOS

**Comment by segunadebayo** [comment] 2021-11-28 17:23
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please attach a reproduction to re-open.

**Comment by maapteh** [comment] 2021-11-29 15:13
@segunadebayo now with reproduction: https://i1esm.sse.codesandbox.io/

Section 1 is said to start opened, when you turn on performance tab, record, reload the page you can see its first render is both closed and then slowly opening. 

<img width="425" alt="Screenshot 2021-11-29 at 16 11 18" src="https://user-images.githubusercontent.com/25961356/143893053-9c1fe3f9-6e65-4750-9762-128861e2578f.png">

**Comment by primos63** [comment] 2021-12-01 03:23
I am using Arch Linux with the latest Chrome browser and 19 tabs open at the time of testing.
I did not observe the issue with the CodeSandbox example provided.
I also created another CodeSandbox with a simple React app and the sample Accordion code provided. I did this to see if it was an issue with Next JS, but I did not observe the issue.

Closing as the issue is not reproducible.

**Closed by primos63** 2021-12-01 03:23 UTC

**Comment by maapteh** [comment] 2021-12-01 07:58
Unbelievable...

So you openend your performance tab and you slowly hovered over all paintings and didnt see it starts all closed on the FIRST paint? I can even show it by a simple test :(

**Comment by maapteh** [comment] 2021-12-01 08:07
![bug](https://user-images.githubusercontent.com/25961356/144195666-a4c46b27-7270-46b8-8a68-4d8c94644c03.gif)

@primos63 please re-open

**Comment by maapteh** [comment] 2021-12-01 11:51
test:
```
describe("Accordion", () => {
  beforeAll(() => {
    jest.useFakeTimers("modern");
  });

  it("renders correctly", async () => {
    render(<Accordion />);

    const buttons = screen.queryAllByRole("button");

    expect(buttons.length).toBe(2);

    expect(screen.getByText("Section 1 title")).toBeVisible();
    expect(screen.getByText("Section 2 title")).toBeVisible();

    expect(screen.getByText(/Lorem ipsum dolor sit amet/)).not.toBeVisible();
    expect(screen.getByText(/Ut enim ad minim veniam/)).not.toBeVisible();

    // AFTER ANIMATION IT OPENS!!
    act(() => {
      jest.runAllTimers();
    });

    expect(screen.getByText(/Lorem ipsum dolor sit amet/)).toBeVisible();
  });
});
```

test results:
```
$ jest
 PASS  components/accordion.spec.tsx
  Accordion
    ✓ renders correctly (148 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.89 s, estimated 2 s
```

**Comment by maapteh** [comment] 2021-12-01 11:53
So clearly you can see by test it not renders it opened at first, thats AFTER the first cycle. 

Im really surprised how quickly a bug gets closed. Normally i would have given up for a long time and just moved to something else. Please dont close something so quickly. Also i really doubt you looked with performance tab...

**Comment by maapteh** [comment] 2021-12-01 11:56
@segunadebayo

**Comment by Jkdrumm** [comment] 2022-04-04 16:12
This is still an issue as of 1.8.7. I haven't been able to find a workaround. @segunadebayo @primos63 please re-open.

**Comment by jdddog** [comment] 2022-11-24 23:22
@maapteh and @Jkdrumm 

I think this is the same issue as [Tabs: defaultIndex does not fully support SSR #4506](https://github.com/chakra-ui/chakra-ui/issues/4506) which was also closed without being fixed.

@primos63, if you run @maapteh's [example](https://i1esm.sse.codesandbox.io/) with JavaScript disabled you'll see that the first accordion item is closed and doesn't open until after the app has hydrated.

This is easy to see on this example built with ChakraUI: https://open.coki.ac/. Notice the country tab starts off not selected and changes to selected and the region accordion is not open to begin with and then opens. If you disable JavaScript then the country tab is not selected and the region accordion is closed.

Is there a way to workaround this?

**Comment by kevinxh** [comment] 2023-05-19 21:56
:( We encountered this issue as well when we upgrade our app from react 17 to 18, apparently in react 18 is a lot more strict for hydration errors. Hydration mismatch cause react to re-render entire component tree. We need the Accordions to be expandable on server side. This is not solvable from user land.

@segunadebayo

**Comment by eddielee394** [comment] 2023-12-21 04:37
Just ran into this issue when updating the route of a page causing a rerender - the accordions briefly flash shut then open again (not using SSR).

**Comment by statico** [comment] 2024-04-30 21:29
I'd love to see this fixed. Now that Google is putting additional focus on Content Layout Shift scores as part of the Core Web Vitals metrics, it's more important to make sure that the accordion displays the correct state during the first paint so that elements around the accordion aren't moved.

**Comment by adam-b-jones** [comment] 2025-02-03 20:15
This is STILL an issue. No idea why this issue was closed.

**Comment by danielbeardsley** [comment] 2025-05-30 00:06
This remains *broken* and the first paint is *closed* even when the code sets it to start as open.
