### ISSUE TITLE
Button: box-shadow property on focus state is always set to blue

### ISSUE THREAD

**Issue by brahim-kellou** [chakra-ui/chakra-ui#2998] opened 2021-01-09 14:32 UTC
# 🐛 Bug report

the `box-shadow` property on `focus` state is always set to blue color `rgba(66, 153, 225, 0.6)` whatever was the `background-color` of the button.

## 💥 Steps to reproduce

We can pick up an example from the docs:
1. Go to [Button documentation](https://chakra-ui.com/docs/form/button)
2. Click on any button that doesn't have blue background-color
3. See the error (`box-shadow` has blue color`)

## 🧐 Expected behavior

By default, I think the color of the `box-shadow` on `focus` state should always follow the `background-color` of the `button`, with changing the opacity of course. 

## 🧭 Possible Solution

A function that converts button `background-color` to `rgba()` (to control the opacity easily) and set that color to `box-shadow` on `focus` state.
Maybe a better solution exists! 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI         |      1.0     |
| Browser            | Chrome  |
| Operating System | Windows 10 |

## 📝 Additional information

- Screenshots or code

![image](https://user-images.githubusercontent.com/32751978/104094103-21744100-528f-11eb-9303-1088d0545299.png)
![image](https://user-images.githubusercontent.com/32751978/104094152-6dbf8100-528f-11eb-87a4-b43adc23cb2d.png)
![image](https://user-images.githubusercontent.com/32751978/104094168-7dd76080-528f-11eb-96ba-bbd38a48cce7.png)

**Comment by LyricL-Gitster** [comment] 2021-02-05 17:38
I think I'm having the same issue. According to [this answer](https://github.com/chakra-ui/chakra-ui/discussions/1921#discussioncomment-84313):

> To change the box-shadow, update the value of theme.shadows.outline to whatever feels like to you

I've tried the following for a Chakra theme:
```
import { extendTheme } from '@chakra-ui/react'
export default extendTheme({shadows: { outline: '#A616BD'}})
```

but no change...

**Comment by with-heart** [comment] 2021-02-06 02:55
Closing as a duplicate of #3122

@LyricL-Gitster You have to provide [a valid `box-shadow` value](https://codesandbox.io/s/distracted-hellman-9nrng?file=/src/App.tsx). Here's an example: https://codesandbox.io/s/distracted-hellman-9nrng?file=/src/App.tsx

**Closed by with-heart** 2021-02-06 02:55 UTC
