### ISSUE TITLE
Gradient Text with a cursive font doesnt display as expected

### ISSUE THREAD

**Issue by kevkanae** [chakra-ui/chakra-ui#5929] opened 2022-04-26 06:29 UTC
### Description

The text to which the gradient is applied as per the official docs, gets clipped incorrectly. Please to check the sandbox for an example

### Link to Reproduction

https://codesandbox.io/s/modern-leaf-celjjc

### Steps to reproduce

1. Add a text component with any text
2. Add the text gradient as per the docs
3. Add a custom font (eg: My Soul, Great Vibes) through fontsource

### Chakra UI Version

1.8.8

### Browser

Microsoft Edge Version 100.0.1185.50 (Official build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/64493268/165235756-73f8c9bb-fc24-47c7-96ad-949409cb0cb3.png)

**Comment by TimKolberger** [comment] 2022-05-01 15:39
The Text component in the codesandbox renders a `p` element, which is by default `display: block`. The background, which is clipped to the text, takes the full width, but is only visible where the text is.

You could add `display="inline-block"` to the Text element to fix this.

Closing this issue because it is not a bug in chakra ui.

**Closed by TimKolberger** 2022-05-01 15:39 UTC

**Comment by kevkanae** [comment] 2022-05-02 02:41
It'd be nice if the docs had a note about this
Thanks :)
