### ISSUE TITLE
Wrong indexes for all props in documentation

### ISSUE THREAD

**Issue by Powerplex** [chakra-ui/chakra-ui#5154] opened 2021-11-26 09:41 UTC
### Subject

Every prop is not associated with its description

### Description

![Capture d’écran 2021-11-26 à 10 40 31](https://user-images.githubusercontent.com/2033710/143560043-674f912e-211b-48fe-97ef-243374acbcb0.png)

`allowPinchZoom` the description for `onClose`, `autoFocus ` has the description of `allowPinchZoom`, etc until the end of the table.

Screenshot was taken here: https://chakra-ui.com/docs/overlay/drawer

**Comment by primos63** [comment] 2021-11-26 15:33
This is a duplicate of #5088. When going to the component from the search bar the documentation is correct. When going to it directly with a url or when refreshing the layout is wrong.
Closing this issue in favor of the first one.

**Closed by primos63** 2021-11-26 15:33 UTC
Labels: Topic: Documentation 📚, Type: Duplicate 😒
