### ISSUE TITLE
Tooltip on disabled buttons not working

### ISSUE THREAD

**Issue by DeeeeLAN** [chakra-ui/chakra-ui#5528] opened 2022-02-04 20:10 UTC
### Description

When there is a tooltip wrapping a disabled button, the tooltip is disabled as well. If you separate the tooltip from the button by adding a Box or using `shouldWrapChildren`, the tooltip works again. However, if the button is part of a button group, this causes it to disconnect from the group and lose the proper border radius. 

### Link to Reproduction

https://codesandbox.io/s/zealous-wind-lysbr

### Steps to reproduce

There are four buttons/button groups set up, demonstrating the different cases I have come across. 

The first demonstrates a tooltip on a disabled button, which does not work.
The second demonstrates a tooltip on a disabled button with `shouldWrapChildren`, which works.
The third is a group showing a tooltip on an enabled button working, and a disabled button not working.
The fourth is a group showing a disabled button with a `shouldWrapChildren` tooltip, demonstrating the border radius issue. 

### Chakra UI Version

1.8.1

### Browser

Firefox 96.0.3

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/12877032/152596500-ca2dc4b5-74fd-49eb-a8eb-feada0194e80.png)

My current workaround is to manually set the border radius back to 0 on the appropriate sides of the first 3 buttons where the issue is occurring.

**Comment by TimKolberger** [comment] 2022-02-05 14:43
Duplicate of #2849
@nikolovlazar is this a candidate for the FAQ?

**Closed by TimKolberger** 2022-02-05 14:43 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by DeeeeLAN** [comment] 2022-02-06 06:36
It is only partly duplicating that ticket, because the workaround of wrapping the button to enable the tooltip again breaks the button group, as noted in the original report.

**Comment by chrysb** [comment] 2022-09-03 20:49
@TimKolberger  

This issue is still problematic and it's broken imo. I am using a button group and I'd like to indicate why some of the options are disabled. It's currently impossible because using `shouldWrapChildren` breaks the layout of the `ButtonGroup`.

Can we re-open this ticket please?

**Comment by DeeeeLAN** [comment] 2022-09-04 07:12
They don't seem interested in fixing this one for some reason. I would just manually set the border radius if it is not too much work for your use-case, personally.

**Comment by chrysb** [comment] 2022-09-06 01:00
> They don't seem interested in fixing this one for some reason. I would just manually set the border radius if it is not too much work for your use-case, personally.

Thanks for the reply! It also changes the size of the button. I only wrapped the middle one here, if I wrapped all 3 it would be a mess. I ended up just manually disabling the buttons instead of using `isDisabled` — I think that's a more extensible approach
