### ISSUE TITLE
[Tooltip] Tooltip doesn't hide on disabled buttons

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#500] opened 2020-03-16 14:30 UTC
**Describe the bug**
Tool tip label does not hide on a disabled button

**Expected Behavior**
Tooltip should hide when mouse leaves target

**To Reproduce**
```
      <Stack isInline spacing={8} shouldWrapChildren>
        <Tooltip
          label="Hey there, i leave!"
          aria-label="Hey there"
          placement="left"
        >
          <Button>Button</Button>
        </Tooltip>
        <Tooltip
          label="I wont leave??"
          aria-label="I wont leave??"
          placement="right"
        >
          <Button isDisabled>Disabled Button</Button>
        </Tooltip>
      </Stack>
```

**Suggested solution(s)**
I assume something to do with the focus on disabled buttons, though im not really sure how it works.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 0.6.1

![Mar-16-2020 15-28-32](https://user-images.githubusercontent.com/12549124/76768208-f8803e00-679a-11ea-9a90-549e88885887.gif)

**Comment by JClackett** [comment] 2020-03-16 14:34
A question that i have with the Tooltip api is: I have a button that can be disabled and i want to display a tooltip for why its disabled, however when the button is not disabled i dont want the tooltip to show, what is the best way to achieve this? Ideally there would be a isDisabled prop on tooltip that disables all functionality at the moment im having to do this:

```jsx
        <Tooltip
          placement="left"
		  // set it to false to force it to hide, or put it to undefined to 
          // resume normal behaviour
          isOpen={isDisabled ? undefined : false} 
          label="This is disabled because..."
          aria-label="This is disabled because..."
        >
          <Button
            onClick={onClick}
          >
			Click me
          </Button>
        </Tooltip>
```

**Comment by segunadebayo** [comment] 2020-03-17 22:10
@JClackett, thanks for finding a walkaround this issue. We'll account for this scenario in the next release.

I think the solution you have works for now, but I understand it's quite painful.  It'll be fixed.

**Comment by JClackett** [comment] 2020-03-19 21:11
Thanks! Do you mean that the isDisabled bug will be fixed in the next release?

**Comment by segunadebayo** [comment] 2020-03-20 05:52
@JClackett. Yes. Ideally, it should work without adding a `isDisabled` prop to the tooltip, since mouse event listeners are meant to be canceled when a button is disabled.

It's a bug and we'll fix it in the next release.

**Comment by moulinraphael** [comment] 2020-05-26 15:53
Hello ! Is this bug fixed in the 0.7.0 or 0.8.0 releases ?

**Comment by YuliyaAstakhova** [comment] 2020-06-18 09:24
I have the same problem

**Comment by eugenenelou** [comment] 2020-07-08 10:03
The workaround is working for me on firefox but not on chrome.

**Comment by segunadebayo** [comment] 2020-07-08 10:59
This is fixed in the V1 pre-release. We'll publish an update shortly.

The next release version: `1.0.0-next.5`

**Comment by trevorblades** [comment] 2020-08-26 19:05
I'm still noticing this issue in the latest RC. It could be related to this long-standing issue in React: https://github.com/facebook/react/issues/4251

This short blog post includes some more detail: https://lecstor.com/react-disabled-button-onmouseleave/

**Comment by with-heart** [comment] 2020-08-30 20:01
Re-opening so we can verify and address further.

**Closed** 2020-10-20 10:45 UTC
Labels: Type: Bug 🐛

**Comment by chrise86** [comment] 2020-11-09 14:17
Does this rectify the issue with tooltips not showing at all on disabled buttons? My issue is slightly different to above (on version 0.8.0) in that tooltips (or popovers) dont show when the trigger element is a disabled button.

**Comment by kuasha420** [comment] 2021-01-12 06:13
> Does this rectify the issue with tooltips not showing at all on disabled buttons? My issue is slightly different to above (on version 0.8.0) in that tooltips (or popovers) dont show when the trigger element is a disabled button.

Same. Tooltip doesn't appear on disabled button or icon buttons

**Comment by tmikeschu** [comment] 2021-01-14 01:06
^ Same behavior with a disabled button as a popover trigger. I want to show a popover to explain why the button is disabled, with a link to rectify the problem (billing related).

**Comment by scottrepreneur** [comment] 2021-02-04 14:23
1.1, also seeing this. Fine for normal buttons and explicitly setting `isOpen` on the `Tooltip`.

**Comment by grsoares21** [comment] 2021-02-10 17:47
I'm also seeing this with version 1.1.4

**Comment by AJFunk** [comment] 2021-02-18 20:10
> Does this rectify the issue with tooltips not showing at all on disabled buttons? My issue is slightly different to above (on version 0.8.0) in that tooltips (or popovers) dont show when the trigger element is a disabled button.

@chrise86  @kuasha420 @tmikeschu  I ran into this same problem - after investigating, this seems to be expected behavior. When Chakra's button is disabled like `<Button isDisabled />` this renders an html `<button disabled>` and the browser swallows hover events.

When you wrap a button with a toolip:
```
<Tooltip>
  <Button isDisabled>foo</Button>
</Tooltip>
```

The Tooltip passes down a `onMouseEnter` handler which is attached to the button. That handler doesn't work because the event is swallowed at the browser level. You need a wrapper to fix this - my implementation looks something like:
```
// don't forget to forwardRef!
const CustomButton = forwardRef(function CustomButton({ onMouseEnter, ...props }, ref) {
  return (
    <Box ref={ref} onMouseEnter={props.isDisabled ? onMouseEnter : undefined}>
      <Button {...props} onMouseEnter={props.isDisabled ? undefined : onMouseEnter}>
        {children}
      </Button>
    </Box>
  );
};

// usage
<Tooltip>
  <CustomButton isDisabled>foo</CustomButton>
</Tooltip>
```

I omit the `onMouseEnter` from the button so we don't have duplicate event handlers (this can result in some weirdness when you hover)

@segunadebayo I think it would be ideal to add something about this in the docs!

**Comment by rossng** [comment] 2021-06-30 11:35
I've also just run into this. Would be really nice if there was a way to make it work without a custom wrapper component.

**Comment by tmikeschu** [comment] 2021-06-30 12:10
@AJFunk good find!

@rossng I've just been wrapping `Button` with a `span`. Still a bit noisy but less boilerplate.

```tsx
<Tooltip>
  <span>
    <Button ...>...</Button>
  </span>
</Tooltip>
```

**Comment by rossng** [comment] 2021-06-30 13:02
@tmikeschu thanks, that worked perfectly. And I think it's still relatively accessible, which is good.

**Comment by andreidmt** [comment] 2021-09-10 09:55
There is also a `shouldWrapChildren` prop on the [Tooltip](https://chakra-ui.com/docs/overlay/tooltip#props) component:

```jsx
<Tooltip label="ipsum" shouldWrapChildren>
  <Button isDisabled>lorem</Button>
</Tooltip>
```

**Comment by julioolvr** [comment] 2023-03-21 11:28
Unfortunately wrapping the trigger on a `span` doesn't work (as in, the popover won't disappear) for `Popover`, and `Tooltip` isn't a good replacement in all cases because it doesn't support arbitrary JSX. It's possible to reproduce by slightly modifying the "Basic Usage" example from [the docs](https://chakra-ui.com/docs/components/popover#basic-usage)

```tsx
<Popover trigger="hover">
  <PopoverTrigger>
    <span><Button isDisabled>Trigger</Button></span>
  </PopoverTrigger>
  <PopoverContent>
    <PopoverArrow />
    <PopoverCloseButton />
    <PopoverHeader>Confirmation!</PopoverHeader>
    <PopoverBody>Are you sure you want to have that milkshake?</PopoverBody>
  </PopoverContent>
</Popover>
```

**Comment by felixfbecker** [comment] 2023-06-23 23:17
`disabled` buttons are a common pitfall, especially as it relates to tooltips, but also because they are generally not tab-focusable and therefor not accessible.
Many great articles on this:
- https://css-tricks.com/making-disabled-buttons-more-inclusive/
- https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/

It would be great if Chakra could just employ one of the solutions under the hood – namely if instead of setting the native `disabled` attribute, it set `aria-disabled="true"` (which already applies the styles) and an `onClick` handler with `event.preventDefault()` (it should prevent clicks and enter/space bar interactions).

Currently it's not even possible to do this manually with Chakra, because Chakra will ignore and override any `aria-disabled` prop passed in with the value of `isDisabled`, meaning you can't set `aria-disabled="true"` without setting `disabled` as well. This is a big accessibility issue.

**Comment by avital-ubeya** [comment] 2024-09-19 09:27
updating rc-tooltip to latest version made it work
