### ISSUE TITLE
Avatar is blinking while switching the screen or during an API call

### ISSUE THREAD

**Issue by bigint** [chakra-ui/chakra-ui#4383] opened 2021-07-14 05:07 UTC
### Description

Avatar is blinking while switching the screen or during an API call, I tried with both eager and lazy loading still happening the same!

### Link to Reproduction

https://devpartyio.vercel.app/

### Steps to reproduce

https://user-images.githubusercontent.com/69431456/125564601-e9c3ed5d-9bee-4202-b045-37505c774f1b.mp4

### Chakra UI Version

1.6.4

### Browser

Chrome Version 91.0.4472.124 (Official Build) (64-bit)

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by MasterGordon** [comment] 2021-07-16 20:22
@bigint You reproduction link no longer works. Maybe you could provide a codesandbox to this issue, since the example site doesn't show the causing code.

**Comment by bigint** [comment] 2021-07-17 04:25
@MasterGordon You can check now here https://devpartyio.vercel.app/, I seeded with dummy data 🤗

**Comment by MasterGordon** [comment] 2021-07-17 15:59
I think the issue is in your code thatfor some reason the recent users are getting readded/updated and there for the avatar get readded and blinks.

**Comment by bigint** [comment] 2021-07-18 03:42
@MasterGordon This happens to all react apps right? I mean calling all APIs the page has when moving to another route that is already rendered?

**Comment by bigint** [comment] 2021-07-18 03:43
I'll make simple react app and try it and get back here!!

**Comment by bigint** [comment] 2021-07-18 03:59
@MasterGordon You can see this is blinking even without an API call

https://stackblitz.com/edit/github-iavef4?file=src%2Fpages%2Findex.js


https://user-images.githubusercontent.com/69431456/126055206-3bbf72af-9339-425c-a73c-b50c77b7afd4.mov

**Comment by MasterGordon** [comment] 2021-07-18 12:16
It looks like this is an issue with the Image fallback logic not respecting cached images. For normal images you can disable this logic with the `ignoreFallback` prop but this seems not to be possible for the avatar.
I will take a look whether I can fix this issue with a PR.

**Comment by bigint** [comment] 2021-07-18 12:41
Great thanks @MasterGordon 🙏🏻 👏🏻

**Comment by segunadebayo** [comment] 2021-09-09 10:57
I just pushed a fix for this. We'll release an update shortly.

You should be able to use `ignoreFallback` prop with the `Avatar` component.

If the issue persists after upgrading, I'll re-open it.

**Closed by segunadebayo** 2021-09-09 10:57 UTC
Labels: Type: Bug 🐛, needs triage
