### ISSUE TITLE
Creating Persistent State for Drawer Component

### ISSUE THREAD

**Issue by thecodeclimber** [chakra-ui/chakra-ui#4375] opened 2021-07-13 12:28 UTC
### Description

Currently, the Drawer component covers the content on the page.  It would be nice if there was an option for it to push the content to the side (or up or down depending on which position one uses for the drawer).  Something similar to the Persistent State of the Material UI drawer:  https://material-ui.com/components/drawers/#persistent-drawer 

### Problem Statement/Justification

In general there seem to be two types of drawers in web design.  Overlay (or temporary) & Persistent.   Chakra UI Drawer component currently only allows for an overlay version.  However, there are many use cases where one wants a persistent drawer.  This is not currently possible in Chakra UI without having to make a custom drawer.  

### Proposed Solution or API

A simple proposed solution would be to add a `persistent` prop (or some other relevant name) that would change the Drawer to remain open and push the content to the side (or up or down) when the drawer is open.

**Comment by anubra266** [comment] 2021-07-19 00:12
Duplicate of Issue #608

**Closed** 2021-08-24 10:42 UTC
Labels: needs triage
