### ISSUE TITLE
Focus outline flickers on hover (Firefox Developer 98)

### ISSUE THREAD

**Issue by koundinyad** [chakra-ui/chakra-ui#5567] opened 2022-02-12 14:09 UTC
### Description

Focus outline 

### Link to Reproduction

https://codesandbox.io/s/bug-git-clone-p98de

### Steps to reproduce

Could not exactly isolate the bug and reproduce. It seems fine on codesandbox. I have attached the link to my component file and theme anyway.

![chakra_flicker_preview](https://user-images.githubusercontent.com/43331897/153714776-b6cf62c9-9d81-47a5-b481-877a62514f08.gif)

Happens only on Firefox Developer (have checked on Edge otherwise)

### Chakra UI Version

^1.8.1

### Browser

Firefox Developer 98

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by takethefake** [comment] 2022-02-16 20:08
Hej @koundinyad thanks for reporting this issue!

I've tried to reproduce it but had no success in doing so. Unfortunately, As long as I can't reproduce this it's hard to find a fix. 

I will close this issue for now but please feel free to ping me and reopen it once you can reproduce it

**Closed by takethefake** 2022-02-16 20:08 UTC
Labels: Type: Bug 🐛, needs triage
