### ISSUE TITLE
[CSSReset] When resetCSS is false, Chakra is still overriding body styles

### ISSUE THREAD

**Issue by tonyjmartinez** [chakra-ui/chakra-ui#2802] opened 2020-12-16 07:26 UTC
# 🐛 Bug report

I have `resetCSS` set to `false` in my chakra provider, but I'm still getting `body` styles overridden by chakra.

## 💥 Steps to reproduce

1. Set `resetCSS` to `false` in the chakra provider.
2. Check the styling for a piece of text and see that it's still getting body styling from chakra.

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox
https://codesandbox.io/s/strange-dhawan-phri5?file=/src/App.tsx

## 🧐 Expected behavior

Either the body styles shouldn't be overridden, or there should be a way to prevent this.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.0.3      |
| Browser          | Chrome     |
| Operating System | MacOS      |

## 📝 Additional information

<img width="462" alt="Screen Shot 2020-12-15 at 2 28 07 PM" src="https://user-images.githubusercontent.com/12503822/102317715-e6e7e480-3f2c-11eb-92df-c12735b7f0cb.png">

**Comment by with-heart** [comment] 2020-12-16 17:36
Hi @tonyjmartinez!

These styles [come from the default `theme`](https://github.com/chakra-ui/chakra-ui/blob/6a0b63dd1b0b78a1d20f46594a8948a68768c2e9/packages/theme/src/styles.ts#L3-L20) and not our CSS reset, which is why `resetCSS={false}` has no effect here. 

Unlike the styles in the reset, these are foundational to the entire design system, enabling the `theme` to apply the correct font, color mode colors, line height, and transitions for all of our built-in components. The entire component library is built with the assumption that the `theme` is used as the mechanism for managing these things and that these foundational styles are applied. While I can't say for sure because I haven't tried it myself, I think you might run into a number of inconsistencies in the visual output of Chakra components without it.

That doesn't mean that you can't control what you're doing in your own code of course, and if you'd really like to remove those entirely, you can do that [by deleting `theme.styles.global`](https://codesandbox.io/s/dazzling-bell-6ovml?file=/src/App.tsx) and passing that as `theme` to `ChakraProvider`. But I don't know that it makes sense for us to offer that as an explicit option.

**Comment by tonyjmartinez** [comment] 2020-12-16 19:01
@with-heart thanks for the detailed response. I'll try deleting the global theme like you suggested, but I'm wondering what your suggested approach is to using chakra in a medium/large app where I don't want any of the existing styles to get overridden by chakra. Is deleting the theme like this the best approach?

For example, I have a page that is 99% existing react components with their own styling, but I want to use a single chakra component. How can I introduce the chakra component without overriding any of the other styles?

**Comment by tonyjmartinez** [comment] 2020-12-16 22:05
Looks like changing the theme like this worked for me, since the font/line-heights were my main issue.

```
const customTheme = extendTheme({
  styles: {
    global: {
      body: {
        fontFamily: null,
        lineHeight: null
      }
    }
  },
```

**Comment by with-heart** [comment] 2020-12-17 11:45
That's probably the best way to go about it in that case. If you were using many parts of Chakra, I'd have suggested customizing your `theme` to match your existing design system, but since you're only trying to use a single component, that's probably not worth all the extra effort.

Going to close this as we're theoretically trying to keep our backlog clean (😆), but please feel free to respond to this if you have further issues/questions!

**Closed by with-heart** 2020-12-17 11:45 UTC

**Comment by nahumzs** [comment] 2021-11-25 03:24
I have been testing chackra in a prototype for some time now, I honestly can't understand how a simple component like the `Box component` will inject so many global styles and resets, IMHO `Styles` within the scope of a **UI library** should be agnostic and specific to the component that you want to use, having this `global` concept of styles plus forcing a reset in an application decrease heavily the chances for a serious application to adopt chackra partially.

Pretty much at this point is all in with chakra you adopt it or you don't, also even if you adopt it I can see many conflicts with third party components that you might want to use in your application, this can be brutal if you don't have access to the styles for third party components. :( 

It would be great to have a function like:

```js
import { avoidCSSInjection } from "@chackra-ui/core"

avoidCSSInjection()
```

And prevent this from happening.

**Comment by kanud** [comment] 2021-12-04 00:40
Agree with @nahumzs- my use case is to inject a chat component into existing web pages. So I'd like to restrict Chakra CSS to that component only.

**Comment by Renfrew** [comment] 2022-05-31 23:42
Are there any updates on this? It is difficult to overwrite the global style injections from the chakra when I am working on the existing codebase. I have no clue why a UI library would change components that the library does not manage. This setup limits the extendability of the project in the future and so restricts the adoption of chakra.

**Comment by shyam-whatmore** [comment] 2022-07-16 20:40
To summarize from my experience on this issue, Chakra has CSS styles in two places : 
1. The **default styles** as mentioned by @with-heart 
- loaded from [https://github.com/chakra-ui/chakra-ui/blob/6a0b63dd1b0b78a1d20f46594a8948a68768c2e9/packages/theme/src/styles.ts#L3-L20](url)
- to remove use the theme after deleting the global styles
`  delete theme.styles.global;
`

2. The **ChakraProvider specific styles**
- loaded from [https://github.com/chakra-ui/chakra-ui/blob/main/packages/css-reset/src/css-reset.tsx](url)
- to replace these by custom css use a combination of `resetCSS` and `cssVarsRoot` and create a react component with your own custom css.

```
delete theme.styles.global;
<ChakraProvider theme={theme} cssVarsRoot="#componentRootStart" resetCSS={false}>
  <MyCssReset />
  <div id="componentRootStart" className='my-css-reset'>  
       // your react component starts from here
  </div
</ChakraProvider>
```
refer original answer for this part : [https://stackoverflow.com/questions/68736105/inject-chakra-uis-global-style-with-a-specific-scope](url)

3. You might also want to add custom css for Chakra Modals and Toasts as these are injected dynamically under body, this should be easy to figure out given 2. is done.

Hope this helps.

This was very painful for us, a library injecting CSS from root level of entire html document breaks many things. But considering Chakra was designed for a uniform UX experience for end user, and implementing this as a official solution might break Chakra Portals too, it's understandable.

**Comment by Weixuanf** [comment] 2023-12-14 17:33
+1 this is really painful, I used resetScope,disableGlobalStyle but none is working. the emotion CSS is still poluting the global CSS. please fix this!!!

**Comment by Weixuanf** [comment] 2023-12-14 18:34
> * https://github.com/chakra-ui/chakra-ui/blob/main/packages/css-reset/src/css-reset.tsx

ok huge thanks to @shyam-whatmore 's great reply, i was able to figure out why the resetScope is not working as expected. because the in the code: https://github.com/chakra-ui/chakra-ui/blob/5ec0be610b5a69afba01a9c22365155c1b519136/packages/components/css-reset/src/css-reset.tsx

the  html {
        line-height: 1.5;
        -webkit-text-size-adjust: 100%;
        font-family: system-ui, sans-serif;
        .....
      }

      body {
        position: relative;
        min-height: 100%;
       ...
      }
ARE NOT SCOPED!
that's why it polluted the global CSS even thought it set resetScope=".myOwnSpecialClass"

so...the solution would be, like @shyam-whatmore copy [chakra's CSS reset](https://github.com/chakra-ui/chakra-ui/blob/5ec0be610b5a69afba01a9c22365155c1b519136/packages/components/css-reset/src/css-reset.tsx) and modify it and scope it down to your own classes, and make sure you also limit or remove the HTML, body selector.

or you just patch some extra CSS to overwrite the HTML, body CSS (not sure if it's gonna work)

I'll probably go with method one, to serve my own CSS reset....

**Comment by Weixuanf** [comment] 2024-01-09 08:04
Ok I finally find a solution to this, we were building a plugin into a parent app but the global styles chakra add polluted the global style, please refer to our pr of how we added class scope and customized CSSReset: https://github.com/11cafe/comfyui-workspace-manager/pull/88/files

ignore all .py changes it's not related. 

basically, first disable CSSReset 
in main.ts
```
    <ChakraProvider resetCSS={false} disableGlobalStyle={true}>
      <CSSReset scope=".workspace_manager" />
      <ColorModeScript />
        <App />
    </ChakraProvider>
``

in App.ts, wrap your YourApp component with:
```
      <div ref={workspaceContainerRef} className="workspace_manager">
        <Portal containerRef={workspaceContainerRef}>
            <YourApp /> 
        </Portal>
      </div>
```

listen for dom loaded to avoid color-scheme:dark leak:
```
  // remove color-scheme property from <html> element, this made the checkboxes dark
  let htmlElement = document.documentElement;
  if (htmlElement.style.colorScheme === "dark") {
    // Remove the color-scheme property
    htmlElement.style.removeProperty("color-scheme");
  }

```

in MyCSSReset.ts
```
import { Global } from "@emotion/react";

const css = String.raw;

const vhPolyfill = css`
  :root,
  :host {
    --chakra-vh: 100vh;
  }

  @supports (height: -webkit-fill-available) {
    :root,
    :host {
      --chakra-vh: -webkit-fill-available;
    }
  }

  @supports (height: -moz-fill-available) {
    :root,
    :host {
      --chakra-vh: -moz-fill-available;
    }
  }

  @supports (height: 100dvh) {
    :root,
    :host {
      --chakra-vh: 100dvh;
    }
  }
`;

export const CSSPolyfill = () => <Global styles={vhPolyfill} />;

export type CSSResetProps = {
  /**
   * The selector to scope the css reset styles to.
   */
  scope?: string;
};

const CSSReset = ({ scope = "" }: CSSResetProps) => (
  <Global
    styles={css`
      ${scope} {
        font-family: var(--chakra-fonts-body);
        color: var(--chakra-colors-chakra-body-text);
        background: var(--chakra-colors-chakra-body-bg);
        transition-property: background-color;
        transition-duration: var(--chakra-transition-duration-normal);
        line-height: var(--chakra-lineHeights-base);
      }
      ${scope} *, ${scope} ::before, ${scope} ::after {
        border-color: var(--chakra-colors-chakra-border-color);
      }

      ${scope} :where(html) {
        line-height: 1.5;
        -webkit-text-size-adjust: 100%;
        font-family: system-ui, sans-serif;
        -webkit-font-smoothing: antialiased;
        text-rendering: optimizeLegibility;
        -moz-osx-font-smoothing: grayscale;
        touch-action: manipulation;
      }

      ${scope} :where(body) {
        position: relative;
        min-height: 100%;
        margin: 0;
        font-feature-settings: "kern";
      }

      ${scope} :where(*, *::before, *::after) {
        border-width: 0;
        border-style: solid;
        box-sizing: border-box;
        word-wrap: break-word;
      }

      ${scope} :where(main) {
        display: block;
      }

      ${scope} hr {
        border-top-width: 1px;
        box-sizing: content-box;
        height: 0;
        overflow: visible;
      }

      ${scope} :where(pre, code, kbd,samp) {
        font-family: SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 1em;
      }

      ${scope} a {
        background-color: transparent;
        color: inherit;
        text-decoration: inherit;
      }

      ${scope} abbr[title] {
        border-bottom: none;
        text-decoration: underline;
        -webkit-text-decoration: underline dotted;
        text-decoration: underline dotted;
      }

      ${scope} :where(b, strong) {
        font-weight: bold;
      }

      ${scope} small {
        font-size: 80%;
      }

      ${scope} :where(sub,sup) {
        font-size: 75%;
        line-height: 0;
        position: relative;
        vertical-align: baseline;
      }

      ${scope} sub {
        bottom: -0.25em;
      }

      ${scope} :where(sup) {
        top: -0.5em;
      }

      ${scope} :where(img) {
        border-style: none;
      }

      ${scope} :where(button, input, optgroup, select, textarea) {
        font-family: inherit;
        font-size: 100%;
        line-height: 1.15;
        margin: 0;
      }

      ${scope} :where(button, input) {
        overflow: visible;
      }

      ${scope} :where(button, select) {
        text-transform: none;
      }

      ${scope} :where(
          button::-moz-focus-inner,
          [type="button"]::-moz-focus-inner,
          [type="reset"]::-moz-focus-inner,
          [type="submit"]::-moz-focus-inner
        ) {
        border-style: none;
        padding: 0;
      }

      ${scope} fieldset {
        padding: 0.35em 0.75em 0.625em;
      }

      ${scope} legend {
        box-sizing: border-box;
        color: inherit;
        display: table;
        max-width: 100%;
        padding: 0;
        white-space: normal;
      }

      ${scope} progress {
        vertical-align: baseline;
      }

      ${scope} textarea {
        overflow: auto;
      }

      ${scope} :where([type="checkbox"], [type="radio"]) {
        box-sizing: border-box;
        padding: 0;
      }

      ${scope} input[type="number"]::-webkit-inner-spin-button,
      ${scope} input[type="number"]::-webkit-outer-spin-button {
        -webkit-appearance: none !important;
      }

      ${scope} input[type="number"] {
        -moz-appearance: textfield;
      }

      ${scope} input[type="search"] {
        -webkit-appearance: textfield;
        outline-offset: -2px;
      }

      ${scope} input[type="search"]::-webkit-search-decoration {
        -webkit-appearance: none !important;
      }

      ${scope} ::-webkit-file-upload-button {
        -webkit-appearance: button;
        font: inherit;
      }

      ${scope} details {
        display: block;
      }

      ${scope} summary {
        display: list-item;
      }

      ${scope} template {
        display: none;
      }

      [hidden] {
        display: none !important;
      }

      ${scope} :where(
          blockquote,
          dl,
          dd,
          h1,
          h2,
          h3,
          h4,
          h5,
          h6,
          hr,
          figure,
          p,
          pre
        ) {
        margin: 0;
      }

      ${scope} :where(button) {
        background: transparent;
        padding: 0;
      }

      ${scope} fieldset {
        margin: 0;
        padding: 0;
      }

      ${scope} :where(ol, ul) {
        margin: 0;
        padding: 0;
      }

      ${scope} textarea {
        resize: vertical;
      }

      ${scope} :where(button, [role="button"]) {
        cursor: pointer;
      }

      ${scope} button::-moz-focus-inner {
        border: 0 !important;
      }

      ${scope} table {
        border-collapse: collapse;
      }

      ${scope} :where(h1, h2, h3, h4, h5, h6) {
        font-size: inherit;
        font-weight: inherit;
      }

      ${scope} :where(button, input, optgroup, select, textarea) {
        padding: 0;
        line-height: inherit;
        color: inherit;
      }

      ${scope} :where(img, svg, video, canvas, audio, iframe, embed, object) {
        display: block;
      }

      ${scope} :where(img, video) {
        max-width: 100%;
        height: auto;
      }

      ${scope} [data-js-focus-visible]
        :focus:not([data-focus-visible-added]):not(
          [data-focus-visible-disabled]
        ) {
        outline: none;
        box-shadow: none;
      }

      ${scope} select::-ms-expand {
        display: none;
      }

      ${vhPolyfill}
    `}
  />
);

export default CSSReset;

```

**Comment by Irrelon** [comment] 2024-11-08 14:05
The proble here is specificity. If you apply a scope to the chakra base styles e.g. ".myApp", the selectors become things like ".myApp :where(button) {...}". Then if you create a button and apply styles to it, it gets it's own component-level css class name like ".css-12343". That classname has a lower specificity than the base style so they get overridden.

Does anyone have a workaround to that?

**Comment by jgwiazdowski** [comment] 2025-03-14 16:57
any updates on this? :|
