### ISSUE TITLE
Drawer component doesn't fill the screen in certain cases

### ISSUE THREAD

**Issue by AnishDe12020** [chakra-ui/chakra-ui#5054] opened 2021-11-10 12:14 UTC
### Description

When I expected the drawer the take up the full screen, it didn't take up the whole screen, instead, a part of it

### Link to Reproduction

https://codesandbox.io/s/sad-tesla-kwbz2?file=/README.md

### Steps to reproduce

1. Go to the route `/color/gradient-generator` (production URL - [`https://devkit.vercel.app/color/gradient-generator`](https://devkit.vercel.app/color/gradient-generator), codesandbox URL - [`https://kwbz2.sse.codesandbox.io/color/gradient-generator`](https://kwbz2.sse.codesandbox.io/color/gradient-generator)
2. Open browser devtools and open mobile view on device emulation OR visit the site on a phone
3. Click on the hamburger menu icon to open the drawer

### Chakra UI Version

1.6.10

### Browser

Google Chrome 95 (Stable), Microsoft Edge 97 (Dev Channel), Google Chrome Android 95 (Stable)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Occurs on Android too
Occurs only on the `/colors/gradient-generator` router, not on the home router
Images - 
On Home Page (how it should be) - 
![image](https://user-images.githubusercontent.com/63192115/141111006-c0836b55-d148-468b-b915-b0ae38a02ee7.png)

On that specific router (**the issue**)
![image](https://user-images.githubusercontent.com/63192115/141111124-b4a7888c-943f-4f61-b24f-8daa18e8e6d4.png)

**Comment by primos63** [comment] 2021-11-11 08:23
The problem is on your Gradient page. Change the width on the Flex element from 4xl to 100%. Remove top level `Box` as it isn't necessary and enclosed the buttons at the bottom with `HStack` instead of `Flex` because it spaces the buttons automatically.
I am closing this issue as the problem appears to be within the provided code and not Chakra.
```jsx
  return (
    <Center>
      <Flex flexDir="column" w="100%">
        <Center>
          <Heading>Gradient Generator</Heading>
        </Center>

        <GradientPreview
          gradientCSS={gradient.css}
          gradientComponentRef={gradientComponentRef}
        />

        <Box mt={8}>
          <Text my={2}>Raw CSS</Text>
          <Input
            placeholder="Enter raw css. E.g: linear(to right, #ff0000, #00ff00)"
            value={gradient.css}
            onChange={e => handleCSSUpdate(e.target.value)}
          />
        </Box>
        <Box mt={4}>
          <Text>Gradient Direction</Text>
          <Slider
            min={0}
            max={360}
            value={gradient.direction}
            onChange={value => handleDirectionUpdate(value)}
            focusThumbOnChange={false}
          >
            <SliderTrack>
              <SliderFilledTrack bgGradient={gradient.css} />
            </SliderTrack>
            <SliderThumb bgGradient={gradient.css}></SliderThumb>
          </Slider>
        </Box>
        <Grid templateColumns="repeat(2, 1fr)" gap={6}>
          {gradient.colors.map((color, index) => (
            <Color
              color={color}
              index={index}
              key={index}
              handleColorUpdate={handleColorUpdate}
            />
          ))}
        </Grid>
        <Button onClick={handleAddColor} mt={8}>
          Add Color
        </Button>

        <chakra.hr mt={4} />

        <HStack mt={4}>
          <ExportAsUrl
            colors={gradient.colors}
            direction={gradient.direction}
          >
            Export URL
          </ExportAsUrl>
          <CSSModal
            colors={gradient.colors}
            direction={gradient.direction}
          >
            Copy CSS
          </CSSModal>
          <ExportAsPng gradientComponentRef={gradientComponentRef} />
        </HStack>
      </Flex>
    </Center>
  );
```

**Closed by primos63** 2021-11-11 08:23 UTC
Labels: Type: Bug 🐛, Topic: Design and UX ✍️

**Comment by AnishDe12020** [comment] 2021-11-11 10:02
Thanks a lot for the help, everything works now :smile:
