### ISSUE TITLE
Various theming not working at 1.6.6

### ISSUE THREAD

**Issue by tony** [chakra-ui/chakra-ui#4675] opened 2021-09-05 19:39 UTC
### Description

When I upgraded to 1.6.5 -> 1.6.6 on a large monorepo gatsby project, bg colors and various other theming things stopped working

### Link to Reproduction

My code base is private and there are too many moving parts

### Steps to reproduce

1. Upgrade from 1.6.5 to 1.6.6
2. Start gatsby as usual
3.  `bg` in <Box>` doesn't swap out
    ![image](https://user-images.githubusercontent.com/26336/132139265-066aaf6e-3955-46ba-bcf9-4a4392757c64.png)

  Expect to see `var(--chakra-colors-blue-700)`

### Chakra UI Version

1.6.6

### Browser

chrome 93

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I'm not sure if it's best to close this or not.  I have a non open source project and its not feasible to create an MVP. 

Did anything change in the past few weeks that make `<Box bg='blue.700'>` not switch out colors?

**Comment by tony** [comment] 2021-09-05 19:42
I'm not sure if it's best to close this or not.  I have a non open source project and its not feasible to create an MVP.

Did anything change in the past few weeks that make `<Box bg='blue.700'>` not switch out colors?

**Comment by tony** [comment] 2021-09-05 19:46
It's okay to close this if there's no hints or anyone else experiencing this.  I shot myself in the foot because between using themes, a monorepo, gatsby - there's too many points of failure to identify why `blue.700` won't turn into `var(--chakra-colors-blue-700)`

**Comment by RIP21** [comment] 2021-09-06 15:50
I have similar issue, but it simply uses `var(--chakra-colors-grey-100)` for Button background while I have such theme config.
```
    components: {
      Button: {
        baseStyle: {
          fontWeight: "bold",
          borderRadius: "lg",
          p: 4,
          color: 'white',
          bg: "gray.900",
        },
      },
    },
```
In ` root:` I can clearly see `gray.900` available with the right color from theme.

**Comment by tony** [comment] 2021-09-06 17:13
@RIP21 Any more clues on your environment / setup?  

In my case I have a gatsby monorepo w/ typescript and multiple `theme.ts` shared across packages. Chakra-UI theming and components is spread across my main gatsby site as well as monorepo packages.

**Comment by RIP21** [comment] 2021-09-06 17:17
@tony Simple CRA and SPA. 0 components from Chakra were used in the whole project, just wrapped the whole thing in ChakraProvider with new extended theme :D I just started migration and encountered this issue.
`yarn` v1, so nothing unusual.

**Comment by tony** [comment] 2021-09-06 17:28
> @tony Simple CRA and SPA. 0 components from Chakra were used in the whole project, just wrapped the whole thing in ChakraProvider with new extended theme :D I just started migration and encountered this issue.
> `yarn` v1, so nothing unusual.

Perhaps then it'll be easier to do a codesandbox reproduction.   That's the part I'm missing. though we don't know if we have the same underlying issue yet

aside: wonder if this is related in any way to #4672

**Comment by RIP21** [comment] 2021-09-06 17:31
@tony here is repro
https://codesandbox.io/s/dry-field-5xztl?file=/src/index.tsx

**Comment by tony** [comment] 2021-09-06 17:56
with 1.6.7 (from @RIP21): https://codesandbox.io/s/dry-field-5xztl?file=/src/index.tsx

Interesting how passing `bg` in directly works: https://codesandbox.io/s/festive-dirac-4pg3s?file=/src/index.tsx

**Comment by RIP21** [comment] 2021-09-06 18:27
@tony any idea which version is working as expected? Really doing the core of the theme now and these issues don't help much :D

**Comment by tony** [comment] 2021-09-06 18:47
@RIP2

> @tony any idea which version is working as expected? Really doing the core of the theme now and these issues don't help much :D

Stumped. Here's various things I've tried.

By the way, 1.6.5 fixes _my_ issue, but doesn't change anything in your sandbox: https://codesandbox.io/s/sad-cori-40mq3

**Comment by RIP21** [comment] 2021-09-06 19:37
@tony yup. I also tried decreasing the version but unfortunately, it's pretty random. Same with `size` and `variant` it may apply or may not apply.  Fix is needed ASAP :( It's really unusable now.

**Comment by tony** [comment] 2021-09-06 19:55
@RIP21 Nothing I've done fixes the code sandbox. Maybe the docs are different?  So far I don't see any similar issues other than #4672

**Comment by takethefake** [comment] 2021-09-06 20:56
Hej @tony @RIP21 

Regarding the provided code sandbox, you may didn't factor into account, that `baseStyle` is not always the resulting style, since chakra applies the concept of `variants`.

Since the `Button`-Component has the default `variant`: `solid` the `solid`-styles are applied onto the base styles which results in your described behavior.

A good approach to ensure that your styles are applied is by styling a variant instead, or by defining a dedicated variant for your use case.

See attached code sandbox for clarification: https://codesandbox.io/s/affectionate-engelbart-9rxou?file=/src/index.tsx

Does this solve your questions regarding theming?

**Comment by RIP21** [comment] 2021-09-06 21:23
@takethefake ok. That makes sense. I try, tho to change size of the IconButton using `h` and `w` props in `sizes` and it doesn't seem to obey.

```
export const IconButton = {
  baseStyle: {
    borderRadius: 'lg',
  },
  sizes: {
    xs: {
      h: '1.5rem',
      w: '1.5rem',
    },
    sm: {
      h: '2rem',
      w: '2rem',
    },
    md: {
      h: '3rem',
      w: '3rem',
    },
    lg: {
      h: '3.5rem',
      w: '3.5rem',
    },
  },
}
```
I guess the default `solid` variant overrides that or smth similar, but then the question is how to overcome that behavior when the variant really changes the size of something, like a border size or font size?

**Comment by RIP21** [comment] 2021-09-06 21:37
I already tested with exactly the same shapes, but bigger, `sizes` object that Chakra has by default, but it doesn't seem to work either. Passing any of these sizes to `sx` works.
```
  sizes: {
    lg: {
      h: 14,
      minW: 14,
      fontSize: "lg",
      px: 6,
    },
    md: {
      h: 12,
      minW: 12,
      fontSize: "md",
      px: 4,
    },
    sm: {
      h: 9,
      minW: 9,
      fontSize: "sm",
      px: 3,
    },
    xs: {
      h: 6,
      minW: 6,
      fontSize: "xs",
      px: 2,
    },
  },
```

Here is the code
https://codesandbox.io/s/jovial-haslett-cgm2c

**Comment by tony** [comment] 2021-09-06 21:45
@takethefake I think this may solve @RIP21's question, but doesn't solve my original issue of `blue.700` not being swatched out.  In my case I don't have variants.

**Comment by takethefake** [comment] 2021-09-06 22:21
@RIP21 could you create a separate issue, since otherwise, the discussion would be kind of hard to get for someone not involved in this yet.

@tony could you narrow your problem down so that we have a codesandbox to talk about?

**Comment by tony** [comment] 2021-09-07 00:43
@takethefake

I'm having a difficulty creating a reproduction. I've spent 5+ hours today. Perhaps it's unique to my case

https://github.com/tony/gatsby-chakra-mvp

maybe we close this for now and see if anyone else chimes in with an MVP (or a less complicated project than mine?)

**Comment by takethefake** [comment] 2021-09-07 06:46
@tony thanks for putting all this effort into this, but since reproduction seems to be so difficult, I guess that this is the result of a combination of errors, why it is quite difficult and time-intensive to handle on our side. That's why I would close this issue for now. 

If you or someone else somehow finds a way to reproduce this in an easy way, feel free to reach out and we'll do our best to help.

So long, I wish you all the best in the further development of the project!

**Closed by takethefake** 2021-09-07 06:46 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by tony** [comment] 2021-09-07 16:17
@takethefake  Thanks!  In my case I'm in a similar position where it's intensive to create a reproduction.

If anyone else comes upon this issue and you can get us closer to a reproduction, please create a fresh issue and link/comment to to this.   In my case `blue.700` and various other theming stopped being processed after 1.6.5.  My setup is complex enough it's difficult to find out where the issue is at
