### ISSUE TITLE
Intellisense not working on pseudo classes

### ISSUE THREAD

**Issue by ninoM** [chakra-ui/chakra-ui#7034] opened 2022-11-24 16:56 UTC
### Description

When I use any pseudo prop on Chakra compoments, intellisense doesn't work
<img width="316" alt="image" src="https://user-images.githubusercontent.com/2021570/203834446-bf3cc7be-0567-4a92-88fd-8a7d1ef136ff.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/2021570/203834600-d18a9def-04a8-4de7-bb52-b7225dd7869a.png">

### Link to Reproduction

https://codesandbox.io/s/adoring-stallman-5gqr2q

### Steps to reproduce

1. In VSCode, create a new project with Chakra
2. Add a pseudo prop on any Chakra component (like _hover)
3. Pass in an object in the _hover (or any pseudo prop with a key `background` in this instance
4. For value of `background` pass in a string with a Chakra color value. We'll try to type in 'purple.100'
5. Try to type 'purple.' then prompt for a suggestion. Nothing will appear

### Chakra UI Version

2.4.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2023-04-24 21:37
Duplicate of #6261

**Closed by segunadebayo** 2023-04-24 21:37 UTC
Labels: Topic: TypeScript 🤠
