### ISSUE TITLE
Input is applying focus-visible styles even when it receives focus via mouse (overwriting focus styles)

### ISSUE THREAD

**Issue by mcha-dev** [chakra-ui/chakra-ui#3915] opened 2021-04-26 02:35 UTC
# 🐛 Bug report

`<Input />` is picking `focus-visible` styles even when it receives focus via mouse

## 💥 Steps to reproduce

1. apply styles (focus & focus-visible) to different elements (i.e. select & input)
2. watch as select works as expected (styles differ per focus) while input always applies focus-visible

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/immutable-river-kj9vt?file=/src/index.tsx

## 🧐 Expected behavior
focusVisible applied on keyboard only (as in the Select case in the codesandbox above).

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.6      |
| Browser          |        Firefox    |
| Operating System |   mac OS         |

## 📝 Additional information

Might be related to #2234 I opened this one to follow the template & provide codesandbox link

**Comment by with-heart** [comment] 2021-04-26 11:12
> Might be related to #2234 I opened this one to follow the template & provide codesandbox link

Close! But imo this a duplicate of #3449. Going to close this one since that's already open.

**Closed by with-heart** 2021-04-26 11:12 UTC

**Comment by mcha-dev** [comment] 2021-04-26 11:22
I don't think those issues are the same. As you can see in the codesandbox provided, the `<Select />` element is behaving correctly. It is only the `<Input />` element that's overwriting `_focus` styles with `_focusVisible`
