### ISSUE TITLE
Menu won't close

### ISSUE THREAD

**Issue by davidbarker** [chakra-ui/chakra-ui#3969] opened 2021-05-07 20:41 UTC
# 🐛 Bug report

Menu will open on click, but then doesn't close when either clicking on button for a second time, clicking outside of the menu, or pressing escape.

## 💥 Steps to reproduce

1. Copy first Menu example from documentation
2. Click on Menu button to open the menu
3. Try closing the menu
4. Menu does not close

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-ui-menu-wont-close-nn48m

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.6.1           |
| Browser          | Chrome            |
| Operating System | macOS           |

**Comment by JClackett** [comment] 2021-05-07 21:54
Duplicate of this: https://github.com/chakra-ui/chakra-ui/issues/3967

**Comment by davidbarker** [comment] 2021-05-07 21:58
Ah, yes. I did search but didn't find that one — thanks!

**Closed** 2021-05-11 17:18 UTC
