### ISSUE TITLE
Store Dark Mode preferences in Local Storage

### ISSUE THREAD

**Issue by deadcoder0904** [chakra-ui/chakra-ui#892] opened 2020-06-19 08:33 UTC
So I can refresh the Chakra UI website & not lose my preferences. Right now, everytime I refresh it takes me back to light mode.

**Comment by diego81b** [comment] 2020-06-19 15:23
Hi @deadcoder0904,
i'm new to chakra-ui so i made a workaround.

On your root component do something like this:
```
const App: React.FC = () => {
  const [appState, setAppState] = React.useState<AppState>({ loading: false, authenticated: false });
  const { colorMode, toggleColorMode } = useColorMode();
  React.useEffect(
    () => {
      if (colorMode === 'light') {
        toggleColorMode();
      }
    },
    [colorMode, toggleColorMode],
  );
  return !!appState.loading ? <h2>Loading...</h2> : (
    <Router>
      <Switch>
        <Route exact path="/" component={Home}></Route>
        <PrivateRoute path="/chat" authenticated={appState.authenticated}>
          <Chat />
        </PrivateRoute>
        <PublicRoute path="/login" authenticated={appState.authenticated}>
          <Login />
        </PublicRoute>
      </Switch>
    </Router>
  );
};
```

idk if it's the right way but it works
bye

**Comment by diego81b** [comment] 2020-06-19 15:42
another way, was to create a component like this (not necessary)

```
import * as React from 'react'
import { ColorModeProvider, CSSReset, ThemeProvider } from '@chakra-ui/core'
import { customTheme } from "../custom-theme"

export const DarkModeTheme: React.FC = ({ children }) => {
  return (
    <ThemeProvider theme={customTheme}>
      <ColorModeProvider value="dark" >
        <CSSReset />
        {children}
      </ColorModeProvider>
    </ThemeProvider>)
}
```

and use as:

```
ReactDOM.render(
  <React.StrictMode>
    <DarkModeTheme>
      <App />
    </DarkModeTheme>
  </React.StrictMode>,
  document.getElementById('root')
);
```

**Comment by deadcoder0904** [comment] 2020-06-20 04:48
No, I am not asking a solution for me. It's for the Chakra UI website itself. If I selected dark mode; then on refreshing, it goes back to light mode.

**Comment by with-heart** [comment] 2020-06-27 23:57
This issue is fixed in 1.0. You can see it in effect at https://next.chakra-ui.com/.

**Closed by with-heart** 2020-06-27 23:57 UTC

**Comment by deadcoder0904** [comment] 2020-06-28 04:55
@with-heart There's a little issue when I refresh, it shows light mode for a few seconds then reverts back to dark mode. I don't think it can be solved though, correct?

**Comment by with-heart** [comment] 2020-06-28 05:41
@deadcoder0904 it does that right now, but it's something we're investigating in #908

**Comment by deadcoder0904** [comment] 2020-06-28 07:09
Yeah sure but why close the issue then?

**Comment by with-heart** [comment] 2020-06-30 01:19
The problem is unfortunately not related to this issue, which has been resolved. @remorses left a fairly detailed comment on that PR explaining what the issue with the flash is: https://github.com/chakra-ui/chakra-ui/pull/908#issuecomment-648881758

We spent some time investigating earlier today and there likely isn't a viable solution to this issue at this time. `theme-ui` "solved" this by using css variables for colors, but we don't believe that can work for our system because we don't use a pre-defined set of role-named colors like they do (`primary`, `secondary`, `text`, etc.) and because we allow color mode to affect **anything** in our system and not just colors.

**Comment by deadcoder0904** [comment] 2020-06-30 04:06
So if I understand, hypothetically to make this work, Chakra UI must use CSS Variables which would require a complete rewrite, right?

**Comment by jacksonet00** [comment] 2021-04-16 20:58
If you are getting this issue it may be because you have useSystemColorMode = true. To my knowledge, in the current version of Chakra when you navigate to a new route it will prefer system color over the cached color selection. 

IMO this is a bad implementation. It should prefer the system color mode until the user requests a version and then it should make user input the preference.

**Comment by deadcoder0904** [comment] 2021-04-17 01:29
> IMO this is a bad implementation. It should prefer the system color mode until the user requests a version and then it should make user input the preference.

I thought this is what everyone does. If Chakra is going the opposite way, then I agree it's a bad implementation :)
