### ISSUE TITLE
Can't move slider more than once

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#3055] opened 2021-01-14 14:11 UTC
# 🐛 Bug report

After version `1.1.4` the Slider stopped working as expected. Now, if you slide it, and then try to do it again it simply stuck and don't move anymore.

I've tested with `1.1.2` and the issue does not exist. (Unfortunatelly, I was not able to test with `1.1.3` since it was a botched release).

## 💥 Steps to reproduce

Open the minimal reproduction (or even the docs), slide the Slider and them try to do it again.

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-slider-stucking-kz23j?file=/src/App.tsx

## 🧐 Expected behavior

We should be able to slide the Slider more than once.

**Comment by with-heart** [comment] 2021-01-14 14:38
Closing as a duplicate of #3040

**Closed by with-heart** 2021-01-14 14:38 UTC
Labels: Type: Bug 🐛
