### ISSUE TITLE
Menu incorrectly triggers page scroll on hover

### ISSUE THREAD

**Issue by jesstelford** [chakra-ui/chakra-ui#5636] opened 2022-02-21 02:39 UTC
### Description

When I hover over a `<Menu>` which is partially off-screen, the page is scrolled. I don't expect the page to ever scroll when hovering on a `<MenuItem>`.

### Link to Reproduction

https://codesandbox.io/s/dawn-bash-516v70?file=/src/index.js

### Steps to reproduce

1. Click to open the menu
2. Resize your browser so the menu goes off the bottom of the screen, but the top is visible:
    * ![Screenshot from 2022-02-21 13-19-10](https://user-images.githubusercontent.com/612020/154878424-bc065659-570c-4725-b963-7d1a12f4397b.png)

2. Hover over any menu item
3. Notice the page scrolls *(this is unexpected behaviour)*.
4. Scroll the page so the menu goes off the _top_ of the screen, but the bottom is visible:
    * ![Screenshot from 2022-02-21 13-22-31](https://user-images.githubusercontent.com/612020/154878716-44a26a49-87cd-4058-a481-dd3b55ce42ff.png)
5. Hover over any menu item
6. Notice the page scrolls *(this is unexpected behaviour)*.
7. Scroll the page so _both_ the top and bottom go off the screen:
    * ![Screenshot from 2022-02-21 13-27-21](https://user-images.githubusercontent.com/612020/154879117-26c49e98-7c6c-43cf-b110-926bf61c5f5a.png)
8. Hover over any menu item
9. Notice there is no scrolling *(this is the correct behaviour)*.
10. Resize your browser so the full menu fits on the screen (but so there's still some vertical scroll):
    * ![Screenshot from 2022-02-21 13-29-23](https://user-images.githubusercontent.com/612020/154879292-3509bf31-cd60-4655-90ae-a31a26b32809.png)
11. Hover over any menu item
12. Notice there is no scrolling *(this is the correct behaviour)*.

### Chakra UI Version

1.8.5

### Browser

Brave 1.35.101 (Chromium: 98.0.4758.87)

### Operating System

- Linux

### Additional Information

I couldn't reproduce the bug in Firefox v97.

Some debugging reveals the culprit as `preventScroll: false` here:

https://github.com/takethefake/chakra-ui/blob/main/packages/menu/src/use-menu.ts#L629-L631

Looks like this was introduced in https://github.com/chakra-ui/chakra-ui/pull/4514/files#diff-6c4aefbd3ea81ddacf70475aa13274ae14fbcc6609044c74a25c45f12bd9ff4eR616 to make the keyboard scrolling support better.

I wonder if there's a better way to fix keyboard support? Or, perhaps alternatively; is there a way we can handle the hovering without having to re-focus every time?

**Comment by Alfxjx** [comment] 2022-02-24 07:14
```tsx
 <MenuList h={40} sx={{overflow:"scroll"}}>
  {Array.from(Array(20)).map((_, index) => (
    <MenuItem>Item {index + 1}</MenuItem>
  ))}
</MenuList>
```
this may help, using a scrollable menuList

**Comment by Alfxjx** [comment] 2022-02-24 07:14
```tsx
 <MenuList h={40} sx={{overflow:"scroll"}}>
  {Array.from(Array(20)).map((_, index) => (
    <MenuItem>Item {index + 1}</MenuItem>
  ))}
</MenuList>
```
this may help, using a scrollable menuList

**Comment by jesstelford** [comment] 2022-04-16 10:47
Still a bug.

**Comment by LachlanCourtSPP** [comment] 2022-05-03 01:53
I am also having a similar issue. I have taken to wrapping the children in an autoscrolling container but this seems like it should be unnecessary and should not be affecting the page scroll like this

**Comment by LachlanCourtSPP** [comment] 2022-05-17 10:13
Hey @jesstelford I just checked back on this to see if there was any progress and noticed your code sandbox doesn't compile anymore, looks like the latest Chakra relies on React 18.1.0 but you have your version pinned. Original bug still there tho :(

**Comment by cwhenderson20** [comment] 2022-06-08 22:35
I'm also having this issue, and unfortunately, at least for me, setting a max height + overflow:scroll doesn't completely fix the problem. My menu itself still scrolls to the bottom, showing the last `x` items instead of the first.

https://user-images.githubusercontent.com/5496110/172728548-c4346418-b665-4d87-9567-18ed89d37bb2.mov

Confirmed in both Safari 15.4 and Firefox 101.

**Comment by cwhenderson20** [comment] 2022-07-10 15:17
Still an issue. Pinging to keep the bot away.

**Comment by l3szcz** [comment] 2022-08-13 08:50
Still an issue.

**Comment by muhazzib** [comment] 2022-08-19 12:48
One workaround is that you can close the menu item using onMouseLeave event.

```
  return (
    <Menu>
    {({ isOpen, onClose }) => (
      <>
        <MenuButton isActive={isOpen} as={Button} rightIcon={<ChevronDownIcon />}>
          {isOpen ? 'Close' : 'Open'}
        </MenuButton>
        <MenuList onMouseLeave={onClose}>
          <MenuItem>Download</MenuItem>
          <MenuItem onClick={() => alert('Kagebunshin')}>Create a Copy</MenuItem>
        </MenuList>
      </>
      )}
     </Menu>
  );
```


Demo:

https://user-images.githubusercontent.com/25737000/185621379-151d02a7-edb8-4f2e-b346-56579a231184.mp4

**Comment by mattstobbs** [comment] 2022-11-24 10:42
Still looks like it's an issue

**Comment by fdFloresMarquez** [comment] 2023-01-25 15:15
I noticed when using scroll-padding in my css for my navbar, it's scrolls up when hover and when clicking. I removed it and it fixed it. Still scrolls up when closing the menu tough.

**Comment by pearcircuitmike** [comment] 2023-04-23 13:22
I'm still seeing this issue. Crazy as it makes this component semi-unusable!

**Comment by segunadebayo** [comment] 2023-04-24 21:49
This has already been fixed in one of the recent commits. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.

**Closed by segunadebayo** 2023-04-24 21:49 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by villesau** [comment] 2023-08-18 17:07
@segunadebayo this is still a problem with the latest ChakraUI. Even when the menu is closed, it overflows and the whole screen scrolls.

**Comment by asimplify** [comment] 2023-10-14 14:36
The issue still persists but was able to find a workaround, just need to add a condition in menuList:
`  <MenuList
          display={isOpen ? "block" : "none"}`

**Comment by sniemeyer13** [comment] 2025-02-18 23:21
I am still seeing this issue as well. If I leverage @villesau's workaround it stops jumping, however ideally our scrollbar is on our page and not the menu itself.
