### ISSUE TITLE
No colormode in text and layer styles

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#3451] opened 2021-02-25 05:56 UTC
# 🐛 Bug report

```js
const overrides = extendTheme({
  layerStyles: {
    card: (props) => ({  
        color: mode("gray.800", "whiteAlpha.900")(props),
        bg: mode("white", "gray.800")(props), 
    }),
  },
})
```
Does not work, `colorMode` is not available in  props.

**Comment by dodas** [comment] 2021-02-25 16:05
Closing as a duplicate of #2231.
You can use a workaround like this:
```js
const theme = {
  layerStyles: {
    yourStyle: {
      bg: "red.500",
      ".chakra-ui-dark &": {
        bg: "red.300",
      },
    },
  },
}
```

**Closed by dodas** 2021-02-25 16:05 UTC
