### ISSUE TITLE
Error while using Nextjs with Chakra-ui  

### ISSUE THREAD

**Issue by traitimtrongvang** [chakra-ui/chakra-ui#7889] opened 2023-07-26 00:41 UTC
### Description

I follow the document and got this error

./node_modules/@chakra-ui/react/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.

### Link to Reproduction

nope

### Chakra UI Version

^2.8.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2023-07-26 21:28
Duplicate of #7878

**Closed by segunadebayo** 2023-07-26 21:28 UTC
