### ISSUE TITLE
ComponentWithAs does not infer types

### ISSUE THREAD

**Issue by yotam707** [chakra-ui/chakra-ui#4411] opened 2021-07-19 05:29 UTC
### Description

When I set properties that do not exist on the button, typescript does not let me know that this property does not exist. 

### Link to Reproduction

https://codesandbox.io/s/chakra-button-ts-vz67b?file=/src/index.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I created a custom button with additional abilities and type inference is not working, I can assign any prop that I want and typescript does not warn me about it.

**Comment by TimKolberger** [comment] 2021-07-21 18:40
Thanks for taking the time to open an issue for this! 

There are some good approaches in the wild for an "isomorphic as prop".
We do have this on our radar for a major release sometime in the future.

Closing this as duplicate of https://github.com/chakra-ui/chakra-ui/issues/4037

**Closed by TimKolberger** 2021-07-21 18:41 UTC
Labels: Type: Bug 🐛, needs triage
