### ISSUE TITLE
FormControl behaviour

### ISSUE THREAD

**Issue by cezarneaga** [chakra-ui/chakra-ui#2142] opened 2020-10-02 12:04 UTC
# Bug report

## Describe the bug

inside ...
```
<FormControl isInvalid={condition}>
  <FormLabel>Label</FormLabel>
  <FormHelperText>some text</FormHelperText>
  <Input some input/>
</FormControl>
```
if condition is true the FormHelperText is removed from dom.
this shouldnt be the case. 

## Expected behavior  
`aria-describedby` should be moved from FormHelperText to the FormErrorMessage but the other should remain there.

## System information

- OS: macOS
- Version of @chakra-ui/core: 1.0.0-rc.5
- Version of Node.js: 12

**Comment by dodas** [comment] 2020-12-10 01:43
https://github.com/chakra-ui/chakra-ui/issues/2365 is duplicate of this one and since that one is more active, I will close this.

**Closed by dodas** 2020-12-10 01:43 UTC
Labels: Type: Bug 🐛
