### ISSUE TITLE
Slider onChangeEnd doesn't get triggered when clicking and triggered twice when dragging

### ISSUE THREAD

**Issue by j-dominguezp** [chakra-ui/chakra-ui#3860] opened 2021-04-20 03:08 UTC
# 🐛 Bug report
 
Slider onChangeEnd event doesn't get triggered when clicking in the slider track.
Also, when dragging event gets triggered twice (at start and at the end).

## 💥 Steps to reproduce

1. Add console.log to onChangeEnd event. 
2. Click anywhere in the slider tack without touching the Slider Thumb.
3. Check logs, you'll see onChangeEnd doesn't get trigerred.
4. Drag the Slider Thumb from any position to any position.
5. Check logs, you'll see onChangeEnd gets triggered twice.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/nervous-almeida-pzbmm?file=/pages/index.tsx

![slider issue](https://user-images.githubusercontent.com/53125581/115479495-81776d80-a216-11eb-8225-1629667fee86.gif)

## 🧐 Expected behavior

1. onChangeEnd event should get triggered when clicking any position of the slider track.
2. When dragging onChangeEnd event should get triggered only at the end of the dragging.

## 🌍 System information

| Software         | Version(s)                        |
| ----------------| --------------------------- |
| Chakra UI        |                                1.6.0 |
| Browser          |        Edge Dev 91.0.852.0 |
| Operating System |              Windows 10 |

## 📝 Additional information

Also tested this in Firefox and Chrome, is happening too.

Any way I can provide more information let me know. :)

**Comment by j-dominguezp** [comment] 2021-04-20 13:57
Kind of weird, it works now. 

Changed nothing. I'll close this one.

**Comment by j-dominguezp** [comment] 2021-04-21 00:15
Reopened this one as I reproduced it again.

Thought it was working, but it was a weird error in the sandbox not using the latest version of chakra.

**Comment by ProxyJoshua** [comment] 2021-04-24 20:54
I'm having the same problem, don't know why is happening

**Comment by j-dominguezp** [comment] 2021-04-24 21:07
> I'm having the same problem, don't know why is happening

Yes, still happening.

Sadly, I haven't found a workaround for this.

This is my use case:

I have a form where I need to go into the next step of the form right after the onChangeEnd event fires.

But as the event is triggered at the start and end users can't event drag the slider when they are moved into the next step.

And when clicking event doesn't trigger, so it's kind of weird :(

**Comment by nollidnosnhoj** [comment] 2021-04-27 01:32
I am getting the same issue as well: https://codesandbox.io/s/confident-jackson-zlg17?file=/src/App.tsx but I'm using Chakra 1.6.0

**Comment by segunadebayo** [comment] 2021-04-29 12:33
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Closed by segunadebayo** 2021-04-29 12:33 UTC

**Comment by pedrozaalex** [comment] 2021-08-12 03:46
I'm sorry to say it, but I believe that the problem persists: https://codesandbox.io/s/aged-browser-4df3l?file=/src/App.js

**Comment by nollidnosnhoj** [comment] 2021-08-12 10:28
This seems to be a regression bug. It works on 1.6.5 (doesnt on 1.6.6) https://codesandbox.io/s/damp-sea-7oc2x

**Comment by aagwali** [comment] 2021-08-13 20:44
Hello,
Same behavior for me in 1.6.6

Using 1.6.5 it works, except when going from a boundary to 50% : 

from any %, click on 50% => onChangeEnd is triggered correctly 
100% click on 50% => no Event triggered
0% click on 50% => no Event triggered

Not sure if its related to 1.6.6 bug
