### ISSUE TITLE
Fast clicking NumberInput on Safari causes unwanted selection

### ISSUE THREAD

**Issue by jkleiser** [chakra-ui/chakra-ui#19] opened 2019-09-05 13:26 UTC
When I rapidly click the up/down controls of the NumberInput samples at https://chakra-ui.com/numberinput in macOS Safari, I get wide selections, i.e. light blue areas across the window. This fast clicking seems to be handled as double-clicks. I'm using macOS 10.14.6 and Safari 12.1.2.
I did not see the same effect in Chrome or Firefox.

**Comment by segunadebayo** [comment] 2019-09-05 19:22
I'll look into this @jkleiser . Your contribution is also welcome

**Comment by devanshj** [comment] 2019-09-06 12:55
I was also able to reproduce this issue on chrome desktop, for me the PR fixes this. @jkleiser Can you test the PR [here](https://deploy-preview-26--chakra-ui.netlify.com/?path=/story/numberinput--default) if the issue is fixed on Safari.

**Comment by jkleiser** [comment] 2019-09-06 13:06
In the storybook the problem is gone, in my macOS Safari. ;-)

**Comment by segunadebayo** [comment] 2019-09-06 14:24
Thanks for looking into this @devanshj .

**Closed by segunadebayo** 2019-09-06 14:24 UTC
