### ISSUE TITLE
[Accordion] Removing an open AccordionItem from the DOM causes another item to open

### ISSUE THREAD

**Issue by vsylvestre** [chakra-ui/chakra-ui#4490] opened 2021-07-28 20:44 UTC
### Description

When an open AccordionItem is removed from the DOM, I would expect that it have no impact on other items under Accordion, but if there is an item following the one being removed, it will be open in its place.

### Link to Reproduction

https://codesandbox.io/s/nifty-tesla-11tul?file=/src/App.tsx

### Steps to reproduce

In the sandbox:
1. Open "Item3"
2. Click on the "Remove" button for "Item3"
3. "Item4" will now be open

### Chakra UI Version

1.6.5

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I understand that this might be a bit tricky since the defaultIndex/openIndex logic relies on indices. But would it be possible for an AccordionItem to be identified using the `id` when that prop is passed, or something like that?

**Comment by primos63** [comment] 2021-08-03 01:49
The example given doesn't remove an AccordionItem. It removes an element from an array managed by the `useState` hook which upon calling the set function will cause the component to re-render. The array is used to iteratively  populate AccordionItems. Accordion's `onChange` event handler provides an array of indices that are open and the `index` prop can be used to set which indices are open. With those two items, the appropriate removal and shifting can be accomplished. As presented in the example, the `removeItem` function only manages one aspect of the component - the data array.

[Here's a fork of the CodeSandbox example](https://codesandbox.io/s/flamboyant-leaf-65en5) showing how to manage the Accordian when the remove button is clicked.

I don't believe this is a bug with the component as it provides the functionality to manage the expansion/contraction of Accordian items.

**Comment by TimKolberger** [comment] 2021-08-05 20:44
The `Accordion` and most other chakra components can be used as controlled or [uncontrolled React component](https://reactjs.org/docs/uncontrolled-components.html). 
I think the provided codesandbox mixes the two approaches, because the AccordionItems are added/removed dynamically, without managing the state for the `index` prop.

Depending on your use case you need to choose the best fit, e.g.

### uncontrolled

```tsx
<Accordion>
  <AccordionItem>...</AccordionItem>
  <AccordionItem>...</AccordionItem>
</Accordion>
```

### controlled

```tsx
const [index, setIndex] = useState([])
const handleChange = (nextIndex) => {
  // this function can be more complex depending on your use case
  setIndex(nextIndex)
}

<Accordion index={index} onChange={handleChange}>
  <AccordionItem>...</AccordionItem>
  <AccordionItem>...</AccordionItem>
</Accordion>
```

I am closing this issue, because it is not a bug in chakra ui.

**Closed by TimKolberger** 2021-08-05 20:44 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by csandman** [comment] 2023-10-04 21:30
@primos63 thanks for this example. This is actually the direction I was thinking about heading in for my own implementation but was looking around to see if there was some way to make Chakra keep track of the list of expanded items based on their IDs instead of their indices. So thanks for getting me started haha.

I just want to point out though, in case someone else comes across this example, that your logic isn't exactly right for the `removeItem` function:

```ts
  const removeItem = (index: number) => {
    const openIndex = openItems.find((item) => item === index);

    if (openIndex) {
      const remainItems = openItems.filter((i) => i !== index);
      const shiftedItems = remainItems.map((i) => (i > index ? i - 1 : i));
      setOpenItems(shiftedItems);
    } else {
      const shiftedItems = openItems.map((i) => (i > index ? i - 1 : i));
      setOpenItems(shiftedItems);
    }

    setItems((prevItems) => {
      return prevItems.filter((_, i) => i !== index);
    });
  };
```


It just checks the truthy-ness of the index that is removed, which will give a false negative when you remove the first one. You also don't really have to check this at all, as running the filter either way is completely fine. Here's a simplified version for anyone else that comes across this:

```ts
  const removeItem = (index: number) => {
    setOpenItems((prevOpenItems) => {
      const newOpenItems = prevOpenItems.filter((i) => i !== index);
      return newOpenItems.map((i) => (i > index ? i - 1 : i));
    });

    setItems((prevItems) => {
      return prevItems.filter((_, i) => i !== index);
    });
  };
```

https://codesandbox.io/s/chakra-ui-accordion-with-remove-gyzhsz?file=/src/App.tsx:1735-2052
