### ISSUE TITLE
NumberInputField doesn't forward the ref argument down to the input

### ISSUE THREAD

**Issue by simontaisne** [chakra-ui/chakra-ui#3131] opened 2021-01-24 00:55 UTC
# 🐛 Bug report

The `NumberInputField` component doesn't forward the `ref` argument down to the `<chakra.input>` element.

Making it impossible to use with [react-hook-form](https://react-hook-form.com/) for instance.

https://github.com/chakra-ui/chakra-ui/blob/a80b8b3c28079f51f52ee779782ae16d9153ede3/packages/number-input/src/number-input.tsx#L160-L170

## 💻 Link to reproduction

https://codesandbox.io/s/angry-dew-5t6z0

## 🧐 Expected behavior

Similar to the `Input` component the value should be registered when setting `register` to the `ref`.

## 🧭 Possible Solution

By passing down the `ref` to the `input`.

```ts
return (
      <chakra.input
        {...input}
        __css={{
          width: "100%",
          ...styles.field,
        }}
      ref={ref}
      />
    )
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.1.5 |
| Browser          |  Chrome 87  |
| Operating System | macOS  |

**Comment by TimKolberger** [comment] 2021-01-24 12:01
The component `NumberInput` controls the state of the `NumberInputField` to be able to change the value with the stepper buttons. Forwarding the ref won't fix this.

Please see this example how to integrate `NumberInput` with `react-hook-form`.

https://codesandbox.io/s/chakra-ui-react-hook-form-hmgl1?file=/src/App.tsx

Closing this because it is not a bug.

**Closed by TimKolberger** 2021-01-24 12:01 UTC

**Comment by simontaisne** [comment] 2021-01-24 14:46
Thank you for explaining @TimKolberger 👍
