### ISSUE TITLE
[Component Styles] __css doesn't work on <Text /> but works on <Box />

### ISSUE THREAD

**Issue by tonyjmartinez** [chakra-ui/chakra-ui#4428] opened 2021-07-21 21:43 UTC
### Description

I'm trying to use component styles per the docs, but I'm unable to use `__css` with a `<Text />` component. I'm able to use it with a `<Box />`, but I don't see it specified in the docs that a `<Box />` is required.

### Link to Reproduction

https://codesandbox.io/s/brave-sunset-qn3tq?file=/src/index.tsx

### Steps to reproduce

1. Go to reproduction
2. See that the `<Box />` applies the `__css` styling, but the `<Text />` doesn't.

### Chakra UI Version

1.6.4

### Browser

Google Chrome 92

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TimKolberger** [comment] 2021-07-22 17:07
The `__css` prop is used internally by the Chakra components to attach styles with the lowest priority to an chakra element.

If you want to attach a style object to a Chakra component like `Text`, `Select` etc. [use the `sx` prop](https://chakra-ui.com/docs/features/the-sx-prop). The `__css` prop is used as an internal API there and cannot be overridden.

If you are creating your own reusable component with chakra elements like `<chakra.p />` you can use the `__css` prop there, and allow the using side to pass the `sx` prop to merge-override the styles.

The `Box` component is basically just `<chakra.div />` this is why it works there.

https://github.com/chakra-ui/chakra-ui/blob/f87952017be210cd6f0f22823a9f28027ab558df/packages/layout/src/box.tsx#L18

Closing this as it is not a bug in chakra - feel free to ask follow up questions :)

**Closed by TimKolberger** 2021-07-22 17:07 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by tonyjmartinez** [comment] 2021-07-22 17:36
@TimKolberger thanks for the response. However, I'm using component styles and the docs show using `__css` for component styles. `sx` wasn't working for me when using component styles. Any suggestions there?

**Comment by TimKolberger** [comment] 2021-07-22 18:02
There are two different layers where things can go wrong with styling.

1. Your style props/objects aren't processed by emotion, because they never get there. 
    This happens if you apply the `__css` prop to components like `Select`, `Input` etc.
    It does not matter, where your styles are coming from (`useStyleConfig`, `{ margin: '4' }`, ...).
    I am debugging this by applying a very noticeable style like `{ border: '4px solid red !important' }` - good old `console.log` of CSS 
2. The **Cascading** in CSS is hitting again. Check in you Browsers Dev Tools if the CSS properties are overridden by another style.

The `sx` prop has the highest priority in the chakra styled system, so it will eliminate option 1 from above.
You can see the hierarchy here:

https://github.com/chakra-ui/chakra-ui/blob/9f404f3261c60c20d16aca1ee8d1f043d7dd464e/packages/system/src/system.ts#L45-L51

If you can provide a reproduction in a codesandbox I'll take a look.

**Comment by tonyjmartinez** [comment] 2021-07-22 20:18
@TimKolberger thanks! That makes a lot of sense, I think my issue with `sx` was on my end, with the inability to add style props along with `sx`, like this `<Button sx={...} ml="20px" />`.

One last question though. Should the docs use `sx` for component styles if we aren't able to use `__css` to override styles for all components?
