### ISSUE TITLE
[Tooltip] Tooltip is not showing up when used inside a Modal

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#1604] opened 2020-08-10 16:49 UTC
Trying with version 0.8.0.

Tried by giving higher z-index as well, but tooltip doesn't seem to be working inside Modal. Any fix or workaround?

**Comment by santialbo** [comment] 2020-08-13 08:35
It would help if you provided a codesanbox reproducing the issue.

**Comment by ganeshkrishnasharma** [comment] 2020-08-13 14:33
@santialbo here you go! 
[https://codesandbox.io/s/chakra-ui-modal-tooltip-u9j9i?file=/src/App.js](url)

**Comment by ganeshkrishnasharma** [comment] 2020-08-13 14:34
@santialbo here you go!

https://codesandbox.io/s/chakra-ui-modal-tooltip-u9j9i?file=/src/App.js

**Comment by ljosberinn** [comment] 2020-08-13 14:39
![image](https://user-images.githubusercontent.com/29307652/90148359-8af52f80-dd83-11ea-9992-34376275a402.png)
more context - seems to be missing `z-index: 1`?

**Comment by jmiazga** [comment] 2020-08-13 14:40
So the z-index of the modal is 1400, can you try setting the zIndex on the tooltip in the modal to a number greater than that?

**Comment by ljosberinn** [comment] 2020-08-13 14:43
Can confirm it works with `zIndex={1401}`

![image](https://user-images.githubusercontent.com/29307652/90148821-14a4fd00-dd84-11ea-9707-c54c747fbd7f.png)

**Comment by ganeshkrishnasharma** [comment] 2020-08-13 14:43
Yes it works if higher zIndex is given to Tooltip itself! updated sandbox

**Comment by ganeshkrishnasharma** [comment] 2020-08-13 14:44
> Can confirm it works with `zIndex={1401}`
> 
> ![image](https://user-images.githubusercontent.com/29307652/90148821-14a4fd00-dd84-11ea-9707-c54c747fbd7f.png)

is it okay to give higher zIndex? v 1 of chakra suggests not to use zIndex in this way right?

**Comment by jmiazga** [comment] 2020-08-13 14:45
That's great @ganeshkrishnasharma 

I am going to close this issue for now because there is a workaround, and the focus right now is on v1.0

**Closed** 2020-08-13 14:45 UTC
Labels: workaround available ✌️

**Comment by ljosberinn** [comment] 2020-08-13 14:47
In v0.8 surely - v1 comes with a `PortalManager` which takes care of that scenario :)

**Comment by AKomar-sm** [comment] 2023-05-13 12:29
z-index did not help me. This is my workaround.
Create empty 
`<div ref={ref}/>`
and forward  
`portalProps={{ containerRef: ref }}` as `Tooltip` prop. 

At the top add `const ref = useRef(null);`
