### ISSUE TITLE
[Textarea] rows not working anymore

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#1428] opened 2020-07-28 00:26 UTC
**Describe the bug**
In Textarea, *rows* used to work as expected to set the number of rows:

`<Textarea rows={8} />`

it seems that in the new update it's being ignored.

**Suggested solution(s)**

Let *rows* property set the default heights of Textarea.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: latest

**Comment by santialbo** [comment] 2020-07-28 12:56
Chakra is applying a default height to the textarea which takes precedende over the `rows` attribute (I think it should probably be removed).

The work-around is to override the theme height with `height="auto"`, `<Textarea rows={10} height="auto"/>`

**Comment by with-heart** [comment] 2020-07-28 23:31
This was intended to be fixed in #1157. We're omitting `height` and `minHeight` if `props.rows` exists:

https://github.com/chakra-ui/chakra-ui/blob/37caed95f9c6f0fbb66b366ebcbffff0ef20b265/packages/textarea/src/textarea.tsx#L54-L54

`min-height` is no longer set but `height` is still being set. This is because the theme specifies `h` and not `height`:

https://github.com/chakra-ui/chakra-ui/blob/7a1e2a026defa4d130942e8695cfce5b7e1d210b/packages/theme/src/components/input.ts#L16-L16

Whoops! 😅

**Comment by segunadebayo** [comment] 2020-07-29 21:14
Thanks for this issue @akiarostami.

@with-heart I've omitted `h` and height` as well. We'll release an update shortly

**Closed by segunadebayo** 2020-07-29 21:14 UTC
Labels: Type: Bug 🐛, good first issue 👍

**Comment by KeisukeNagakawa** [comment] 2022-04-25 11:09
Hi, I think this is causing problem again. On the latest version, it is not possible to fix rows using “rows” option. I can’t find any alternatives and it is a quite trouble for me…
