### ISSUE TITLE
className did not match between server and client when using useBreakpointValue

### ISSUE THREAD

**Issue by OFranke** [chakra-ui/chakra-ui#2601] opened 2020-11-24 11:56 UTC
# Bug report

## Describe the bug

Using useBreakpointValue in SSR NextJS project I am receiving in the console:
```
Warning: Prop `className` did not match. Server: "chakra-heading css-1jlcwm0" Client: "chakra-heading css-2bykvb"
```

So the issue is I guess, that the Server delivers some style, e.g. for `base` breakpoint which is different from the actual style on the client, e.g. when it's a desktop (lg breakpoint) device.

I guess the server would somehow need to deliver the right styles for a device breakpoint. Not sure how that would work, there are some ways to figure out which browser a client uses (e.g. mobile android chrome, etc.) and then assume if its a base, sm, md, lg, xl device.

I am not even sure if thats a bug at all or if that is simply a thing that cannot be fixed due to the nature of server side rendering.

## To reproduce

See this example, or check the console in https://codesandbox.io/s/modest-haze-pn9z2?file=/pages/index.js

```
import { Heading, HeadingProps, useBreakpointValue } from "@chakra-ui/react";

interface DefaultHeadlineProps extends HeadingProps {
  size: "xs" | "s" | "m" | "l";
}
export const DefaultHeadline: React.FC<DefaultHeadlineProps> = ({
  as,
  size,
  children,
  ...props
}) => {
  const headingSizes = {
    xs: { base: "sm", md: "md", lg: "lg", xl: "xl" },
    s: { base: "md", md: "lg", lg: "xl", xl: "2xl" },
    m: { base: "lg", md: "xl", lg: "2xl", xl: "3xl" },
    l: { base: "xl", md: "2xl", lg: "3xl", xl: "4xl" },
  };
  const headingSize = useBreakpointValue(headingSizes[size]);

  const headingMarginBottom = {
    xs: { base: "2", md: "4", lg: "6" },
    s: { base: "4", md: "6", lg: "10" },
    m: { base: "5", md: "7", lg: "12" },
    l: { base: "6", md: "8", lg: "12" },
  };
  const marginBottomSize = useBreakpointValue(headingMarginBottom[size]);

  return (
    <Heading
      as={as}
      fontFamily="Source Sans Pro"
      size={headingSize}
      textTransform="uppercase"
      fontWeight="bold"
      marginBottom={marginBottomSize}
      {...props}
    >
      {children}
    </Heading>
  );
};
```

## Minimal reproduction

https://codesandbox.io/s/modest-haze-pn9z2?file=/pages/index.js

## Expected behavior

Generate the same css on server and client.

## Additional context

I guess the issue is somewhere here: https://github.com/chakra-ui/chakra-ui/blob/develop/packages/media-query/src/use-breakpoint.ts

The problem is, that we are dependant on the window object which is simply not there on SSR. Is there any way to handle that case for SSR rendered apps?

As a workaround I could just use create different components for my heading sizes like that, which seems to work. Could some1 explain to me why this works? I don't know if I have the right piece of code here: https://github.com/chakra-ui/chakra-ui/blob/develop/packages/layout/src/heading.tsx

```
export const HeadlineL: React.FC<HeadingProps> = ({
  as,
  children,
  ...props
}) => {
  return (
    <Heading
      as={as}
      fontSize={{ base: "xl", md: "2xl", lg: "3xl", xl: "4xl" }}
      textTransform="uppercase"
      fontWeight="bold"
      marginBottom={{ base: "6", md: "8", lg: "12" }}
      {...props}
    >
      {children}
    </Heading>
  );
};
``` 

Edit: I just noticed, that for that specific case I could also solve the responsive font sizes via theme:
```
  const extendedTheme = {
    components: {
      Heading: {
        sizes: {
          "6xl": {
            fontSize: { base: "10px", lg: "50px" },
          },
        },
      },
    },
  };
```

**Comment by nassimbenkirane** [comment] 2020-11-29 19:03
I had a similar issue and my temporary workaround was to use a custom hook that would provide the base value on server side render and then useEffect so that the first rehydration on the client would use the same base value as in the server and then rerender on the client with the actual values from useBreakpointValue

**Comment by with-heart** [comment] 2020-11-29 20:56
@ljosberinn can probably help us here

**Comment by pedro-lb** [comment] 2020-11-30 14:53
Just FYI, this is working perfectly fine in `@chakra-ui/core` `@1.0.0-rc.8`, and we've started to see this problem when upgrading to `@chakra-ui/react@1.0.1`.

May be related to recent commits.

**Comment by pedro-lb** [comment] 2020-11-30 15:10
Here's a workaround for now (in Typescript, just remove the types if you're in js):

`file: hooks/useBreakpointValue/index.tsx`

```tsx
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useEffect, useRef, useState } from "react";
import { useBreakpointValue as useChakraBreakpointValue } from "@chakra-ui/react";

type Values<T> = (Record<string, T> | T[]) & {
  base: any;
}

/**
 * Hook that exposes the result of Chakra UI `useBreakpointValue` but hydrates the result
 * on the first SSR render.
 *
 * This is done to avoid the "className did not match between server and client" error
 * that happens in `@chakra-ui/react@1.0.1`.
 *
 * TODO: Check if this has been fixed in newer versions and remove this hook.
 *
 * @param values Values as accepted in `useBreakpointValue`.
 */
function useBreakpointValue<T = any>(values: Values<T>): T | undefined {
  const firstRender = useRef(true);
  const [, setTick] = useState(0);

  const result = useChakraBreakpointValue(values);

  /**
   * Force a re-render after the first SSR render and ensures the return value
   * of the hook on next render will be the result of the original hook.
   */
  useEffect(() => {
    if (firstRender.current) {
      setTick((prev) => prev + 1);

      firstRender.current = false;
    }
  }, []);

  if (firstRender.current) {
    return values.base;
  }

  return result;
}

export default useBreakpointValue;
```

**Comment by nassimbenkirane** [comment] 2020-12-01 12:59
I don't know where to share this thought but :
Since useBreakpointValue is used in <Show> and <Hide> components, it causes a mismatch between what's rendered on SSR vs on hydration, and React cannot always understand the new DOM structure (in my case it's causing the body to have thé footer's background color...)

It looks like an approach like fresnel's ( https://github.com/artsy/fresnel ) could be used for such scénarios : on SSR it would handle the display with pure CSS

**Comment by segunadebayo** [comment] 2020-12-10 22:50
@ljosberinn recently pushed a fix for this and it has been published in v1.0.3. Feel free to check it out.

We'll re-open if the issue persists.

**Closed by segunadebayo** 2020-12-10 22:50 UTC
Labels: Topic: SSR 💻, Type: Bug 🐛, workaround available ✌️

**Comment by omarkhatibco** [comment] 2020-12-10 23:02
@segunadebayo I just tested the new update, the problem is still exist in Nextjs

**Comment by ljosberinn** [comment] 2020-12-11 08:51
@omarkhatibco can you clarify what you mean with "new update" and/or how you tested it? becaus the change is still unreleased, it will be included in the next patch.

**Comment by nassimbenkirane** [comment] 2020-12-11 08:58
@ljosberinn was the fix not released with 1.0.3 ?
I was gonna try upgrading to 1.0.3 today but if the fix is not released yet, I'll wait 😊

> @ljosberinn recently pushed a fix for this and it has been published in v1.0.3. Feel free to check it out.
> 
> We'll re-open if the issue persists.

**Comment by ljosberinn** [comment] 2020-12-11 09:50
No, I'm afraid Sage was mistaken there, I snuck it in shortly after 1.0.3 release :/

**Comment by omarkhatibco** [comment] 2020-12-11 10:14
@ljosberinn I was testing 1.0.3, I thought it was released.

**Comment by nassimbenkirane** [comment] 2020-12-11 10:24
Great news anyway ! Thanks for the fix 👍👍🔥

**Comment by velddev** [comment] 2022-02-14 00:58
Hey, I think this needs to be reopened as of @chakra-ui/media-query@1.2.3

**Comment by ifightcrime** [comment] 2022-02-22 00:01
> Hey, I think this needs to be reopened as of @chakra-ui/media-query@1.2.3

Hmm yea, I’m having the same problem in @chakra-ui/media-query@2.0.3 with @chakra-ui/react@1.8.5.

**Comment by aspraveen** [comment] 2022-02-25 14:28
I'm also facing this warning.

**Comment by ifightcrime** [comment] 2022-02-26 14:49
It seems like this might be fixed by #5651 if we’re lucky.

**Comment by carloscurcino** [comment] 2023-07-25 21:13
Was this fixed?? I'm having this problem with next. The versions i1m using "@chakra-ui/next-js": "^2.1.4",
    "@chakra-ui/react": "^2.7.1".

**Comment by grevory** [comment] 2023-10-26 21:51
Problem exists with 2.1.5 as well.

**Comment by grevory** [comment] 2023-10-26 23:21
Using "@chakra-ui/next-js": "^2.1.5" and "next": "13.5.6" I got the same error.

I solved this by removing the ColorModeScript tag. I set my initial color mode in the theme object.

`const theme = extendTheme({
  initialColorMode: 'light',
  useSystemColorMode: false,
});

<ChakraProvider theme={theme}>...`

**Comment by bluefeet** [comment] 2023-11-18 06:49
I was able to get around this issue by making a local component called `ColorModeScriptWrapper`:

```tsx
import { ColorModeScript } from '@chakra-ui/react'
import theme from './theme'

export default () =>
  <ColorModeScript initialColorMode={theme.config.initialColorMode} />
```

And then in your `layout.tsx` or `providers.tsx` dynamically import it with SSR **off**:

```tsx
import dynamic from 'next/dynamic'
const ColorModeScriptWrapper = dynamic(() => import('./ColorModeScriptWrapper'), { ssr: false })
```

The wrapper is necessary as Chakra doesn't seem to expose ColorModeScript as an independent module and `import()` doesn't seem to support named imports.

**Comment by chyde** [comment] 2024-01-02 22:30
https://github.com/chakra-ui/chakra-ui/issues/2601#issuecomment-1817415918

`ColorModeScriptWrapper` only worked for one load when running locally...

**Comment by AllanKevinScain** [comment] 2024-01-05 13:38
if i can help, it this work for me:

this code send warning:
```
export const MyComopnent: React.FC<any> = props => {
  const {
    prop0= [],
    prop1= 'white',
    prop2= 'transparent',
    prop3= 'blue.500'
  } = props;

  const borderStyles = {
    bg: prop1,
    borderColor: prop2,
    borderWidth: prop3
 };

  const [top, right, bottom, left] = prop0;

  return (
    <Flex
      position="absolute"
      top={top}
      right={right}
      bottom={bottom}
      left={left}
      {...(!isMediaQueryActive && {
        ...borderStyles,
        ...generateShadow(0)
      })}
    />
  );
};
```

this don't:
```
export const MyComopnent: React.FC<any> = props => {
  const {
    prop0= [],
    prop1= 'white',
    prop2= 'transparent',
    prop3= 'blue.500'
  } = props;
  const [isLargerThan1366] = useMediaQuery('(max-width: 1366px)');
  const [state, setValues] = useState<unknown>();

  const b = {
    bg: prop1,
    borderColor: prop2,
    borderWidth: prop3
 };

  const left = { left: 0 };
  const right = { right: 0 };

  const a = {
    top: 'auto',
    right: 'auto',
    bottom: 'auto',
    left: 'auto',
    ...(position === 'left' ? left : right)
  };

  useEffect(() => {
    setValues({
      ...a,
      ...(!isLargerThan1366 && {
        ...b,
      })
    });
  }, [isLargerThan1366]);

  return (
    <Flex
      position="absolute"
      {...state}
    />
  );
};

```

I believe it is a re-rendering error.

**Comment by sktbrd** [comment] 2024-06-09 00:48
> I was able to get around this issue by making a local component called `ColorModeScriptWrapper`:
> 
> ```tsx
> import { ColorModeScript } from '@chakra-ui/react'
> import theme from './theme'
> 
> export default () =>
>   <ColorModeScript initialColorMode={theme.config.initialColorMode} />
> ```
> 
> And then in your `layout.tsx` or `providers.tsx` dynamically import it with SSR **off**:
> 
> ```tsx
> import dynamic from 'next/dynamic'
> const ColorModeScriptWrapper = dynamic(() => import('./ColorModeScriptWrapper'), { ssr: false })
> ```
> 
> The wrapper is necessary as Chakra doesn't seem to expose ColorModeScript as an independent module and `import()` doesn't seem to support named imports.

that one solved for me too, thanks
