### ISSUE TITLE
ColorScheme inconsistencies when creating new palettes.

### ISSUE THREAD

**Issue by Tfines19** [chakra-ui/chakra-ui#7549] opened 2023-04-05 19:41 UTC
### Description

When I extend a custom theme and provide the same yellow color palette chakra uses to a new palette like `"newYellow":  baseTheme.colors.yellow`, the new colorScheme has different behavior even though if is the exact same colors.  I'm not sure it is a bug and I've noticed other inconsistencies as well.  I have a sandbox to show how the two buttons look completely different even with technically the same color scheme.

edit: looks to be on light mode only atleast for this example.

### Link to Reproduction

https://codesandbox.io/s/exciting-fog-w064fs?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/exciting-fog-w064fs?file=/src/App.js
2. Click on App.js
3. Scroll down to App component
4. Both Yellow and newYellow colorScheme have exact same color palette yet look different.  One is darker, one has white text and other black text.

### Chakra UI Version

2.53

### Browser

Google Chrome  111.0.5563.147 

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sblyvwx** [comment] 2023-04-09 19:48
From what I checked, the button uses accessible color overrides for yellow and cyan on the button component, so you will see the same difference on cyan, but I am pretty sure this is the intended behavior for increased accessibility.

**Comment by segunadebayo** [comment] 2023-04-24 20:53
Duplicate of #7247

**Closed by segunadebayo** 2023-04-24 20:53 UTC
