### ISSUE TITLE
Typescript - Button should not allow disabled prop

### ISSUE THREAD

**Issue by lexanth** [chakra-ui/chakra-ui#7343] opened 2023-02-10 13:05 UTC
### Description

Since https://github.com/chakra-ui/chakra-ui/commit/0f376650efce9eb2d2cba3484ffe4e3a73364504 Button now accepts a `disabled` prop, but does nothing with it - it is always overridden by `isDisabled`, `isLoading` and the button group's `isDisabled`.

It would make it easier to use to either prevent `disabled` being used (in typescript) or include `disabled` in the options which disable a button.

### Link to Reproduction

https://codesandbox.io/s/distracted-matsumoto-iq5sly?file=/src/index.tsx

### Steps to reproduce

1. Click the button
2. Alert is shown

### Chakra UI Version

2.4.9

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The behaviour (ignoring `disabled`) may be valid, but if so it should be excluded from the TS props.

**Comment by pmpwith2i** [comment] 2023-02-10 15:16
@lexanth I opened a PR for adding a deprecation message when users are using the disabled prop, hope it will help :)

**Comment by segunadebayo** [comment] 2023-04-24 20:51
Duplicate of #7269

**Closed by segunadebayo** 2023-04-24 20:51 UTC
