### ISSUE TITLE
clean install and getting error on setup ChakraProvider

### ISSUE THREAD

**Issue by fortniteil** [chakra-ui/chakra-ui#5621] opened 2022-02-19 13:46 UTC
### Description

when i insert ChakraProvider inside index.js on React i am getting error

### Link to Reproduction

https://localhost/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.8.3

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

ERROR in ./node_modules/@emotion/react/dist/emotion-react.browser.esm.js 95:48-68
export 'useInsertionEffect' (imported as 'useInsertionEffect$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
 @ ./node_modules/@chakra-ui/css-reset/dist/chakra-ui-css-reset.esm.js 1:0-40 5:42-48
 @ ./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js 13:0-37 13:0-37
 @ ./src/index.js 10:0-50

**Comment by fortniteil** [comment] 2022-02-19 13:47
its working on the sandbox its happen only on my pc i think, how can i delete everything belong to chakra or whatever?

**Comment by tricertc** [comment] 2022-02-19 15:10
It looks like this was caused by a bug introduced in the _@emotion/react_ and _@emotion/styled_ **v11.8.0** dependencies. 
There's a patch for those on the way and should be fixed in **v11.8.1** (see https://github.com/emotion-js/emotion/pull/2652). In the meantime, I downgraded @emotion/react to 11.7.1 and @emotion/styled to 11.6.0 to get by.

**Comment by TimKolberger** [comment] 2022-02-20 07:56
Closing this as upstream error.

**Closed by TimKolberger** 2022-02-20 07:56 UTC
Labels: Type: Bug 🐛, needs triage
