### ISSUE TITLE
Slider's "onChangeEnd" event not called when the value is the same as before

### ISSUE THREAD

**Issue by Treycos** [chakra-ui/chakra-ui#3516] opened 2021-03-07 18:03 UTC
# 🐛 Bug report

The Slider's `onChangeEnd` event not called when the value is the same as before.

The sentence itself may seem weird, but using `onChangeEnd` is the only way to know if the user released the slider handle which can be useful to trigger other events.

## 💥 Steps to reproduce

1. Render a Slider
2. Drag it around
3. Release it on the same position as before
4. No event :(

## 🧐 Expected behavior

> "onChangeEnd" should be triggered whenever the user releases their mouse click after dragging

## 🧭 Possible Solution

While it appears intuitive to not call a change event if the slider value did not change, it leaves the component without any way to register to the "drag end" event, since there's none so far

Adding a separate drag event or changing the behavior of "onChangeEnd" would both be fine

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   react: 1.3.2     |
| Browser          |      Chrome 90 / Firefox 87      |
| Operating System |    Windows 10    |

## 📝 Additional information

Here's a scenario where it can matter (don't mind the terrible UI layout) :

![screen-capture (10)](https://user-images.githubusercontent.com/19551067/110246151-bc735980-7f66-11eb-9288-7cc1f4a48249.gif)

**Comment by with-heart** [comment] 2021-03-07 22:38
Duplicate of #2887, already resolved in `1.3.4`

**Closed by with-heart** 2021-03-07 22:38 UTC
Labels: Type: Feature 🚀
