### ISSUE TITLE
Still the Command Icon In Search Box of Docs

### ISSUE THREAD

**Issue by Darshan-Bajeja** [chakra-ui/chakra-ui#4371] opened 2021-07-12 15:54 UTC
### Description

I was using Chakra-UI docs and when I looked at the search box, it is still showing me a command key icon (Note: I am using linux and not a mac)

https://chakra-ui.com/

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by abhishekmg** [comment] 2021-07-17 06:24
The issue is present in windows as well , the command key icon appears in search box . 

It looks like this is the condition that determines which icon to be displayed , the condition seems to work fine for me in local dev and prod build though . 


https://github.com/chakra-ui/chakra-ui/blob/3205ad6d55f935f37db8f61d2dde7eaa2481578c/website/src/components/algolia-search.tsx#L38

**Comment by segunadebayo** [comment] 2021-08-09 09:00
This has been fixed in a recent update. Please confirm

**Closed by segunadebayo** 2021-08-09 09:00 UTC
Labels: Type: Bug 🐛, needs triage

**Comment by Darshan-Bajeja** [comment] 2021-08-09 11:25
# @segunadebayo this works perfect now on Linux!
![image](https://user-images.githubusercontent.com/84301900/128699143-e1749131-44b3-4d34-a97a-24d8b8fb90ab.png)
