### ISSUE TITLE
Modal footer hidden in mobile device

### ISSUE THREAD

**Issue by hachimihamza** [chakra-ui/chakra-ui#2495] opened 2020-11-14 11:34 UTC
# Bug report

## Describe the bug

When opening a modal, drawer footer is hidden in mobile devices

## Screenshots
![Screenshot_20201114-113239_Chrome](https://user-images.githubusercontent.com/16524191/99146119-09a48600-266d-11eb-884e-154752cf468a.jpg)

## Suggestion

Change DrawerContent Height from 100vh to 100%
![Screenshot_20201114-112036_Chrome_eee](https://user-images.githubusercontent.com/16524191/99146058-6f444280-266c-11eb-8c11-e5ec756299ba.jpg)

## System information

- OS: Android
- Browser Chrome
- Chakra Version 1.0
- Device mobile

Thanks.

**Comment by with-heart** [comment] 2020-11-14 12:55
Duplicate of #2468

**Closed** 2020-11-14 12:55 UTC

**Comment by Davestring** [comment] 2022-10-27 06:36
@segunadebayo this still happens on the modal component.
