### ISSUE TITLE
Support text cropping for consistent spacing

### ISSUE THREAD

**Issue by kumar303** [chakra-ui/chakra-ui#2096] opened 2020-09-27 03:47 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Yes. Text elements such as `<Heading />` cannot be easily cropped to account for extra top and bottom space [added by the line height](https://medium.com/eightshapes-llc/cropping-away-negative-impacts-of-line-height-84d744e016ce). This introduces spacing inconsistencies which defeats the purpose of using a design system with well defined spacing.

## Describe the solution you'd like

This looks like a good solution https://github.com/chakra-ui/chakra-ui/pull/512 . I am filing an issue because I didn't see one linked to it and it took me a while to find that PR.

## Describe alternatives you've considered

One can use inline styles with the [`:before` and `:after` trick](https://medium.com/eightshapes-llc/cropping-away-negative-impacts-of-line-height-84d744e016ce) (adding negative margins) but the formula might get out of sync if the author changes fonts and forgets to update the formula. The formula itself also needs to know internal values such as line height and size aliases.

## Additional context

This tool shows how to calculate the cropping: http://text-crop.eightshapes.com/

**Comment by segunadebayo** [comment] 2020-09-27 12:51
Thanks for raising this issue @kumar303.

It's a duplicate of #1199 and we have it in mind to add this immediately after the official v1 release.

Permit me to close this out in favor of that issue.

Thanks

**Closed by segunadebayo** 2020-09-27 12:51 UTC

**Comment by kumar303** [comment] 2020-09-27 13:30
Ah, whoops, I couldn't find that one because it didn't have _crop_ in the title, I guess. Thanks!
