### ISSUE TITLE
[Link] Cannot use react-router-dom link in `as` prop

### ISSUE THREAD

**Issue by pandaniell** [chakra-ui/chakra-ui#562] opened 2020-04-03 14:33 UTC
**Describe the bug**
[This](https://chakra-ui.com/link#usage-with-routing-library) example in the docs does not work well with TypeScript using a react-router-dom link

**Expected Behavior**
```typescript
// 1. import { Link as ReactRouterLink } from "react-router-dom"

// 2. Then use it like this
<Link as={ReactRouterLink} to="/home">
  Home
</Link>
```
Should be valid but instead it gives a type error for both properties

**To Reproduce**
1. Install react-router-dom with typings
2. Attempt to create a link like above
[CodeSandbox example](https://codesandbox.io/s/chakra-ts-starter-b40hd)
```

**Comment by segunadebayo** [comment] 2020-04-03 16:10
Hi @pandaniell.

Thanks for reporting this issue. However this issue is a duplicate of an existing issue in #205 . Please subscribe to that issue for future updates.

**Closed by segunadebayo** 2020-04-03 16:10 UTC
